		{"capture" "<c(8470ff)>▼▼▼<c(BBBBBB)>"}

		{"body_broken" "<c(FF1F00)>Корпус разрушен<c(FFFFFF)>"}
		{"body_injured" "<c(FFFF00)>Корпус поврежден<c(FFFFFF)>"}
		{"track_broken" "<c(C71585)>Трак сбит<c(FFFFFF)>"}
		{"track_injured" "<c(C71585)>Трак поврежден<c(FFFFFF)>"}
		{"engine_broken" "<c(FF1F00)>Двигатель сломан<c(FFFFFF)>"}
		{"engine_injured" "<c(FFFF00)>Двигатель поврежден<c(FFFFFF)>"}
		{"gun_broken" "<c(C71585)>Пушка сломана<c(FFFFFF)>"}
		{"gun_injured" "<c(FFFF00)>Пушка повреждена<c(FFFFFF)>"}
		{"turret_broken" "<c(FF1F00)>Башня сломана<c(FFFFFF)>"}
		{"turret_injured" "<c(FFFF00)>Башня повреждена<c(FFFFFF)>"}
		{"turret_pierced" "<c(FFFF00)>Башня пробита<c(FFFFFF)>"}
		{"armor_broken" "<c(FF1F00)>Броня сломана<c(FFFFFF)>"}
		{"armor_injured" "<c(FFFF00)>Броня повреждена<c(FFFFFF)>"}
		{"body_break" "<c(FFFF00)>Корпус сломан<c(FFFFFF)>"}
		{"body_pierced" "<c(FFFF00)>Корпус пробит<c(FFFFFF)>"}
		{"turret_jammed" "<c(FFFF00)>Башню заклинило<c(FFFFFF)>"}
		{"burn_engine" "<c(FFAF00)>Пожар<c(FFFFFF)>"}
		{"burn_fire" "<c(FFAF00)>Пожар<c(FFFFFF)>"}
		{"overheat" "<c(FFAF00)>Перегрев<c(FFFFFF)>"}
		{"strong_overheat" "<c(FFAF00)>Сильный перегрев<c(FFFFFF)>"}
		{"antifire" "<c(00FF00)>Пожар потушен<c(FFFFFF)>"}
		{"inventory_broken" "<c(FF1F00)>Взрыв боекомплекта<c(FFFFFF)>"}
		{"crew_down" "<c(FFFF00)>Экипаж уничтожен<c(FFFFFF)>"}
		{"leave_unit" "<c(CCCCCC)>Покинул технику<c(FFFFFF)>"}
		{"empty" ""}
		{"shock" "<c(BBBBBB)>Экипаж контужен<c(BBBBBB)>"}
		{"charger_die" "<c(CCCCCC)>Погиб заряжающий<c(FFFFFF)>"}
		{"commander_die" "<c(CCCCCC)>Погиб командир<c(FFFFFF)>"}
		{"driver_die" "<c(CCCCCC)>Погиб водитель<c(FFFFFF)>"}
		{"gunner_die" "<c(CCCCCC)>Погиб стрелок<c(FFFFFF)>"}
		{"gunner2_die" "<c(CCCCCC)>Погиб пулеметчик<c(FFFFFF)>"}
;============CW==========
		{"autoloader_malfunction" "<c(C71585)>АЗ неисправен<c(FFFFFF)>"}
		{"era_pierced" "<c(BBBBBB)>Динамическая защита пробита<c(BBBBBB)>"}
		{"guided_weap_disabled" "<c(1F1FCC)>Управляемое оружие отключено<c(BBBBBB)>"}
		{"guided_weap_enabled" "<c(1F1FCC)>Управляемое оружие включено<c(BBBBBB)>"}
		{"heavy_weap_disabled" "<c(1F1FCC)>Тяжелое оружие отключено<c(BBBBBB)>"}
		{"heavy_weap_enabled" "<c(1F1FCC)>Тяжелое оружие включено<c(BBBBBB)>"}
		{"zpu_disabled" "<c(1F1FCC)>ЗПУ отключена<c(BBBBBB)>"}
		{"zpu_enabled" "<c(1F1FCC)>ЗПУ включена<c(BBBBBB)>"}
		{"zpu_careful" "<c(1F1FCC)>ЗПУ по ситуации<c(BBBBBB)>"}
		{"radar_disabled" "<c(1F1FCC)>Радар отключен<c(BBBBBB)>"}
		{"radar_enabled" "<c(1F1FCC)>Радар включен<c(BBBBBB)>"}
		{"radar_careful" "<c(1F1FCC)>Радар временно отключен<c(BBBBBB)>"}
		{"salvo_launch" "<c(1F1FCC)>Парный пуск<c(BBBBBB)>"}
		{"single_launch" "<c(1F1FCC)>Одиночный пуск<c(BBBBBB)>"}
		{"cargobay_opened" "<c(1F1FCC)>Грузовой люк открыт<c(BBBBBB)>"}
		{"cargobay_closed" "<c(1F1FCC)>Грузовой люк закрыт<c(BBBBBB)>"}
		{"misfire" "<c(1F1FCC)>Осечка<c(BBBBBB)>"}
		{"return_to_base" "<c(1F1FCC)>Возврат на базу<c(BBBBBB)>"}
		{"return_to_base_cancel" "<c(1F1FCC)>Отмена возврата на базу<c(BBBBBB)>"}
		{"hydro_steering_off" "<c(1F1FCC)>Регулируемая подвеска выключена<c(BBBBBB)>"}
		{"hydro_steering_on" "<c(1F1FCC)>Регулируемая подвеска включена<c(BBBBBB)>"}
		{"smoke_reloading" "<c(1F1FCC)>Дымовой гранатомёт заряжается<c(BBBBBB)>"}
		{"smoke_reloaded" "<c(1F1FCC)>Дымовой гранатомёт заряжен<c(BBBBBB)>"}
		{"dont_see_anything" "<c(1F1FCC)>Ничего не вижу<c(BBBBBB)>"}
		{"airborne_M"
			{"ammo_storage_autocannon_damaged" "Попадание в боеукладку"}
			{"ammo_storage_mgun_damaged" "Попадание в боеукладку"}
			{"OLS_damaged" "<c(FFFF00)>ОЛС сломана<c(FFFFFF)>"}
			{"wing_damaged" "<c(FFFF00)>Крыло повреждено<c(FFFFFF)>"}
			{"aileron_damaged" "<c(FFFF00)>Элерон поврежден<c(FFFFFF)>"}
			{"elevator_damaged" "<c(FFFF00)>Руль высоты поврежден<c(FFFFFF)>"}
			{"rudder_damaged" "<c(FFFF00)>Руль направления поврежден<c(FFFFFF)>"}
			{"stabilizer_damaged" "<c(FFFF00)>Стабилизатор поврежден<c(FFFFFF)>"}
			{"tail_damaged" "<c(FFFF00)>Киль поврежден<c(FFFFFF)>"}
			{"flap_damaged" "<c(FFFF00)>Закрылок поврежден<c(FFFFFF)>"}
			{"wheels_damaged" "<c(FFFF00)>Шасси сломано<c(FFFFFF)>"}
			{"engine_damaged" "<c(FF1F00)>Двигатель сломан<c(FFFFFF)>"}
			{"engine1_damaged" "<c(FFFF00)>Левый двигатель сломан<c(FFFFFF)>"}
			{"engine2_damaged" "<c(FFFF00)>Правый двигатель сломан<c(FFFFFF)>"}
			{"enginea_damaged" "<c(FFFF00)>Первый двигатель сломан<c(FFFFFF)>"}
			{"engineb_damaged" "<c(FFFF00)>Второй двигатель сломан<c(FFFFFF)>"}
			{"enginec_damaged" "<c(FFFF00)>Третий двигатель сломан<c(FFFFFF)>"}
			{"engined_damaged" "<c(FFFF00)>Четвертый двигатель сломан<c(FFFFFF)>"}
			{"main_reductor_damaged" "<c(FF1F00)>Поломка главного редуктора<c(FFFFFF)>"}
			{"main_reductor_malfunction" "<c(FF1F00)>Стружка в главном редукторе<c(FFFFFF)>"}
			{"propeller_damaged" "<c(FF1F00)>Несущий винт поврежден<c(FFFFFF)>"}
			{"tail_shaft_damaged" "<c(FF1F00)>Хвостовой вал поврежден<c(FFFFFF)>"}
			{"tail_rotor_damaged" "<c(FF1F00)>Хвостовой винт поврежден<c(FFFFFF)>"}
			{"driver_panel_damaged" "<c(FF1F00)>Приборная панель повреждена<c(FFFFFF)>"}
			{"steering_damaged" "<c(FF1F00)>Тяга управления повреждена<c(FFFFFF)>"}
			{"hydrosystem_damaged" "<c(FFFF00)>Гидросистема повреждена<c(FFFFFF)>"}
			{"antifire_damaged" "<c(FFFF00)>Cистема пожаротушения повреждена<c(FFFFFF)>"}
			{"hydrosystem_tank_damaged" "<c(FF1F00)>Бак гидросистемы поврежден<c(FFFFFF)>"}
			{"PPU_damaged" "<c(C71585)>Аккумулятор поврежден<c(FFFFFF)>"}
			{"APU_damaged" "<c(C71585)>ВСУ повреждена<c(FFFFFF)>"}
			{"ir_active_def_damaged" "<c(FFFF00)>КОЭП поврежден<c(FFFFFF)>"}
			{"ECM_damaged" "<c(FFFF00)>Система РЭБ повреждена<c(FFFFFF)>"}
			{"targeting_pod_damaged" "<c(FFFF00)>Контейнер обзора поврежден<c(FFFFFF)>"}
			{"electronics_damaged" "<c(FFFF00)>Электроника повреждена<c(FFFFFF)>"}
			{"PrPNK_damaged" "<c(FFFF00)>Прицельный комплекс поврежден<c(FFFFFF)>"}
			{"radar_damaged" "<c(FFFF00)>Радар поврежден<c(FFFFFF)>"}
			{"Laser_TD_damaged" "<c(FFFF00)>ЛЦУ поврежден<c(FFFFFF)>"}
			{"Radar_TD_damaged" "<c(FFFF00)>Радар наведения поврежден<c(FFFFFF)>"}
			{"fuel_tank_damaged" "<c(FFFF00)>Бак пробит<c(FFFFFF)>"}
			{"gun_damaged" "<c(FFFF00)>Пушка повреждена<c(FFFFFF)>"}
			{"mgun_damaged" "<c(FFFF00)>Пулемет поврежден<c(FFFFFF)>"}
			{"ptur_damaged" "<c(FFFF00)>ПУ повреждена<c(FFFFFF)>"}
			{"nar_damaged" "<c(FFFF00)>Блок НАР поврежден<c(FFFFFF)>"}
			{"flares_damaged" "<c(FFFF00)>Блок ловушек поврежден<c(FFFFFF)>"}
			{"chaff_damaged" "<c(FFFF00)>Блок отражателей поврежден<c(FFFFFF)>"}

			{"wing_repaired" "<c(00FF00)>Крыло отремонтировано<c(FFFFFF)>"}
			{"aileron_repaired" "<c(00FF00)>Элерон отремонтирован<c(FFFFFF)>"}
			{"elevator_repaired" "<c(00FF00)>Руль высоты отремонтирован<c(FFFFFF)>"}
			{"rudder_repaired" "<c(00FF00)>Руль направления отремонтирован<c(FFFFFF)>"}
			{"stabilizer_repaired" "<c(00FF00)>Стабилизатор отремонтирован<c(FFFFFF)>"}
			{"tail_repaired" "<c(00FF00)>Киль отремонтирован<c(FFFFFF)>"}
			{"flap_repaired" "<c(00FF00)>Закрылок отремонтирован<c(FFFFFF)>"}
			{"wheels_repaired" "<c(00FF00)>Шасси отремонтировано<c(FFFFFF)>"}
			{"engine_repaired" "<c(00FF00)>Двигатель отремонтирован<c(FFFFFF)>"}
			{"engine1_repaired" "<c(00FF00)>Левый двигатель отремонтирован<c(FFFFFF)>"}
			{"engine2_repaired" "<c(00FF00)>Правый двигатель отремонтирован<c(FFFFFF)>"}
			{"enginea_repaired" "<c(00FF00)>Первый двигатель отремонтирован<c(FFFFFF)>"}
			{"engineb_repaired" "<c(00FF00)>Второй двигатель отремонтирован<c(FFFFFF)>"}
			{"enginec_repaired" "<c(00FF00)>Третий двигатель отремонтирован<c(FFFFFF)>"}
			{"engined_repaired" "<c(00FF00)>Четвертый двигатель отремонтирован<c(FFFFFF)>"}
			{"main_reductor_repaired" "<c(00FF00)>Главный редуктор отремонтирован<c(FFFFFF)>"}
			{"propeller_repaired" "<c(00FF00)>Несущий винт отремонтирован<c(FFFFFF)>"}
			{"main_reductor_repaired" "<c(00FF00)>Главный редуктор отремонтирован<c(FFFFFF)>"}
			{"tail_shaft_repaired" "<c(00FF00)>Хвостовой вал отремонтирован<c(FFFFFF)>"}
			{"tail_rotor_repaired" "<c(00FF00)>Хвостовой винт отремонтирован<c(FFFFFF)>"}
			{"driver_panel_repaired" "<c(00FF00)>Приборная панель отремонтирована<c(FFFFFF)>"}
			{"steering_repaired" "<c(00FF00)>Тяга управления отремонтирована<c(FFFFFF)>"}
			{"hydrosystem_repaired" "<c(00FF00)>Гидросистема отремонтирована<c(FFFFFF)>"}
			{"hydrosystem_tank_repaired" "<c(00FF00)>Бак гидросистемы отремонтирован<c(FFFFFF)>"}
			{"antifire_repaired" "<c(00FF00)>Cистема пожаротушения отремонтирована<c(FFFFFF)>"}
			{"PPU_repaired" "<c(00FF00)>Аккумулятор отремонтирован<c(FFFFFF)>"}
			{"APU_repaired" "<c(00FF00)>ВСУ отремонтирована<c(FFFFFF)>"}
			{"ir_active_def_repaired" "<c(00FF00)>КОЭП отремонтирован<c(FFFFFF)>"}
			{"ECM_repaired" "<c(00FF00)>Система РЭБ отремонтирована<c(FFFFFF)>"}
			{"targeting_pod_repaired" "<c(00FF00)>Контейнер обзора отремонтирован<c(FFFFFF)>"}
			{"electronics_repaired" "<c(00FF00)>Электроника отремонтирована<c(FFFFFF)>"}
			{"PrPNK_repaired" "<c(00FF00)>Прицельный комплекс отремонтирован<c(FFFFFF)>"}
			{"radar_repaired" "<c(00FF00)>Радар отремонтирован<c(FFFFFF)>"}
			{"Laser_TD_repaired" "<c(00FF00)>ЛЦУ отремонтирован<c(FFFFFF)>"}
			{"Radar_TD_repaired" "<c(00FF00)>Радар наведения отремонтирован<c(FFFFFF)>"}
			{"gun_repaired" "<c(00FF00)>Пушка отремонтирована<c(FFFFFF)>"}
			{"mgun_repaired" "<c(00FF00)>Пулемет отремонтирован<c(FFFFFF)>"}
			{"ptur_repaired" "<c(00FF00)>ПУ отремонтирована<c(FFFFFF)>"}
			{"nar_repaired" "<c(00FF00)>Блок НАР отремонтирован<c(FFFFFF)>"}
			{"flares_repaired" "<c(00FF00)>Блок ловушек отремонтирован<c(FFFFFF)>"}
			{"chaff_repaired" "<c(00FF00)>Блок отражателей отремонтирован<c(FFFFFF)>"}

			{"reload_zur" "<c(1F1FCC)>Заряжаем ЗУР<c(BBBBBB)>"}
			{"reload_missile" "<c(1F1FCC)>Заряжаем ракету<c(BBBBBB)>"}
		}
		{"armored"
			{"driver_triplex_damaged" "<c(FFFF00)>Триплекс водителя сломан<c(FFFFFF)>"}
			{"commander_triplex_damaged" "<c(FFFF00)>Прицел наводчика сломан<c(FFFFFF)>"}
			{"additional_triplex_damaged" "<c(FFFF00)>Прицел сломан<c(FFFFFF)>"}
			{"additional_triplex1_damaged" "<c(FFFF00)>Прицел сломан<c(FFFFFF)>"}
			{"ammo_storage_damaged" "<c(FFAF00)>Попадание в боеукладку<c(FFFFFF)>"}
			{"body_pierced" "Корпус пробит"}
			{"turret_pierced" "Башня пробита"}
			{"fuel_tank_damaged" "<c(FFFF00)>Бак пробит<c(FFFFFF)>"}
			{"kaz_radar_damaged" "<c(C71585)>Радар КАЗ поврежден<c(FFFFFF)>"}
			{"kaz_mortar_damaged" "<c(C71585)>Мортира КАЗ повреждена<c(FFFFFF)>"}
			{"Shtora_damaged" "<c(C71585)>КОЭП поврежден<c(FFFFFF)>"}
			{"gun_damaged" "<c(C71585)>Пушка повреждена<c(FFFFFF)>"}
			{"transmission_damaged" "<c(FF1F00)>Трансмиссия повреждена<c(FFFFFF)>"}
			{"panel_engine_connectors_damaged" "<c(FF1F00)>Тяги управления повреждены<c(FFFFFF)>"}
			{"front_wheels_damaged" "<c(C71585)>Натяжение гусениц утрачено<c(FFFFFF)>"}
			{"driver_panel_damaged" "<c(FF1F00)>Приборная панель повреждена<c(FFFFFF)>"}
			{"mgun_damaged" "<c(C71585)>Пулемет сломан<c(FFFFFF)>"}
			{"gun1_damaged" "<c(C71585)>Дополнительное орудие повреждено<c(FFFFFF)>"}
			{"ptur_damaged" "<c(C71585)>ПУ ПТУР повреждена<c(FFFFFF)>"}
			{"autoloader_damaged" "<c(C71585)>АЗ поврежден<c(FFFFFF)>"}
			{"turret_move_engine_damaged" "<c(C71585)>Привод башни поврежден<c(FFFFFF)>"}
			{"stabilizer_damaged" "<c(FF1F00)>Привод пушки поврежден<c(FFFFFF)>"}
			{"gunner_panel_damaged" "<c(C71585)>Пульт наводчика поврежден<c(FFFFFF)>"}
			{"PPU_damaged" "<c(C71585)>Аккумулятор поврежден<c(FFFFFF)>"}
			{"APU_damaged" "<c(C71585)>ВСУ повреждена<c(FFFFFF)>"}
			{"hull_integrity_damaged" "<c(FFFF00)>Герметичность нарушена<c(FFFFFF)>"}
            {"driver_dead" "<c(C71585)>Член экипажа мёртв<c(FFFFFF)>"}
			{"gunner_dead" "<c(C71585)>Член экипажа мёртв<c(FFFFFF)>"}
			{"shooter_dead" "<c(C71585)>Член экипажа мёртв<c(FFFFFF)>"}
			{"charger_dead" "<c(C71585)>Член экипажа мёртв<c(FFFFFF)>"}
			{"commander_dead" "<c(C71585)>Член экипажа мёртв<c(FFFFFF)>"}

			{"driver_triplex_repaired" "<c(00FF00)>Триплекс водителя отремонтирован<c(FFFFFF)>"}
			{"commander_triplex_repaired" "<c(00FF00)>Прицел наводчика отремонтирован<c(FFFFFF)>"}
			{"additional_triplex_repaired" "<c(00FF00)>Прицел отремонтирован<c(FFFFFF)>"}
			{"additional_triplex1_repaired" "<c(00FF00)>Прицел отремонтирован<c(FFFFFF)>"}
			{"driver_panel_repaired" "<c(00FF00)>Приборная панель отремонтирована<c(FFFFFF)>"}
			{"transmission_repaired" "<c(00FF00)>Трансмиссия отремонтирована<c(FFFFFF)>"}
			{"panel_engine_connectors_repaired" "<c(00FF00)>Тяги управления отремонтированы<c(FFFFFF)>"}
			{"front_wheels_repaired" "<c(00FF00)>Натяжение гусениц восстановлено<c(FFFFFF)>"}
			{"autoloader_repaired" "<c(00FF00)>АЗ отремонтирован<c(FFFFFF)>"}
			{"mgun_repaired" "<c(00FF00)>Пулемет отремонтирован<c(FFFFFF)>"}
			{"gun_repaired" "<c(00FF00)>Пушка отремонтирована<c(FFFFFF)>"}
			{"gun1_repaired" "<c(00FF00)>Дополнительное орудие отремонтировано<c(FFFFFF)>"}
			{"ptur_repaired" "<c(00FF00)>ПУ ПТУР отремонтирована<c(FFFFFF)>"}
			{"kaz_mortar_repaired" "<c(00FF00)>Мортира КАЗ отремонтирована<c(FFFFFF)>"}
			{"turret_move_engine_repaired" "<c(00FF00)>Привод башни отремонтирован<c(FFFFFF)>"}
			{"stabilizer_repaired" "<c(00FF00)>Привод пушки отремонтирован<c(FFFFFF)>"}
			{"gunner_panel_repaired" "<c(00FF00)>Пульт наводчика отремонтирован<c(FFFFFF)>"}
			{"PPU_repaired" "<c(00FF00)>Аккумулятор отремонтирован<c(FFFFFF)>"}
			{"APU_repaired" "<c(00FF00)>ВСУ отремонтирована<c(FFFFFF)>"}
			{"hull_integrity_repaired" "<c(00FF00)>Герметичность восстановлена<c(FFFFFF)>"}
			{"kaz_radar_repaired" "<c(00FF00)>Радар КАЗ отремонтирован<c(FFFFFF)>"}
			{"Shtora_repaired" "<c(00FF00)>КОЭП отремонтирован<c(FFFFFF)>"}


		}
		{"other"
			{"ptur_damaged" "<c(C71585)>ПУ ПТУР повреждена<c(FFFFFF)>"}
			{"ptur_repaired" "<c(00FF00)>ПУ ПТУР отремонтирована<c(FFFFFF)>"}
			{"radar_damaged" "<c(C71585)>Радар сломан<c(FFFFFF)>"}
			{"radar_array_damaged" "<c(C71585)>Радарная решетка повреждена<c(FFFFFF)>"}

		}
		{"selfdestruct"
			{"delay_0" "<c(FF1F00)>180<c(FFFFFF)>"}
			{"delay_10" "<c(FF1F00)>170<c(FFFFFF)>"}
			{"delay_20" "<c(FF1F00)>160<c(FFFFFF)>"}
			{"delay_30" "<c(FF1F00)>150<c(FFFFFF)>"}
			{"delay_40" "<c(FF1F00)>140<c(FFFFFF)>"}
			{"delay_50" "<c(FF1F00)>130<c(FFFFFF)>"}
			{"delay_60" "<c(FF1F00)>120<c(FFFFFF)>"}
			{"delay_70" "<c(FF1F00)>110<c(FFFFFF)>"}
			{"delay_80" "<c(FF1F00)>100<c(FFFFFF)>"}
			{"delay_90" "<c(FF1F00)>90<c(FFFFFF)>"}
			{"delay_100" "<c(FF1F00)>80<c(FFFFFF)>"}
			{"delay_110" "<c(FF1F00)>70<c(FFFFFF)>"}
			{"delay_120" "<c(FF1F00)>60<c(FFFFFF)>"}
			{"delay_130" "<c(FF1F00)>50<c(FFFFFF)>"}
			{"delay_140" "<c(FF1F00)>40<c(FFFFFF)>"}
			{"delay_150" "<c(FF1F00)>30<c(FFFFFF)>"}
			{"delay_160" "<c(FF1F00)>20<c(FFFFFF)>"}
			{"delay_170" "<c(FF1F00)>10<c(FFFFFF)>"}
			{"delay_171" "<c(FF1F00)>9<c(FFFFFF)>"}
			{"delay_172" "<c(FF1F00)>8<c(FFFFFF)>"}
			{"delay_173" "<c(FF1F00)>7<c(FFFFFF)>"}
			{"delay_174" "<c(FF1F00)>6<c(FFFFFF)>"}
			{"delay_175" "<c(FF1F00)>5<c(FFFFFF)>"}
			{"delay_176" "<c(FF1F00)>4<c(FFFFFF)>"}
			{"delay_177" "<c(FF1F00)>3<c(FFFFFF)>"}
			{"delay_178" "<c(FF1F00)>2<c(FFFFFF)>"}
			{"delay_179" "<c(FF1F00)>1<c(FFFFFF)>"}
		}