;Revised by maaa - DTTGOC
;LocalGen2
;Extra data placeholder
;Extra data placeholder
;rev 04.07.2022

;________________________________________________________________________________________________________
;faction name
	;brigade name
		;row number
			{"example_item"													"Example name"}
;________________________________________________________________________________________________________
;1 ряд
;2 ряд 
;3 ряд
;4 ряд
;5 ряд
;6 ряд