;Revised by maaa - DTTGOC
;LocalGen2
;Extra data placeholder
;Extra data placeholder
;rev 04.07.2022

;-vehicle
	;-modern
		;air_modern
			;cn
				;j-10c
					{"j-10c_aa"							"<c(FFFFFF)e(shadow)>J-10C"													" <c(FFAF00)e(shadow)>AA</c>"}
					{"j-10c_ab"							"<c(FFFFFF)e(shadow)>J-10C"													" <c(FFAF00)e(shadow)>AA+SGB</c>"}
					{"j-10c_patrol"						"<c(FFFFFF)e(shadow)>J-10C"													" <c(FFAF00)e(shadow)>AA+drop tanks</c>"}
				;jh-7a
					{"jh-7a_antirad"					"<c(FFFFFF)e(shadow)>JH-7A"													" <c(FFAF00)e(shadow)>SEAD</c>"}
					{"jh-7a_at"							"<c(FFFFFF)e(shadow)>JH-7A"													" <c(FFAF00)e(shadow)>CBU</c>"}
					{"jh-7a_bomber"						"<c(FFFFFF)e(shadow)>JH-7A"													" <c(FFAF00)e(shadow)>IB</c>"}
					{"jh-7a_kab"						"<c(FFFFFF)e(shadow)>JH-7A"													" <c(FFAF00)e(shadow)>Strike</c>"}
					{"jh-7a_light"						"<c(FFFFFF)e(shadow)>JH-7A"													" <c(FFAF00)e(shadow)>Light CAS</c>"}
					{"jh-7a_strike"						"<c(FFFFFF)e(shadow)>JH-7A"													" <c(FFAF00)e(shadow)>Precision Strike</c>"}
				{"ch802"								"<c(FFAF00)e(shadow)>CH-802<c(00FF00)e(shadow)> Rainbow<c(FFFFFF)e(shadow)> UAV</c>"}
				{"mi171_china"							"<c(FFFFFF)e(shadow)>Mi-171Sh</c>"}
				{"su-35_aa_china"						"<c(FFFFFF)e(shadow)>Su-35S"													" <c(FFAF00)e(shadow)>AA</c>"}
				{"z-10_support"							"<c(FFFFFF)e(shadow)>Z-10"													" <c(FFAF00)e(shadow)>CAS</c>"}
			;fr
				;nh90
					{"nh90"								"<c(FFFFFF)e(shadow)>NH-90</c>"}
					{"nh90_sas"							"<c(FFFFFF)e(shadow)>NH-90</c>"}
				;tiger_hap
					{"tiger_hap_at"						"<c(FFFFFF)e(shadow)>RAH-2 Tiger"											" <c(FFAF00)e(shadow)>AT</c>"}
					{"tiger_hap_escort"					"<c(FFFFFF)e(shadow)>RAH-2 Tiger"											" <c(FFAF00)e(shadow)>Escort</c>"}
					{"tiger_hap_support"				"<c(FFFFFF)e(shadow)>RAH-2 Tiger"											" <c(FFAF00)e(shadow)>CAS</c>"}
			;gb
				;eurofighter
					{"eurofighter_aa"					"<c(FFFFFF)e(shadow)>Typhoon"												" <c(FFAF00)e(shadow)>AA</c>"}
					{"eurofighter_ab"					"<c(FFFFFF)e(shadow)>Typhoon"												" <c(FFAF00)e(shadow)>AA+LGB</c>"}
					{"eurofighter_antirad"				"<c(FFFFFF)e(shadow)>Typhoon"												" <c(FFAF00)e(shadow)>SEAD</c>"}
					{"eurofighter_strike"				"<c(FFFFFF)e(shadow)>Typhoon"												" <c(FFAF00)e(shadow)>Strike</c>"}
					{"eurofighter_support"				"<c(FFFFFF)e(shadow)>Typhoon"												" <c(FFAF00)e(shadow)>CAS</c>"}
				;tornado
					{"tornado_gr1_bomber"				"<c(FFFFFF)e(shadow)>Tornado GR1"											" <c(FFAF00)e(shadow)>Bomber</c>"}
					{"tornado_gr1_carpet"				"<c(FFFFFF)e(shadow)>Tornado GR1"											" <c(FFAF00)e(shadow)>CBU</c>"}
					{"tornado_gr4_antirad"				"<c(FFFFFF)e(shadow)>Tornado GR4"											" <c(FFAF00)e(shadow)>SEAD</c>"}
					{"tornado_gr4_at"					"<c(FFFFFF)e(shadow)>Tornado GR4"											" <c(FFAF00)e(shadow)>AT</c>"}
					{"tornado_gr4_bomber1"				"<c(FFFFFF)e(shadow)>Tornado GR4"											" <c(FFAF00)e(shadow)>Bomber</c>"}
					{"tornado_gr4_strike"				"<c(FFFFFF)e(shadow)>Tornado GR4"											" <c(FFAF00)e(shadow)>Strike</c>"}
					{"tornado_gr4_support"				"<c(FFFFFF)e(shadow)>Tornado GR4"											" <c(FFAF00)e(shadow)>CAS</c>"}
					{"tornado_gr4_support_light"		"<c(FFFFFF)e(shadow)>Tornado GR4"											" <c(FFAF00)e(shadow)>Light CAS</c>"}
				{"f-35b_stealthaa_british"				"<c(FFFFFF)e(shadow)>F-35B"													" <c(FFAF00)e(shadow)>AA"						" <c(13E1C5)e(shadow)>Stealth state</c>"}
			;ger
				{"aladin"								"<c(00FF00)e(shadow)>EMT Aladin<c(FFFFFF)e(shadow)> UAV</c>"}
			;ir
				{"shahed136_base"						"<c(00FF00)e(shadow)>Shahed-136<c(FFFFFF)e(shadow)> UAV</c>"}
			;rus
				;an-12
					{"an-12"							"<c(FFFFFF)e(shadow)>Аn-12</c>"}
					{"an-12bk"							"<c(FFFFFF)e(shadow)>Аn-12BK</c>"}
				;eleron
					{"eleron3sv"						"<c(00FF00)e(shadow)>Eleron-3SV<c(FFFFFF)e(shadow)> UAV</c>"}
					{"eleron_catapult"					"<c(00FF00)e(shadow)>Eleron-3SV<c(FFFFFF)e(shadow)> UAV catapult</c>"}
					{"eleron_control"					"<c(00FF00)e(shadow)>Eleron-3SV<c(FFFFFF)e(shadow)> UAV control unit</c>"}
				;ka52
					{"ka52"								"<c(FFFFFF)e(shadow)>Ka-52 Alligator</c>"}
					{"ka52_germes"						"<c(FFFFFF)e(shadow)>Ka-52 Alligator - Hermes-A</c>"}
					{"ka52k"							"<c(FFFFFF)e(shadow)>Ka-52K Katran</c>"}
				;mi-24v
					{"mi-24v"							"<c(FFFFFF)e(shadow)>Mi-24V</c>"}
					{"mi-24v_2"							"<c(FFFFFF)e(shadow)>Mi-24V</c>"}
				;mi17
					{"mi17"								"<c(FFFFFF)e(shadow)>Mi-8MTV UV-32-57</c>"}
					{"mi17_b8"							"<c(FFFFFF)e(shadow)>Mi-8MTV B-8V20A</c>"}
					{"mi17_china"						"<c(FFFFFF)e(shadow)>Mi-171Sh</c>"}
					{"mi17_unarmed"						"<c(FFFFFF)e(shadow)>Mi-8MTV</c>"}
				;mi8amtsh
					{"mi8amtsh"							"<c(FFFFFF)e(shadow)>Mi-8AMTSh</c>"}
					{"mi8amtsh1"						"<c(FFFFFF)e(shadow)>Mi-8AMTSh-1</c>"}
					{"mi8amtsh1_mgnar"					"<c(FFFFFF)e(shadow)>Mi-8AMTSh-1</c>"}
					{"mi8amtsh1_mgun"					"<c(FFFFFF)e(shadow)>Mi-8AMTSh-1</c>"}
				;mig-21bis
					{"mig-21bis_aa"						"<c(FFFFFF)e(shadow)>MiG-21bis"												" <c(FFAF00)e(shadow)>AA</c>"}
					{"mig-21bis_bomber"					"<c(FFFFFF)e(shadow)>MiG-21bis"												" <c(FFAF00)e(shadow)>Bomber</c>"}
					{"mig-21bis_support"				"<c(FFFFFF)e(shadow)>MiG-21bis"												" <c(FFAF00)e(shadow)>CAS</c>"}
				;mig-29k
					{"mig-29k_aa"						"<c(FFFFFF)e(shadow)>MiG-29K"												" <c(FFAF00)e(shadow)>AA</c>"}
					{"mig-29k_ab"						"<c(FFFFFF)e(shadow)>MiG-29K"												" <c(FFAF00)e(shadow)>AA+LGB</c>"}
					{"mig-29k_antiship"					"<c(FFFFFF)e(shadow)>MiG-29K"												" <c(FFAF00)e(shadow)>AShM</c>"}
				;mig-29s
					{"mig-29s_aa"						"<c(FFFFFF)e(shadow)>MiG-29C"												" <c(FFAF00)e(shadow)>AA</c>"}
					{"mig-29s_aa_vks"					"<c(FFFFFF)e(shadow)>MiG-29C"												" <c(FFAF00)e(shadow)>AA</c>"}
					{"mig-29s_ab"						"<c(FFFFFF)e(shadow)>MiG-29C"												" <c(FFAF00)e(shadow)>CAS</c>"}
				;su-25sm_part1
					{"su-25sm_accurate"					"<c(FFFFFF)e(shadow)>Su-25SM"												" <c(FFAF00)e(shadow)>Precision Strike</c>"}
					{"su-25sm_miner"					"<c(FFFFFF)e(shadow)>Su-25SM"												" <c(FFAF00)e(shadow)>Minelayer</c>"}
					{"su-25sm_support"					"<c(FFFFFF)e(shadow)>Su-25SM"												" <c(FFAF00)e(shadow)>CAS</c>"}
					{"su-25sm_support_light"			"<c(FFFFFF)e(shadow)>Su-25SM"												" <c(FFAF00)e(shadow)>Light CAS</c>"}
				;su-25sm_part2
					{"su-25sm_at"						"<c(FFFFFF)e(shadow)>Su-25SM"												" <c(FFAF00)e(shadow)>AT</c>"}
					{"su-25sm_strike"					"<c(FFFFFF)e(shadow)>Su-25SM"												" <c(FFAF00)e(shadow)>Strike</c>"}
				;su-34
					{"su-34_accurate_2"					"<c(FFFFFF)e(shadow)>Su-34"													" <c(FFAF00)e(shadow)>Precision Strike</c>"}
					{"su-34_antiair"					"<c(FFFFFF)e(shadow)>Su-34"													" <c(FFAF00)e(shadow)>AA</c>"}
					{"su-34_antirad"					"<c(FFFFFF)e(shadow)>Su-34"													" <c(FFAF00)e(shadow)>SEAD</c>"}
					{"su-34_antisam"					"<c(FFFFFF)e(shadow)>Su-34"													" <c(FFAF00)e(shadow)>SEAD/ASM</c>"}
					{"su-34_antitank"					"<c(FFFFFF)e(shadow)>Su-34"													" <c(FFAF00)e(shadow)>AT</c>"}
					{"su-34_bomber"						"<c(FFFFFF)e(shadow)>Su-34"													" <c(FFAF00)e(shadow)>Precision Strike</c>"}
					{"su-34_medbomber"					"<c(FFFFFF)e(shadow)>Su-34"													" <c(FFAF00)e(shadow)>Bomber</c>"}
					{"su-34_strike"						"<c(FFFFFF)e(shadow)>Su-34"													" <c(FFAF00)e(shadow)>Strike</c>"}
					{"su-34_support"					"<c(FFFFFF)e(shadow)>Su-34"													" <c(FFAF00)e(shadow)>CAS</c>"}
				;su-35
					{"su-35_aa"							"<c(FFFFFF)e(shadow)>Su-35C"												" <c(FFAF00)e(shadow)>AA</c>"}
					{"su-35_at"							"<c(FFFFFF)e(shadow)>Su-35C"												" <c(FFAF00)e(shadow)>AT</c>"}
					{"su-35_strike"						"<c(FFFFFF)e(shadow)>Su-35C"												" <c(FFAF00)e(shadow)>Strike</c>"}
				;su-50
					{"su-50_aa"							"<c(FFFFFF)e(shadow)>Su-57"													" <c(FFAF00)e(shadow)>AA</c>"}
					{"su-50_ab"							"<c(FFFFFF)e(shadow)>Su-57"													" <c(FFAF00)e(shadow)>AA+LGB</c>"}
					{"su-50_at"							"<c(FFFFFF)e(shadow)>Su-57"													" <c(FFAF00)e(shadow)>AT</c>"}
				{"il-76td"								"<c(FFFFFF)e(shadow)>Il-76TD</c>"}
				{"Ka50"									"<c(FFFFFF)e(shadow)>Ka-50 Black Shark</c>"}
				{"Ka50sh"								"<c(FFFFFF)e(shadow)>Ka-50Sh Ball</c>"}
				{"mi-24vm"								"<c(FFFFFF)e(shadow)>Mi-35M3</c>"}
				{"mi28n"								"<c(FFFFFF)e(shadow)>Mi-28N</c>"}
				{"mi28ub"								"<c(FFFFFF)e(shadow)>Mi-28UB</c>"}
			;usa
				;a-10_csupport
					{"a-10c_AT"							"<c(FFFFFF)e(shadow)>A-10C"													" <c(FFAF00)e(shadow)>AT</c>"}
					{"a-10c_support"					"<c(FFFFFF)e(shadow)>A-10C"													" <c(FFAF00)e(shadow)>CAS</c>"}
					{"a-10c_support_light"				"<c(FFFFFF)e(shadow)>A-10C"													" <c(FFAF00)e(shadow)>Light CAS</c>"}
				;apache
					{"apache"							"<c(FFFFFF)e(shadow)>AH-64D Longbow</c>"}
					{"apache_brit"						"<c(FFFFFF)e(shadow)>WAH-64D Longbow</c>"}
					{"apache_spike"						"<c(FFFFFF)e(shadow)>AH-64D Longbow</c>"}
				;e-2c_hawkeye
					{"e-2c_hawkeye"						"<c(FFFFFF)e(shadow)>E-2C Hawkeye</c>"}
					{"e-2c_hawkeye_france"				"<c(FFFFFF)e(shadow)>E-2C Hawkeye</c>"}
				;f-16c
					{"f-16c_aa"							"<c(FFFFFF)e(shadow)>F-16C"													" <c(FFAF00)e(shadow)>AA</c>"}
					{"f-16c_antirad"					"<c(FFFFFF)e(shadow)>F-16C"													" <c(FFAF00)e(shadow)>SEAD</c>"}
					{"f-16c_antirad_2"					"<c(FFFFFF)e(shadow)>F-16C"													" <c(FFAF00)e(shadow)>SEAD</c>"}
					{"f-16c_antiship"					"<c(FFFFFF)e(shadow)>F-16C"													" <c(FFAF00)e(shadow)>AShM</c>"}
					{"f-16c_strike"						"<c(FFFFFF)e(shadow)>F-16C"													" <c(FFAF00)e(shadow)>Strike</c>"}
					{"f-16c_support"					"<c(FFFFFF)e(shadow)>F-16C"													" <c(FFAF00)e(shadow)>CAS</c>"}
					{"f-16c_support_pol"				"<c(FFFFFF)e(shadow)>F-16C"													" <c(FFAF00)e(shadow)>CAS</c>"}
				;f-22
					{"f-22_antiair"						"<c(FFFFFF)e(shadow)>F-22"													" <c(FFAF00)e(shadow)>AA</c>"}
					{"f-22_fighter-bomber"				"<c(FFFFFF)e(shadow)>F-22"													" <c(FFAF00)e(shadow)>AA+JDAM</c>"}
				;f-35b
					{"f-35b_aa"							"<c(FFFFFF)e(shadow)>F-35B"													" <c(FFAF00)e(shadow)>AA"						" <c(13E1C5)e(shadow)>Stealth state</c>"}
					{"f-35b_stealthaa"					"<c(FFFFFF)e(shadow)>F-35B"													" <c(FFAF00)e(shadow)>AA"						" <c(13E1C5)e(shadow)>Stealth state</c>"}
					{"f-35b_stealthab"					"<c(FFFFFF)e(shadow)>F-35B"													" <c(FFAF00)e(shadow)>CAS"						" <c(13E1C5)e(shadow)>Stealth state</c>"}
					{"f-35b_strike"						"<c(FFFFFF)e(shadow)>F-35B"													" <c(FFAF00)e(shadow)>Strike</c>"}
					{"f-35b_support"					"<c(FFFFFF)e(shadow)>F-35B"													" <c(FFAF00)e(shadow)>CAS</c>"}
				;f-35c
					{"f-35c_aa"							"<c(FFFFFF)e(shadow)>F-35C"													" <c(FFAF00)e(shadow)>AA</c>"}
					{"f-35c_stealthaa"					"<c(FFFFFF)e(shadow)>F-35C"													" <c(FFAF00)e(shadow)>AA"						" <c(13E1C5)e(shadow)>Stealth state</c>"}
					{"f-35c_stealthab"					"<c(FFFFFF)e(shadow)>F-35C"													" <c(FFAF00)e(shadow)>AA+JDAM"					" <c(13E1C5)e(shadow)>Stealth state</c>"}
					{"f-35c_strike"						"<c(FFFFFF)e(shadow)>F-35C"													" <c(FFAF00)e(shadow)>AShM</c>"}
					{"f-35c_support"					"<c(FFFFFF)e(shadow)>F-35C"													" <c(FFAF00)e(shadow)>CAS</c>"}
				;uh60
					{"sikorsky s-70c2"					"<c(FFFFFF)e(shadow)>S-70C-2</c>"}
					{"uh60"								"<c(FFFFFF)e(shadow)>UH-60 Black Hawk</c>"}
				{"a-10c_bomber"							"<c(FFFFFF)e(shadow)>A-10C"													" <c(FFAF00)e(shadow)>Bomber</c>"}
				{"ah1z"									"<c(FFFFFF)e(shadow)>AH-1Z  Viper</c>"}
				{"mh-6"									"<c(FFFFFF)e(shadow)>MH-6 Little Bird</c>"}
				{"mq9"									"<c(FFFFFF)e(shadow)>MQ-9A Block 1</c>"}
				{"rq11raven"							"<c(FFAF00)e(shadow)>RQ-11<c(FFFFFF)e(shadow)> Raven<c(FFFFFF)> UAV</c>"}
				{"uh1y"									"<c(FFFFFF)e(shadow)>UH-1Y Venom</c>"}
		;art_modern
			;cn
				{"dong_feng_15b"						"<c(FFFFFF)e(shadow)>DF-15B</c>"}
				{"plz-05"								"<c(FFFFFF)e(shadow)>PLZ-05</c>"}
				{"phl_81"								"<c(FFFFFF)e(shadow)>PHL-81</c>"}
			;gb
				{"as_90"								"<c(FFFFFF)e(shadow)>AS-90</c>"}
			;ger
				{"lars2"								"<c(FFFFFF)e(shadow)>Lars 2</c>"}
				{"pzh2000"								"<c(FFFFFF)e(shadow)>PzH 2000 A1</c>"}
			;rus
				;9k72
					{"9k72"								"<c(FFFFFF)e(shadow)>9K72 Elbrus</c>"}
					{"9k72_for_single"					"<c(FFFFFF)e(shadow)>9K72 Elbrus</c>"}
				;bm-30_tornado_s
					{"bm-30_smerch"						"<c(FFFFFF)e(shadow)>BM-30 Smerch</c>"}
					{"bm-30_tornado_s"					"<c(FFFFFF)e(shadow)>9K515 Tornado-S</c>"}
				{"2c3_akaciya"							"<c(FFFFFF)e(shadow)>2S3 Akatsiya</c>"}
				{"2c9"									"<c(FFFFFF)e(shadow)>2S9 Nona-S</c>"}
				{"iskander"								"<c(FFFFFF)e(shadow)>9K720 Iskander-M</c>"}
				{"Koalition"							"<c(FFFFFF)e(shadow)>2S35 Koalitsiya-SV</c>"}
				{"Msta"									"<c(FFFFFF)e(shadow)>2S19 Msta-S</c>"}
				{"Mstasm2"								"<c(FFFFFF)e(shadow)>2S19M2 Msta-SM2</c>"}
				{"tos-1a_solntsepek"					"<c(FFFFFF)e(shadow)>TOS-1A Solntsepyok</c>"}
			;usa
				;m142_himars
					{"m142_himars"						"<c(FFFFFF)e(shadow)>M142 Himars</c>"}
					{"m142_himarser"					"<c(FFFFFF)e(shadow)>M142 Himars ER</c>"}
				;mlrs_new
					{"mrls"								"<c(FFFFFF)e(shadow)>M270A1</c>"}
					{"mrls_2"							"<c(FFFFFF)e(shadow)>M270A1</c>"}
					{"mrls_atacms"						"<c(FFFFFF)e(shadow)>MGM-140 ATACMS</c>"}
					{"mrls_atacms_2"					"<c(FFFFFF)e(shadow)>MGM-140 ATACMS Cluster warhead</c>"}
					{"mrls_atacms_nato"					"<c(FFFFFF)e(shadow)>MGM-140 ATACMS</c>"}
				{"dana_152mm"							"<c(FFFFFF)e(shadow)>vz.77 DANA</c>"}
				{"paladin"								"<c(FFFFFF)e(shadow)>M109A6 Paladin</c>"}
		;btr_modern
			;cn
				;zbl_08
					{"zbl_08"							"<c(FFFFFF)e(shadow)>ZBL-08</c>"}
					{"zbl_08_atgm"						"<c(FFFFFF)e(shadow)>ZBL-08 ATGM</c>"}
				;zsl_92
					{"zsl-92a"							"<c(FFFFFF)e(shadow)>ZSL-92</c>"}
					{"zsl-92b"							"<c(FFFFFF)e(shadow)>ZSL-92B ATGM</c>"}
				{"aft-10"								"<c(FFFFFF)e(shadow)>AFT-10</c>"}
				{"aft-9"								"<c(FFFFFF)e(shadow)>AFT-9</c>"}
				{"hq_7b"								"<c(FFFFFF)e(shadow)>HQ-7B</c>"}
				{"pgz-04"								"<c(FFFFFF)e(shadow)>PGZ-04</c>"}
				{"pgz-09"								"<c(FFFFFF)e(shadow)>PGZ-09</c>"}
				{"zbd-86"								"<c(FFFFFF)e(shadow)>ZBD-86</c>"}
				{"zbd04a"								"<c(FFFFFF)e(shadow)>ZBD-04A</c>"}
				{"zbd86a"								"<c(FFFFFF)e(shadow)>ZBD-86A</c>"}
			;fr
				;amx10rcr
					{"amx10rc"							"<c(FFFFFF)e(shadow)>AMX-10RC</c>"}
					{"amx10rcr"							"<c(FFFFFF)e(shadow)>AMX-10RCR</c>"}
				;vbi_reco
					{"vbl_anf"							"<c(FFFFFF)e(shadow)>VBL - AN-F1 7.62 LMG</c>"}
					{"vbl_milan"						"<c(FFFFFF)e(shadow)>VBL Milan</c>"}
					{"vbl_mistral"						"<c(FFFFFF)e(shadow)>VBL Mistral</c>"}
					{"vbl_reco"							"<c(FFFFFF)e(shadow)>VBL Reco 12.7 HMG</c>"}
				{"vab_mephisto"							"<c(FFFFFF)e(shadow)>VAB HOT</c>"}
				{"vab_reco"								"<c(FFFFFF)e(shadow)>VAB Reco</c>"}
				{"vbci"									"<c(FFFFFF)e(shadow)>VBCI</c>"}
				{"vbci_2"								"<c(FFFFFF)e(shadow)>VBCI-2</c>"}
				{"vbci_vpc"								"<c(FFFFFF)e(shadow)>VBCI VPC</c>"}
			;gb
				;warrior
					{"warrior"							"<c(FFFFFF)e(shadow)>MCV-80 Warrior</c>"}
					{"warrior_wrap2"					"<c(FFFFFF)e(shadow)>MCV-80 Warrior WRAP-2</c>"}
				{"ajax"									"<c(FFFFFF)e(shadow)>AJAX(Scout SV)</c>"}
				{"boxer_artec_mgun"						"<c(FFFFFF)e(shadow)>Boxer MIV</c>"}
				{"boxer_gun_noptur_gb"					"<c(FFFFFF)e(shadow)>ARTEC Boxer Block 1</c>"}
				{"fv432_mk2"							"<c(FFFFFF)e(shadow)>Fv432 Mk2</c>"}
				{"fv107scimitar_mk2"					"<c(FFFFFF)e(shadow)>FV107 Scimitar</c>"}
			;ger
				;boxer_apc
					{"boxer_gmg"						"<c(FFFFFF)e(shadow)>Boxer A2</c>"}
					{"boxer_mgun"						"<c(FFFFFF)e(shadow)>Boxer A1</c>"}
				;boxer_gun
					{"boxer_gun"						"<c(FFFFFF)e(shadow)>Boxer Block 1</c>"}				
					{"boxer_gun_noptur"					"<c(FFFFFF)e(shadow)>Boxer Block 1</c>"}
				;fennek
					{"fennek"							"<c(FFFFFF)e(shadow)>KWM Fennek HMG</c>"}
					{"fennek_gmg"						"<c(FFFFFF)e(shadow)>KWM Fennek AGL</c>"}
				;tpz1a6
					{"tpz1a6"							"<c(FFFFFF)e(shadow)>TpZ 1A6 Fuchs</c>"}
					{"tpz1a6_uk"						"<c(FFFFFF)e(shadow)>Fox NBC</c>"}
				{"marder_1a3"							"<c(FFFFFF)e(shadow)>Marder 1A3</c>"}
				{"puma"									"<c(FFFFFF)e(shadow)>SPz Puma VJTF</c>"}
				{"puma_noptur"							"<c(FFFFFF)e(shadow)>SPz Puma</c>"}
				{"wiesel1_gun"							"<c(FFFFFF)e(shadow)>Wiesel 1 Mk20</c>"}
				{"wiesel1_tow"							"<c(FFFFFF)e(shadow)>Wiesel 1 TOW</c>"}
			;pol
				{"kto_rosomak"							"<c(FFFFFF)e(shadow)>KTO Rosomak</c>"}
			;rus
				;-mtlb_new
					{"mtlb"								"<c(FFFFFF)e(shadow)>MT-LB</c>"}
					{"mtlb_new"							"<c(FFFFFF)e(shadow)>MT-LB</c>"}
					{"mtlb_vmk"							"<c(FFFFFF)e(shadow)>MT-LB VMK</c>"}
					{"mtlb_vmk_no_ammobox"				"<c(FFFFFF)e(shadow)>MT-LB BMK</c>"}
				;9k35_sterla-10
					{"9k35_strela-10"					"<c(FFFFFF)e(shadow)>9K35 Strela-10</c>"}
					{"9k35_strela-10m3"					"<c(FFFFFF)e(shadow)>9K35 Strela-10M3</c>"}
					{"9k35_strela-10mn"					"<c(FFFFFF)e(shadow)>9K35 Strela-10MN</c>"}
				;bmd1
					{"bmd1"								"<c(FFFFFF)e(shadow)>BMD-1 Mod.1974</c>"}
					{"bmd1p"							"<c(FFFFFF)e(shadow)>BMD-1P</c>"}
				;bmd4m
					{"bmd4m"							"<c(FFFFFF)e(shadow)>BMD-4M</c>"}
					{"bmd4m_sadovnitsa"					"<c(FFFFFF)e(shadow)>BMD-4M with armor kit</c>"}
				;bmp2_new
					{"bmp2_new"							"<c(FFFFFF)e(shadow)>BMP-2</c>"}
					{"bmp2_new_without_ptyr"			"<c(FFFFFF)e(shadow)>BMP-2</c>"}
				;bmp3
					{"bmp3"								"<c(FFFFFF)e(shadow)>BMP-3 Mod.1987</c>"}
					{"bmp3_2"							"<c(FFFFFF)e(shadow)>BMP-3 Mod.1998</c>"}
					{"bmp3_3"							"<c(FFFFFF)e(shadow)>BMP-3 Mod.2017</c>"}
					{"bmp3_derivation"					"<c(FFFFFF)e(shadow)>BMP-3 Derivation</c>"}
					{"bmp3_dz"							"<c(FFFFFF)e(shadow)>BMP-3 ERA</c>"}
					{"bmp3m"							"<c(FFFFFF)e(shadow)>BMP-3M</c>"}
				;btr-d
					{"btr-d"							"<c(FFFFFF)e(shadow)>BTR-D</c>"}
					{"btr-d_zu"							"<c(FFFFFF)e(shadow)>BTR-ZD Skrezhet</c>"}
					{"btr-rd"							"<c(FFFFFF)e(shadow)>BTR-RD Robot</c>"}
				;btr80_new
					{"btr80_2_new"						"<c(FFFFFF)e(shadow)>BTR-80 Mod.1984</c>"}
					{"btr80_new"						"<c(FFFFFF)e(shadow)>BTR-80 Mod.2008</c>"}
				;btr80a.82a
					{"btr80a"							"<c(FFFFFF)e(shadow)>BTR-80A Mod.1994</c>"}
					{"btr82a"							"<c(FFFFFF)e(shadow)>BTR-82А</c>"}
					{"btr82a_mgun"						"<c(FFFFFF)e(shadow)>BTR-82</c>"}
				;btr90_kom
					{"armbr_hqcar"						"<c(FFFFFF)e(shadow)>SVR Tank Brigade</c>"}
					{"artbr_hqcar"						"<c(FFFFFF)e(shadow)>SVR Artillery Brigade</c>"}
					{"btr90_kom"						"<c(FFFFFF)e(shadow)>BTR-90K</c>"}
					{"mot_hqcar"						"<c(FFFFFF)e(shadow)>SVR Motorized Rifle Brigade</c>"}
					{"specbr_hqcar"						"<c(FFFFFF)e(shadow)>BV Naval Infantry Brigade</c>"}
					{"vdv_hqcar"						"<c(FFFFFF)e(shadow)>Russian Airborne Forces (VDV)</c>"}
					{"vvs_hqcar"						"<c(FFFFFF)e(shadow)>VKS & SVR SAM Brigades</c>"}
				;mtlb_6mx
					{"mtlb_6ma"							"<c(FFFFFF)e(shadow)>MT-LBM 6MА</c>"}
					{"mtlb_6mb"							"<c(FFFFFF)e(shadow)>MT-LBM 6MB</c>"}
				;uran9
					{"Uran9_assault"					"<c(FFFFFF)e(shadow)>Uran-9</c>"}
					{"Uran9_assault2"					"<c(FFFFFF)e(shadow)>Uran-9</c>"}
					{"Uran9_support"					"<c(FFFFFF)e(shadow)>Uran-9</c>"}
				{"9p149_shturm-s"						"<c(FFFFFF)e(shadow)>Shturm-S</c>"}
				{"bmd2"									"<c(FFFFFF)e(shadow)>BMD-2 Budka</c>"}
				{"bmp1_new"								"<c(FFFFFF)e(shadow)>BMP-1</c>"}
				{"bmp1_kliver"							"<c(FFFFFF)e(shadow)>BMP-1M Kliver</c>"}
				{"bmp1_new_zbd-86"						"<c(FFFFFF)e(shadow)>ZBD86</c>"}
				{"bmp2m_new"							"<c(FFFFFF)e(shadow)>BMP-2M Berezhok</c>"}
				{"brdm2"								"<c(FFFFFF)e(shadow)>BRDM-2</c>"}
				{"brdm2_atgm"							"<c(FFFFFF)e(shadow)>9P148 Konkurs</c>"}
				{"brdm2_strela"							"<c(FFFFFF)e(shadow)>BRDM-2 9K31 Strela-1</c>"}
				{"btr60"								"<c(FFFFFF)e(shadow)>BTR-60PB</c>"}
				{"btr70"								"<c(FFFFFF)e(shadow)>BTR-70 Mod.1972</c>"}
				{"btr90"								"<c(FFFFFF)e(shadow)>BTR-90 Rostok</c>"}
				{"bumerang_k-16"						"<c(FFFFFF)e(shadow)>K-16 Bumerang</c>"}
				{"bumerang_k-17"						"<c(FFFFFF)e(shadow)>K-17 Bumerang</c>"}
				{"kamaz_43269"							"<c(FFFFFF)e(shadow)>BPM-97 (KamАZ-43269 Vistrel)</c>"}
				{"kurganec_b-10"						"<c(FFFFFF)e(shadow)>B-10 Kurganets-25</c>"}
				{"kurganec_b-11"						"<c(FFFFFF)e(shadow)>B-11 Kurganets-25</c>"}
				{"sprutsd"								"<c(FFFFFF)e(shadow)>2S25 Sprut-SD</c>"}
			;usa
				;bredly
					{"bredly"							"<c(FFFFFF)e(shadow)>M2A2 Bradley</c>"}
					{"m2a3"								"<c(FFFFFF)e(shadow)>M2A3 Bradley</c>"}
					{"m2a3_brat"						"<c(FFFFFF)e(shadow)>M2A3 Bradley Busk III</c>"}
				;lav25_2
					{"bund_hqcar"						"<c(FFFFFF)e(shadow)>Bundeswehr</c>"}
					{"lav25_2"							"<c(FFFFFF)e(shadow)>LAV-25 C2</c>"}
					{"ngrd_hqcar"						"<c(FFFFFF)e(shadow)>National Guard of the U.S.</c>"}
					{"usaf_hqcar"						"<c(FFFFFF)e(shadow)>U.S. Air Force</c>"}
					{"usarmy_hqcar"						"<c(FFFFFF)e(shadow)>U.S. Army</c>"}
					{"usart_hqcar"						"<c(FFFFFF)e(shadow)>U.S. Army Field Artillery Branch</c>"}
					{"usmc_hqcar"						"<c(FFFFFF)e(shadow)>U.S. Marines Corps</c>"}
				;m1126
					{"m1126"							"<c(FFFFFF)e(shadow)>M1126 Stryker ICV</c>"}
					{"m1126_jav"						"<c(FFFFFF)e(shadow)>M1126 Stryker ICV - CROWS-J</c>"}
					{"m1126_mk19"						"<c(FFFFFF)e(shadow)>M1126 Stryker ICV</c>"}
				;m113
					{"m113a"							"<c(FFFFFF)e(shadow)>M113</c>"}
					{"m113a_israel"						"<c(FFFFFF)e(shadow)>M113</c>"}
				{"aavp7"								"<c(FFFFFF)e(shadow)>AAVP-7A1 EAKK</c>"}
				{"lav-ad"								"<c(FFFFFF)e(shadow)>LAV-AD</c>"}
				{"lav-atws"								"<c(FFFFFF)e(shadow)>LAV-ATWS</c>"}
				{"lav25"								"<c(FFFFFF)e(shadow)>LAV-25</c>"}
				{"m-1129"								"<c(FFFFFF)e(shadow)>M1129 Stryker MC</c>"}
				{"m1128"								"<c(FFFFFF)e(shadow)>M1128 Stryker MGS</c>"}
				{"m1134"								"<c(FFFFFF)e(shadow)>M1134 Stryker ATGM</c>"}
				{"M163"									"<c(FFFFFF)e(shadow)>M163 VADS</c>"}
				{"m163machbet"							"<c(FFFFFF)e(shadow)>Machbet</c>"}
				{"m2_adats"								"<c(FFFFFF)e(shadow)>ADATS</c>"}
				{"shorad"								"<c(FFFFFF)e(shadow)>M-SHORAD</c>"}
		;cannon_modern
			;cn
				{"hj73_stan"							"<c(FFFFFF)e(shadow)>HJ-73</c>"}
				{"hj8_stan"								"<c(FFFFFF)e(shadow)>HJ-8</c>"}
				{"pbp-172"								"<c(FFFFFF)e(shadow)>PBP-172</c>"}
				{"pl-66"								"<c(FFFFFF)e(shadow)>PL-66</c>"}
				{"qjz-89_stan"							"<c(FFFFFF)e(shadow)>QJZ-89</c>"}
				{"qlz04"								"<c(FFFFFF)e(shadow)>QLZ-04</c>"}
				{"radar_bs903"							"<c(FFFFFF)e(shadow)>BS-903</c>"}
				{"type63_rocket2"						"<c(FFFFFF)e(shadow)>Type 63</c>"}
				{"type_pp87"							"<c(FFFFFF)e(shadow)>Type 87</c>"}
			;fr
				{"mistral_stan"							"<c(FFFFFF)e(shadow)>Mistral</c>"}
				{"mmp_stan"								"<c(FFFFFF)e(shadow)>MMP</c>"}
				{"mo_81_llr_f1"							"<c(FFFFFF)e(shadow)>MO-81 LLR F1</c>"}
				{"mortarfr"								"<c(FFFFFF)e(shadow)>MO-120 RT61</c>"}
			;gb
				;mstar_v6
					{"mstar_v6"							"<c(FFFFFF)e(shadow)>MSTAR v6</c>"}
					{"mstar_v6usa"						"<c(FFFFFF)e(shadow)>MSTAR v6</c>"}
				{"exactor_mk2"							"<c(FFFFFF)e(shadow)>Exactor Mk2</c>"}
				{"l118"									"<c(FFFFFF)e(shadow)>105mm L118 light gun</c>"}
				{"l16_mortar"							"<c(FFFFFF)e(shadow)>L16</c>"}
				{"m2_stan"								"<c(FFFFFF)e(shadow)>Browning M2HB</c>"}
			;ger
				;gmg_stan
					{"gmg_stan"							"<c(FFFFFF)e(shadow)>GMG</c>"}
					{"mg3_stan"							"<c(FFFFFF)e(shadow)>MG3</c>"}
				;spike_stan
					{"spike_stan"						"<c(FFFFFF)e(shadow)>SPIKE-ER</c>"}
					{"spike_stan_idf"					"<c(FFFFFF)e(shadow)>SPIKE-ER</c>"}
				{"fh-70"								"<c(FFFFFF)e(shadow)>FH-70</c>"}
				{"milan_stan"							"<c(FFFFFF)e(shadow)>MILAN</c>"}
				{"ptur_tow_nato"						"<c(FFFFFF)e(shadow)>BMG-71 TOW</c>"}
			;rus
				;d30
					{"d30"								"<c(FFFFFF)e(shadow)>122mm D-30А</c>"}
					{"pl-96"							"<c(FFFFFF)e(shadow)>122mm PL-96</c>"}
				;psnr5
					{"psnr5"							"<c(FFFFFF)e(shadow)>PSNR-5</c>"}
					{"psnr5m"							"<c(FFFFFF)e(shadow)>PSNR-5M</c>"}
				;ur83p
					{"ur_83p"							"<c(FFFFFF)e(shadow)>UR-83P</c>"}
				{"2a65_msta_b"							"<c(FFFFFF)e(shadow)>2A65 Msta-B</c>"}
				{"2b11"									"<c(FFFFFF)e(shadow)>2B11 Sani</c>"}
				{"2b14_podnos"							"<c(FFFFFF)e(shadow)>2B14 Podnos</c>"}
				{"ags17"								"<c(FFFFFF)e(shadow)>АGS-17</c>"}
				{"ags30_stan"							"<c(FFFFFF)e(shadow)>АGS-30</c>"}
				{"kord_stan"							"<c(FFFFFF)e(shadow)>Kord</c>"}
				{"kornet_base_stan"						"<c(FFFFFF)e(shadow)>9P163M-1 Kornet-P</c>"}
				{"kornet_stan"							"<c(FFFFFF)e(shadow)>9P163M-2 Kornet-D</c>"}
				{"malytka_stan"							"<c(FFFFFF)e(shadow)>9M14M Malyutka-M</c>"}
				{"metis_m"								"<c(FFFFFF)e(shadow)>9K115-1 Metis-M</c>"}
				{"mt12_rapira"							"<c(FFFFFF)e(shadow)>MT-12 Rapira</c>"}
				{"p-37"									"<c(FFFFFF)e(shadow)>P-37</c>"}
				{"pkm_stan"								"<c(FFFFFF)e(shadow)>PKM</c>"}
				{"ptur_konkurs"							"<c(FFFFFF)e(shadow)>9M113 Konkurs</c>"}
				{"spg_9"								"<c(FFFFFF)e(shadow)>SPG-9M</c>"}
				{"vant_vm_shield"						"<c(FFFFFF)e(shadow)>Vant-VM</c>"}
				{"vasilek"								"<c(FFFFFF)e(shadow)>2B9 Vasilek</c>"}
				{"ZU23-2"								"<c(FFFFFF)e(shadow)>ZU-23-2</c>"}
			;usa
				;patriot
					{"patriot_launcher"					"<c(FFFFFF)e(shadow)>MIM-104 Patriot M901 Launching Station</c>"}
					{"patriot_radar"					"<c(FFFFFF)e(shadow)>MIM-104 Patriot AN/MPQ-53</c>"}
				{"hawk_rls"								"<c(FFFFFF)e(shadow)>MIM-23 Hawk AN/MPQ-50 IPAR</c>"}
				{"hawk_cwar"							"<c(FFFFFF)e(shadow)>MIM-23 Hawk AN/MPQ-55 ICWAR</c>"}
				{"m119"									"<c(FFFFFF)e(shadow)>105mm M119A1</c>"}
				{"m252"									"<c(FFFFFF)e(shadow)>M252</c>"}
				{"mk19"									"<c(FFFFFF)e(shadow)>Mk19</c>"}
				{"ptur_tow"								"<c(FFFFFF)e(shadow)>BMG-71 TOW</c>"}
		;car_modern
			;cn
				;shaanxi_sx2190_ammo
					{"shaanxi_sx2190_ammo"				"<c(FFFFFF)e(shadow)>Shaanxi SX2190 Logistic truck</c>"}
					{"shaanxi_sx2190_ammo_track"		"<c(FFFFFF)e(shadow)></c>"}
					{"shaanxi_sx2190_art_pvo"			"<c(FFFFFF)e(shadow)>Shaanxi SX2190 Arty/SAM Logistic truck</c>"}
					{"shaanxi_sx2190_avia"				"<c(FFFFFF)e(shadow)>Shaanxi SX2190 AVN Logistic truck</c>"}
				{"beijing_bj2022"						"<c(FFFFFF)e(shadow)>Beijing BJ2022</c>"}
				{"dongfeng__mengshi_sk131"				"<c(FFFFFF)e(shadow)>Dongfeng Mengshi CSK-131 HMG</c>"}
				{"dongfeng_mengshi_hj8"					"<c(FFFFFF)e(shadow)>Dongfeng Mengshi TL-4 ATGM</c>"}
				{"hq-16b_launcher"						"<c(FFFFFF)e(shadow)>HQ-16B VLS</c>"}
				{"hq-16b_radar"							"<c(FFFFFF)e(shadow)>HQ-16B HT-233 PESA radar</c>"}
				{"lyt2021"								"<c(FFFFFF)e(shadow)>LYT2021</c>"}
				{"pcp001_cs_sm1"						"<c(FFFFFF)e(shadow)>PCP-001</c>"}
				{"shaanxi_sx2190_passenger"				"<c(FFFFFF)e(shadow)>Shaanxi SX2190 Transport truck</c>"}
				{"shaanxi_sx2190_repair"				"<c(FFFFFF)e(shadow)>Shaanxi SX2190 Engineering truck</c>"}
				{"shaanxi_sx2190_tanker"				"<c(FFFFFF)e(shadow)>Shaanxi SX2190 Tanker</c>"}
			;ir
				{"shahed136_truck"						"<c(FFFFFF)e(shadow)>Shahed-136 launcher</c>"}					 
			;cz
				{"tatra_t810"							"<c(FFFFFF)e(shadow)>TATRA T810</c>"}					 
			;fr
				{"peugeot_p4"							"<c(FFFFFF)e(shadow)>Peugeot P4</c>"}
				{"renault_gbc_180"						"<c(FFFFFF)e(shadow)>Renault GBC 180</c>"}
				{"sampt_arabel"							"<c(FFFFFF)e(shadow)>SAMPT Arabel</c>"}
				{"sampt_mamba"							"<c(FFFFFF)e(shadow)>SAMPT Mamba</c>"}
			;gb
				;land_rover_truck
					{"land_rover_exactor"				"<c(FFFFFF)e(shadow)>Land Rover-Exactor</c>"}
					{"land_rover_snatch"				"<c(FFFFFF)e(shadow)>Land Rover Snatch</c>"}
				;land_rover_turret
					{"land_rover_atgm"					"<c(FFFFFF)e(shadow)>Land Rover MWIM ATGM</c>"}
					{"land_rover_mgun"					"<c(FFFFFF)e(shadow)>Land Rover MWIM HMG</c>"}
				;mwwmik_jackal2
					{"mwwik_jackal2_gmg"				"<c(FFFFFF)e(shadow)>Jackal 2 AGL</c>"}
					{"mwwik_jackal2_mgun"				"<c(FFFFFF)e(shadow)>Jackal 2 HMG</c>"}
				{"husky_tsv"							"<c(FFFFFF)e(shadow)>Husky TSV</c>"}
				{"man_sx44"								"<c(FFFFFF)e(shadow)>MAN SX44</c>"}
				{"pinzgauer_710m"						"<c(FFFFFF)e(shadow)>Pinzgauer 710m</c>"}
			;ger
				;dingo2a2
					{"dingo2a1"							"<c(FFFFFF)e(shadow)>ATF Dingo</c>"}
					{"dingo2a2"							"<c(FFFFFF)e(shadow)>ATF Dingo</c>"}
				{"dingo2a2_gun"							"<c(FFFFFF)e(shadow)>ATF Dingo 2A2</c>"}
				;man
					{"man_ammo"							"<c(FFFFFF)e(shadow)>MAN KAT1 Logistic truck</c>"}
					{"man_art"							"<c(FFFFFF)e(shadow)>MAN KAT1 Arty/SAM Logistic truck</c>"}
					{"man_avia"							"<c(FFFFFF)e(shadow)>MAN KAT1 AVN Logistic truck</c>"}
					{"man_passenjer"					"<c(FFFFFF)e(shadow)>MAN KAT1 1 Transport truck</c>"}
					{"man_repair"						"<c(FFFFFF)e(shadow)>MAN KAT1 Engineering truck</c>"}
				{"kwm_ampv"								"<c(FFFFFF)e(shadow)>KWM AMPV</c>"}
				{"man_tanker"							"<c(FFFFFF)e(shadow)>MAN KAT1 Tanker</c>"}
				{"roland"								"<c(FFFFFF)e(shadow)>Roland 3</c>"}
				{"wolf"									"<c(FFFFFF)e(shadow)>Wolf W461</c>"}
			;rus
				;gas66
					{"gaz66"							"<c(FFFFFF)e(shadow)>GАZ-66</c>"}
					{"gaz66_inf"						"<c(FFFFFF)e(shadow)>GАZ-66</c>"}
				;gaz_tiger
					{"gaz_tigr"							"<c(FFFFFF)e(shadow)>GАZ-233014 Tigr</c>"}
					{"gaz_tigr_mgun"					"<c(FFFFFF)e(shadow)>GАZ-233014 Tigr</c>"}
					{"gaz_tigr_mgun2"					"<c(FFFFFF)e(shadow)>GАZ-233014 Tigr</c>"}
				;pantsir
					{"pantsir_s"						"<c(FFFFFF)e(shadow)>Pantsir-S</c>"}
					{"pantsir_s1"						"<c(FFFFFF)e(shadow)>Pantsir-S1</c>"}
				;ural-4320_all
					{"ural-4320_fuel"					"<c(FFFFFF)e(shadow)>Ural-4320 Tanker</c>"}
					{"ural-4320_kamaz_tent"				"<c(FFFFFF)e(shadow)>Ural-4320 Transport truck</c>"}
					{"ural-4320_kung"					"<c(FFFFFF)e(shadow)>Ural-4320 Kung</c>"}
					{"ural-4320_long_tent"				"<c(FFFFFF)e(shadow)>Ural-4320-31 Transport truck</c>"}
					{"ural-4320_long_tent2"				"<c(FFFFFF)e(shadow)>Ural-4320-31 Transport truck</c>"}
					{"ural-4320_long_zu23-2"			"<c(FFFFFF)e(shadow)>Ural-4320-31 ZU-23-2</c>"}
					{"ural-4320_tent2"					"<c(FFFFFF)e(shadow)>Ural-4320<c(FFFFFF)e(shadow)></c>"}
					{"ural-4320_tornado_g"				"<c(FFFFFF)e(shadow)>9K51M Tornado-G</c>"}
					{"ural-4320_tractor"				"<c(FFFFFF)e(shadow)>Ural-44202</c>"}
					{"ural375"							"<c(FFFFFF)e(shadow)>Ural-4320 Transport truck</c>"}
					{"ural375_inf"						"<c(FFFFFF)e(shadow)>Ural-4320 Transport truck</c>"}
					{"ural375_zu"						"<c(FFFFFF)e(shadow)>Ural-4320 ZU-23-2</c>"}
					{"ural_art"							"<c(FFFFFF)e(shadow)>Ural-4320 Logistic truck</c>"}
					{"ural_art_pvo"						"<c(FFFFFF)e(shadow)>Ural-4320 Arty/SAM Logistic truck</c>"}
					{"ural_avia"						"<c(FFFFFF)e(shadow)>Ural-4320 AVN Logistic truck</c>"}
					{"ural_eng"							"<c(FFFFFF)e(shadow)>Ural-4320 Engineering truck</c>"}
					{"ural_grad"						"<c(FFFFFF)e(shadow)>9K51 Grad</c>"}
					{"ural_umz"							"<c(FFFFFF)e(shadow)>Ural-4320 UMZ Minelayer</c>"}
				{"gaz66_zu"								"<c(FFFFFF)e(shadow)>GАZ-66 ZU-23-2</c>"}
				{"kamaz"								"<c(FFFFFF)e(shadow)>KamАZ-43114 Transport truck</c>"}
				{"kamaz-4326"							"<c(FFFFFF)e(shadow)>KamАZ-4326 Transport truck</c>"}
				{"kamaz-6350"							"<c(FFFFFF)e(shadow)>KamАZ-6350 Transport truck</c>"}
				{"kamaz-r142nm"							"<c(FFFFFF)e(shadow)>R-142NM Deimos</c>"}
				{"kamaz_taifun"							"<c(FFFFFF)e(shadow)>KamAZ-63968 Typhoon-K</c>"}
				{"kornet-d"								"<c(FFFFFF)e(shadow)>Kornet-D</c>"}
				{"kraz255b1_pmp"						"<c(FFFFFF)e(shadow)>KrAZ-255B1 PMP</c>"}
				{"maz7410"								"<c(FFFFFF)e(shadow)>MАZ-7410</c>"}
				{"maz7410_pricep"						"<c(FFFFFF)e(shadow)>ChMZАP-5247G</c>"}
				{"uaz2"									"<c(FFFFFF)e(shadow)>UАZ-469 PKM GPMG</c>"}
			;usa
				;hemtt
					{"hemtt_refueller"					"<c(FFFFFF)e(shadow)>HEMTT M978A4 Tanker</c>"}
					{"hemtt_tent"						"<c(FFFFFF)e(shadow)>HEMTT M977A4</c>"}
				;hmmwv_m998_tent
					{"hmmwv_m998"						"<c(FFFFFF)e(shadow)>HMMWV M998</c>"}
					{"hmmwv_m998_tent"					"<c(FFFFFF)e(shadow)>HMMWV M998</c>"}
				;hmmwv_turret
					{"hmmwv_for_single"					"<c(FFFFFF)e(shadow)>HMMWV M240B MMG</c>"}
					{"hmmwv_for_single_turret"			"<c(FFFFFF)e(shadow)>HMMWV M240B MMG turret</c>"}
					{"hmmwv_turret"						"<c(FFFFFF)e(shadow)>HMMWV M2HB HMG</c>"}
				;m939
					{"m939"								"<c(FFFFFF)e(shadow)>M939 Cargo truck</c>"}
					{"m939_inf"							"<c(FFFFFF)e(shadow)>M939 Transport truck</c>"}
				;m939_art
					{"m939_art"							"<c(FFFFFF)e(shadow)>M939 Logistic truck</c>"}
					{"m939_art_pvo"						"<c(FFFFFF)e(shadow)>M939 Arty/SAM Logistic truck</c>"}
					{"m939_avia"						"<c(FFFFFF)e(shadow)>M939 AVN Logistic truck</c>"}
				;oshkosh_m-atv
					{"oshkosh_m-atv_m2"					"<c(FFFFFF)e(shadow)>Oshkosh M-ATV SF M2HB HMG</c>"}
					{"oshkosh_m-atv_m240"				"<c(FFFFFF)e(shadow)>Oshkosh M-ATV SF M240 MMG</c>"}
					{"oshkosh_m-atv_mk19"				"<c(FFFFFF)e(shadow)>Oshkosh M-ATV SF Mk 19 AGL</c>"}
				{"Hmmwv"								"<c(FFFFFF)e(shadow)>HMMWV M2HB HMG</c>"}
				{"hmmwv_m1035"							"<c(FFFFFF)e(shadow)>HMMWV M1035</c>"}
				{"Hmmwv_TOW"							"<c(FFFFFF)e(shadow)>Hummer M966 TOW</c>"}
				{"m939_eng"								"<c(FFFFFF)e(shadow)>M939 Engineering truck</c>"}
				{"m1097_avenger"						"<c(FFFFFF)e(shadow)>M1097 Avenger</c>"}
				{"mtvr_m2"								"<c(FFFFFF)e(shadow)>Oshkosh MTVR Mk27</c>"}
				{"oshkosh_m-atv"						"<c(FFFFFF)e(shadow)>Oshkosh M-ATV</c>"}
				{"oshkosh_mtvr_ammo_mk25"				"<c(FFFFFF)e(shadow)>Oshkosh MTVR MK25</c>"}
				{"oshkosh_mtvr_cargo_mk25"				"<c(FFFFFF)e(shadow)>Oshkosh MTVR MK25</c>"}
				{"oshkosh_mtvr_tanker_mk25"				"<c(FFFFFF)e(shadow)>Oshkosh MTVR MK25 CST</c>"}
				{"patriot_truck"						"<c(FFFFFF)e(shadow)>MAN KAT1 Truck</c>"}
		;car_other
			;uaz_car
				{"UAZ_car"								"<c(FFFFFF)e(shadow)>UАZ-469</c>"}
				{"UAZ_car_konkurs"						"<c(FFFFFF)e(shadow)>UАZ-469</c>"}
			{"chevrolet_bel_air"						"<c(FFFFFF)e(shadow)>Chevrolet Bel Air</c>"}
			{"chevy_s10"								"<c(FFFFFF)e(shadow)>Chevrolet C10</c>"}
			{"dodje"									"<c(FFFFFF)e(shadow)>Dodge Charger 2010</c>"}
			{"dodje_police"								"<c(FFFFFF)e(shadow)>Dodge Charger 2010</c>"}
			{"fire_department"							"<c(FFFFFF)e(shadow)>2011 Pierce Impel</c>"}
			{"ford_f150"								"<c(FFFFFF)e(shadow)>Ford F-350 2008"}
			{"furgon"									"<c(FFFFFF)e(shadow)>GMC Dura 1995"}
			{"furgon_swat"								"<c(FFFFFF)e(shadow)>GMC Dura 1995"}
			{"gaz_24"									"<c(FFFFFF)e(shadow)>GАZ-24</c>"}
			{"motorcycle"								"<c(FFFFFF)e(shadow)>Honda XLX 250"}
			{"mtz_80"									"<c(FFFFFF)e(shadow)>MTZ-80</c>"}
			{"prado"									"<c(FFFFFF)e(shadow)>Toyota Land Cruiser Prado 150</c>"}																			
			{"toyota_hilux"								"<c(FFFFFF)e(shadow)>Toyota Hilux PKM GPMG</c>"}
			{"toyota_hilux_ammo"						"<c(FFFFFF)e(shadow)>Toyota Hilux Ammunition</c>"}
			{"toyota_hilux_dshkm"						"<c(FFFFFF)e(shadow)>Toyota Hilux DShKM HMG</c>"}
			{"toyota_hilux_spg9"						"<c(FFFFFF)e(shadow)>Toyota Hilux SPG-9 RR</c>"}
			{"toyota_hilux_transport"					"<c(FFFFFF)e(shadow)>Toyota Hilux</c>"}
			{"tractor_fiat25"							"<c(FFFFFF)e(shadow)>FIAT 25</c>"}
			{"uaz_van"									"<c(FFFFFF)e(shadow)>UАZ-452</c>"}
			{"vaz_2106"									"<c(FFFFFF)e(shadow)>VАZ-2106</c>"}
			{"volkswagen_beetle"						"<c(FFFFFF)e(shadow)>VW Beetle</c>"}
		;marine_modern
			;rus
				;bpk1155
					{"bpk1155_harlamov"					"<c(FFFFFF)e(shadow)>Admiral Kharlamov - 678</c>"}
					{"bpk1155_levchenko"				"<c(FFFFFF)e(shadow)>Admiral Levchenko - 605</c>"}
					{"bpk1155_panteleev"				"<c(FFFFFF)e(shadow)>Admiral Panteleyev - 548</c>"}
					{"bpk1155_severomorsk"				"<c(FFFFFF)e(shadow)>Severomorsk - 619</c>"}
					{"bpk1155_tribuc"					"<c(FFFFFF)e(shadow)>Admiral Tributs - 564</c>"}
					{"bpk1155_vinogradov"				"<c(FFFFFF)e(shadow)>Admiral Vinogradov - 572</c>"}
				;linked_entities
					;ak630
						{"ak630"						"<c(FFFFFF)e(shadow)>АK-630</c>"}
						{"ak630_side"					"<c(FFFFFF)e(shadow)>АK-630</c>"}
					;torpedotube_rus_x2
						{"torpedotube_rus_x2_left"		"<c(FFFFFF)e(shadow)>533mm torpedo tubes</c>"}
						{"torpedotube_rus_x2_right"		"<c(FFFFFF)e(shadow)>533mm torpedo tubes</c>"}
					;torpedotube_rus_x4
						{"torpedotube_rus_x4_left"		"<c(FFFFFF)e(shadow)>533mm torpedo tubes</c>"}
						{"torpedotube_rus_x4_right"		"<c(FFFFFF)e(shadow)>533mm torpedo tubes</c>"}
					;torpedotube_rus_x5
						{"torpedotube_rus_x5_left"		"<c(FFFFFF)e(shadow)>533mm torpedo tubes</c>"}
						{"torpedotube_rus_x5_right"		"<c(FFFFFF)e(shadow)>533mm torpedo tubes</c>"}
					{"a22_ogon"							"<c(FFFFFF)e(shadow)>A-22 Ogon</c>"}
					{"ak100_maingun"					"<c(FFFFFF)e(shadow)>АK-100</c>"}
					{"ak130_maingun"					"<c(FFFFFF)e(shadow)>АK-130</c>"}
					{"ak176"							"<c(FFFFFF)e(shadow)>AK-176</c>"}
					{"ak630_rls"						"<c(FFFFFF)e(shadow)>MR-123/176 Vympel</c>"}
					{"ak630_rls_1"						"<c(FFFFFF)e(shadow)>MR-123-02/MR-123-03 Vympel-AM</c>"}
					{"basalt_pu"						"<c(FFFFFF)e(shadow)>P-500 Bazalt</c>"}
					{"flag_rls"							"<c(FFFFFF)e(shadow)>MR-800 Flag</c>"}
					{"fort_m_rls"						"<c(FFFFFF)e(shadow)>30N6E2</c>"}
					{"fort_rls"							"<c(FFFFFF)e(shadow)>Volna 3R41</c>"}
					{"fregat710"						"<c(FFFFFF)e(shadow)>MR-710M Fregat</c>"}
					{"fregat710m1"						"<c(FFFFFF)e(shadow)>MR-710M1 Fregat</c>"}
					{"fregat750"						"<c(FFFFFF)e(shadow)>MR-750 Fregat-MA</c>"}
					{"granit1144_pu"					"<c(FFFFFF)e(shadow)>P-700 Granit</c>"}
					{"kinjal_1144"						"<c(FFFFFF)e(shadow)>3K95 Kinzhal</c>"}
					{"kinjal_1155back"					"<c(FFFFFF)e(shadow)>3K95 Kinzhal</c>"}
					{"kinjal_1155front"					"<c(FFFFFF)e(shadow)>3K95 Kinzhal</c>"}
					{"kinjal_rls"						"<c(FFFFFF)e(shadow)>MR-360</c>"}
					{"kortik"							"<c(FFFFFF)e(shadow)>Kortik Kashtan-M</c>"}
					{"lev_rls"							"<c(FFFFFF)e(shadow)>MR-184 Lev</c>"}
					{"malahit_pu"						"<c(FFFFFF)e(shadow)>P-120 Malakhit</c>"}
					{"moskit_pu"						"<c(FFFFFF)e(shadow)>P-270 Moskit</c>"}
					{"osa_ma_pu"						"<c(FFFFFF)e(shadow)>ZIF-122</c>"}
					{"osa_am_rls"						"<c(FFFFFF)e(shadow)>M-4 Osa-MA</c>"}
					{"podberezovik_rls"					"<c(FFFFFF)e(shadow)>Podberezovik-EТ1</c>"}
					{"podkat_rls"						"<c(FFFFFF)e(shadow)>MR-350 Podkat</c>"}
					{"rastrub_pu"						"<c(FFFFFF)e(shadow)>URPK-5 Rastrub-B</c>"}
					{"rbu1000"							"<c(FFFFFF)e(shadow)>RBU-1000 Smerch-3</c>"}
					{"rbu12000"							"<c(FFFFFF)e(shadow)>RBU-12000 Udav-1</c>"}
					{"rbu6000"							"<c(FFFFFF)e(shadow)>RBU-6000 Smerch-2</c>"}
					{"s300f_1144"						"<c(FFFFFF)e(shadow)>97.2FE</c>"}
					{"s300f_1164"						"<c(FFFFFF)e(shadow)>3S-48E</c>"}
					{"uragan_pu"						"<c(FFFFFF)e(shadow)>3S90 Uragan</c>"}
					{"uragan_rls"						"<c(FFFFFF)e(shadow)>3R90/MR-90 Orekh</c>"}
				;orlan
					{"orlan_body1"						"<c(FFFFFF)e(shadow)>Pyotr Velikiy (099) - Project 1144 Orlan</c>"}
					{"orlan_body2"						"<c(FFFFFF)e(shadow)>Pyotr Velikiy (099) - Project 1144 Orlan</c>"}
					{"orlan_body3"						"<c(FFFFFF)e(shadow)>Pyotr Velikiy (099) - Project 1144 Orlan</c>"}
					{"orlan_body4"						"<c(FFFFFF)e(shadow)>Pyotr Velikiy (099) - Project 1144 Orlan</c>"}
					{"orlan_main"						"<c(FFFFFF)e(shadow)>Pyotr Velikiy (099) - Project 1144 Orlan</c>"}
				;pr1164
					{"pr1164_moskva"					"<c(FFFFFF)e(shadow)>Moskva (121) - Project 1164 Atlant</c>"}
					{"pr1164_ustinov"					"<c(FFFFFF)e(shadow)>Marshal Ustinov (055) - Project 1164 Atlant</c>"}
					{"pr1164_varyag"					"<c(FFFFFF)e(shadow)>Varyag (011) - Project 1164 Atlant</c>"}
				;pr1234_ovod
					{"pr1234_ovod"						"<c(FFFFFF)e(shadow)>Project 1234.1 Ovod</c>"}
				;zubr
					{"zubr"								"<c(FFFFFF)e(shadow)>Project 1232.2</c>"}
				{"636_3varshavyanka"					"<c(FFFFFF)e(shadow)>Project 636 Varshavyanka</c>"}
				{"boat338m"								"<c(FFFFFF)e(shadow)>Project 338M</c>"}
				{"boat1390"								"<c(FFFFFF)e(shadow)>Project 1390</c>"}
				{"boat1402"								"<c(FFFFFF)e(shadow)>Project 1402</c>"}
				{"boat1404"								"<c(FFFFFF)e(shadow)>Project 1404</c>"}
				{"pr949a"								"<c(FFFFFF)e(shadow)>Project 949A Antey</c>"}
				{"pr956"								"<c(FFFFFF)e(shadow)>Project 956 Sarych</c>"}
			;usa
				;arly_burke
					;arly_burke
						{"arley_burke"					"<c(FFFFFF)e(shadow)>Arleigh Burke</c>"}
						{"arley_burke_a2"				"<c(FFFFFF)e(shadow)>Arleigh Burke</c>"}
						{"arley_burke_laser"			"<c(FFFFFF)e(shadow)>Arleigh Burke</c>"}
						{"arley_burke_with_land"		"<c(FFFFFF)e(shadow)>Arleigh Burke</c>"}
					;weaponry
						{"laws"							"<c(FFFFFF)e(shadow)>AN/SEQ-3 LaWS</c>"}
						{"mk32_left"					"<c(FFFFFF)e(shadow)>Mark 32</c>"}
						{"mk32_right"					"<c(FFFFFF)e(shadow)>Mark 32</c>"}
						{"mk38_mod2"					"<c(FFFFFF)e(shadow)>Mk 38 Mod 2</c>"}
						{"mk41_32"						"<c(FFFFFF)e(shadow)>Mk41 VLS</c>"}
						{"mk41_64"						"<c(FFFFFF)e(shadow)>Mk41 VLS</c>"}
						{"mk45"							"<c(FFFFFF)e(shadow)>5-inch/62 caliber Mark 45 Mod 4 lightweight gun</c>"}
						{"naval_browning"				"<c(FFFFFF)e(shadow)>Twin M2HB</c>"}
						{"spg62_radar"					"<c(FFFFFF)e(shadow)>AN/SPG-62 CW radar</c>"}
				;linked_entities
					{"carrier_cst"						"<c(FFFFFF)e(shadow)>A/S-32-31A Mule</c>"}
					{"carrier_lifter"					"<c(FFFFFF)e(shadow)>HYSTER 3.0</c>"}
				;nimitz
					;nimitz_body3
						{"nimitz_body3"					"<c(FFFFFF)e(shadow)>Nimitz-class aircraft carrier</c>"}
						{"nimitz_body3_cvn68"			"<c(FFFFFF)e(shadow)>USS Nimitz (CVN-68)</c>"}
						{"nimitz_body3_cvn69"			"<c(FFFFFF)e(shadow)>USS Dwight D. Eisenhower (CVN-69)</c>"}
						{"nimitz_body3_cvn73"			"<c(FFFFFF)e(shadow)>USS George Washington (CVN-73)</c>"}
						{"nimitz_body3_cvn75"			"<c(FFFFFF)e(shadow)>USS Harry S. Truman (CVN-75)</c>"}
					;nimitz_body4
						{"nimitz_body4"					"<c(FFFFFF)e(shadow)>Nimitz-class aircraft carrier</c>"}
						{"nimitz_body4_cvn68"			"<c(FFFFFF)e(shadow)>USS Nimitz (CVN-68)</c>"}
						{"nimitz_body4_cvn69"			"<c(FFFFFF)e(shadow)>USS Dwight D. Eisenhower (CVN-69)</c>"}
						{"nimitz_body4_cvn73"			"<c(FFFFFF)e(shadow)>USS George Washington (CVN-73)</c>"}
						{"nimitz_body4_cvn75"			"<c(FFFFFF)e(shadow)>USS Harry S. Truman (CVN-75)</c>"}
					;nimitz_main
						{"nimitz_main"					"<c(FFFFFF)e(shadow)>Nimitz-class aircraft carrier</c>"}
						{"nimitz_main_cvn68"			"<c(FFFFFF)e(shadow)>USS Nimitz (CVN-68)</c>"}
						{"nimitz_main_cvn69"			"<c(FFFFFF)e(shadow)>USS Dwight D. Eisenhower (CVN-69)</c>"}
						{"nimitz_main_cvn73"			"<c(FFFFFF)e(shadow)>USS George Washington (CVN-73)</c>"}
						{"nimitz_main_cvn75"			"<c(FFFFFF)e(shadow)>USS Harry S. Truman (CVN-75)</c>"}
					{"nimitz_body"						"<c(FFFFFF)e(shadow)>Nimitz-class aircraft carrier</c>"}
					{"nimitz_body1"						"<c(FFFFFF)e(shadow)>Nimitz-class aircraft carrier</c>"}
					;weaponry
						{"mk95_radar"					"<c(FFFFFF)e(shadow)>Mk95 CW radar</c>"}
						{"phalanx"						"<c(FFFFFF)e(shadow)>Mk15 Phalanx CIWS</c>"}
						{"sea_sparrow"					"<c(FFFFFF)e(shadow)>RIM-7 Sea Sparrow</c>"}
						{"searam"						"<c(FFFFFF)e(shadow)>SeaRAM</c>"}
				{"boat_rhib"							"<c(FFFFFF)e(shadow)>11M</c>"}
				{"lcac"									"<c(FFFFFF)e(shadow)>LCAC</c>"}
				{"los_angeles"							"<c(FFFFFF)e(shadow)>USS Los Angeles (SSN-688)</c>"}
		;missile_modern
			;aim-9l
				{"aim-9l"								"<c(FFFFFF)e(shadow)>AIM-9L Sidewinder</c>"}
				{"aim-9l_ammo"							"<c(FFFFFF)e(shadow)>AIM-9L Sidewinder</c>"}
				{"aim-9l_impactor"						"<c(FFFFFF)e(shadow)>AIM-9L Sidewinder</c>"}
			;service_stuff
				{"rus_las_designator"					"<c(FFFFFF)e(shadow)>1D26 Atoll</c>"}
			{"48n6e2"									"<c(FFFFFF)e(shadow)>48N6E2</c>"}
			{"maverick"									"<c(FFFFFF)e(shadow)>AGM-65 Maverick</c>"}
			{"x-25ml"									"<c(FFFFFF)e(shadow)>Kh-25ML</c>"}
		;proj_2
			;atgm_carrier
				{"mmp_missile_carrier"					"<c(FFFFFF)e(shadow)>MMP</c>"}
				{"red_arrow_10b_carrier"				"<c(FFFFFF)e(shadow)>HJ-10</c>"}
				{"Spike-er2_carrier"					"<c(FFFFFF)e(shadow)>Spike ER2</c>"}
				{"spike-er_carrier"						"<c(FFFFFF)e(shadow)>Spike ER</c>"}
				{"spike-lr_carrier"						"<c(FFFFFF)e(shadow)>Spike LR</c>"}
				{"spike_nlos_carrier"					"<c(FFFFFF)e(shadow)>Spike NLOS - HEAT</c>"}
				{"spike_nlos_fg_carrier"				"<c(FFFFFF)e(shadow)>Spike NLOS - Blast Frag</c>"}
				{"switchblade300_carrier"				"<c(FFFFFF)e(shadow)>Switchblade 300</c>"}
				{"shahed136_base_carrier"				"<c(FFFFFF)e(shadow)>Shahed-136</c>"}
			;sam_carrier
				{"x59m_carrier"							"<c(FFFFFF)e(shadow)>Kh-59M</c>"}
		;tank_modern
			;cn
				{"ztz-96a"								"<c(FFFFFF)e(shadow)>ZTZ-96</c>"}
				{"ztz-99a"								"<c(FFFFFF)e(shadow)>ZTZ-99A</c>"}
				{"ztz_99_phase_2"						"<c(FFFFFF)e(shadow)>ZTZ-99 Phase-II</c>"}
			;fr
				;lecrerc
					{"leclerc"							"<c(FFFFFF)e(shadow)>Leclerc</c>"}
					{"leclerc_azur"						"<c(FFFFFF)e(shadow)>Leclerc Renove XLR</c>"}
			;gb
				;challenger_2
					{"challenger_2"						"<c(FFFFFF)e(shadow)>Challenger 2</c>"}
					{"challenger_2_applique"			"<c(FFFFFF)e(shadow)>Challenger 2 TES Megatron</c>"}
			;gr
				;leopard_1a4_c1
					{"leopard_1a4"						"<c(FFFFFF)e(shadow)>Leopard 1A4</c>"}
					{"leopard_1a5"						"<c(FFFFFF)e(shadow)>Leopard 1A5</c>"}
					{"leopard_c1"						"<c(FFFFFF)e(shadow)>Leopard C1</c>"}
				;leopard_2a0_2a4
					{"leopard_2a0"						"<c(FFFFFF)e(shadow)>Leopard 2</c>"}
					{"leopard_2a4"						"<c(FFFFFF)e(shadow)>Leopard 2A4</c>"}
				;leopard_2a5_2a6
					{"leopard_2a5"						"<c(FFFFFF)e(shadow)>Leopard 2A5</c>"}
					{"leopard_2a6"						"<c(FFFFFF)e(shadow)>Leopard 2A6M</c>"}
				;leopard_2a7plus
					{"leopard_2a7plus"					"<c(FFFFFF)e(shadow)>Leopard 2A7+</c>"}
					{"leopard_2a7plus_gmg"				"<c(FFFFFF)e(shadow)>Leopard 2A7+</c>"}
				{"gepard"								"<c(FFFFFF)e(shadow)>Flakpanzer Gepard</c>"}
			;idf
				;merkava_mk4
					{"merkava_mk4"						"<c(FFFFFF)e(shadow)>Merkava Mk4</c>"}
					{"merkava_trophy"					"<c(FFFFFF)e(shadow)>Merkava Mk4M Windbreaker</c>"}	
				{"magach7"								"<c(FFFFFF)e(shadow)>Magach 7C</c>"}
				{"namer"								"<c(FFFFFF)e(shadow)>Namer</c>"}
			;nato
				{"pt-91"								"<c(FFFFFF)e(shadow)>PT-91 Twardy</c>"}
				{"t72m4cz"								"<c(FFFFFF)e(shadow)>T-72M4CZ</c>"}
		;tank_modern
			;rus
				;buk_m1
					{"buk_m1"							"<c(FFFFFF)e(shadow)>9K37M1-2 Buk-M1-2</c>"}
					{"buk_m2"							"<c(FFFFFF)e(shadow)>9K317 Buk-M2</c>"}
				;pak_t72_new
					;t72(era_k5)_all
						{"t72b3"						"<c(FFFFFF)e(shadow)>T-72B3 Mod.2011</c>"}
						{"t72b3_single"					"<c(FFFFFF)e(shadow)>T-72B3 Mod.2011</c>"}
						{"t72b_1989year"				"<c(FFFFFF)e(shadow)>T-72B Mod.1989</c>"}
						{"t72ba"						"<c(FFFFFF)e(shadow)>T-72BА Mod.2003</c>"}
					;t72a_all
						{"t72_yral"						"<c(FFFFFF)e(shadow)>T-72 Mod.1973</c>"}
						{"t72a"							"<c(FFFFFF)e(shadow)>T-72A Mod.1982</c>"}
						{"t72m1"						"<c(FFFFFF)e(shadow)>T-72M1 Mod.1982</c>"}
						{"t72m_siriya"					"<c(FFFFFF)e(shadow)>T-72M Mod.1980</c>"}
					;t72b3_2017
						{"t72b3_2017"					"<c(FFFFFF)e(shadow)>T-72B3 Mod.2016</c>"}
						{"t72b3_2017_2"					"<c(FFFFFF)e(shadow)>T-72B3 Mod.2016</c>"}
					;t72b_all
						{"t72a_1984year"				"<c(FFFFFF)e(shadow)>T-72A Mod.1984</c>"}
						{"t72b"							"<c(FFFFFF)e(shadow)>T-72B Mod.1985</c>"}
						{"t72b1"						"<c(FFFFFF)e(shadow)>T-72B1 Mod.1985</c>"}
						{"t72b_single"					"<c(FFFFFF)e(shadow)>T-72B Mod.1985</c>"}
					{"t72av"							"<c(FFFFFF)e(shadow)>T-72AV Mod.1985</c>"}
					{"t72b3_gorod_komplect"				"<c(FFFFFF)e(shadow)>T-72B3 Gorod</c>"}
				;pak_t80
					;t80b_all
						{"t80b"							"<c(FFFFFF)e(shadow)>T-80B Mod.1982</c>"}
						{"t80b_2"						"<c(FFFFFF)e(shadow)>T-80B Mod.1984</c>"}
						{"t80bv"						"<c(FFFFFF)e(shadow)>T-80BV Mod.1984</c>"}
						{"t80bv_2"						"<c(FFFFFF)e(shadow)>T-80BV Mod.1985</c>"}
						{"t80bvm"						"<c(FFFFFF)e(shadow)>T-80BVM</c>"}
						{"t80bvm_2"						"<c(FFFFFF)e(shadow)>T-80BVM</c>"}
					;t80y_all
						{"t80y"							"<c(FFFFFF)e(shadow)>T-80U Mod.1986</c>"}
						{"t80y_2"						"<c(FFFFFF)e(shadow)>T-80U Mod.1990</c>"}
						{"t80ye-1"						"<c(FFFFFF)e(shadow)>T-80UE-1</c>"}
						{"t80yk"						"<c(FFFFFF)e(shadow)>T-80UK</c>"}
						{"t80ym1"						"<c(FFFFFF)e(shadow)>T-80UM1 Bars</c>"}
				;shilka
					{"Shilka"							"<c(FFFFFF)e(shadow)>ZSU-23-4M3 Shilka M3</c>"}
					{"Shilka_nato"						"<c(FFFFFF)e(shadow)>ZSU-23-4</c>"}
				;t15
					{"t-15"								"<c(FFFFFF)e(shadow)>T-15 Barbaris</c>"}
					{"t-15_au220"						"<c(FFFFFF)e(shadow)>T-15 АU-220M</c>"}
				;t62_cw
					{"t62_cw"							"<c(FFFFFF)e(shadow)>T-62 Mod.1972</c>"}
					{"t62m"								"<c(FFFFFF)e(shadow)>T-62M Mod.1983</c>"}
					{"t62m_v2"							"<c(FFFFFF)e(shadow)>T-62M Mod.1983</c>"}
					{"t62md"							"<c(FFFFFF)e(shadow)>T-62MD</c>"}
				;t90sm
					{"t90sm"							"<c(FFFFFF)e(shadow)>T-90SM Tagil - 7.62mm PKMT</c>"}
					{"t90sm_zpy12"						"<c(FFFFFF)e(shadow)>T-90SM Tagil - 12.7mm NSVT</c>"}
				{"9s18_kupol"							"<c(FFFFFF)e(shadow)>9C18 Kupol SOC/TAR</c>"}
				{"bmpt"									"<c(FFFFFF)e(shadow)>BMPT Terminator</c>"}
				{"bmr-3"								"<c(FFFFFF)e(shadow)>BMR-3M Vepr</c>"}
				{"t-14"									"<c(FFFFFF)e(shadow)>T-14 Аrmata</c>"}
				{"t-55"									"<c(FFFFFF)e(shadow)>T-55А</c>"}
				{"t-90a"								"<c(FFFFFF)e(shadow)>T-90A Vladimir</c>"}
				{"t34-85_cw"							"<c(FFFFFF)e(shadow)>T-34-85</c>"}
				{"t64"									"<c(FFFFFF)e(shadow)>T-64А Mod.1971</c>"}
				{"tunguska"								"<c(FFFFFF)e(shadow)>2S6 Tunguska</c>"}
			;ukr
				{"bm_oplot"								"<c(FFFFFF)e(shadow)>BM Oplot</c>"}
				{"t-64b"								"<c(FFFFFF)e(shadow)>T-64B Sosna Mod.1980</c>"}
				{"t-64bv"								"<c(FFFFFF)e(shadow)>T-64BV Skif</c>"}
				{"t-64bm1"								"<c(FFFFFF)e(shadow)>T-64BM1 Bulat</c>"}
				{"t-64bm2"								"<c(FFFFFF)e(shadow)>T-64BM2 Bulat</c>"}
			;usa
				;m1a1_all_model
					{"m1a1_FEP"							"<c(FFFFFF)e(shadow)>M1A1 FEP</c>"}
					{"m1a1_new"							"<c(FFFFFF)e(shadow)>M1A1HA</c>"}
					{"m1a2_sep"							"<c(FFFFFF)e(shadow)>M1A2 SEPv2</c>"}
					{"m1a2sep3"							"<c(FFFFFF)e(shadow)>M1A2 SEPv3</c>"}
					{"m1ip_1"							"<c(FFFFFF)e(shadow)>M1IP</c>"}
					{"m1ip_2"							"<c(FFFFFF)e(shadow)>M1IP</c>"}
				;m1a1tusk_2_new
					{"m1a2tusk_2_new"					"<c(FFFFFF)e(shadow)>M1A2A TUSK II</c>"}
					{"m1a2tusk_2_m2_new"				"<c(FFFFFF)e(shadow)>M1A2A TUSK</c>"}
				{"M1_Abrams"							"<c(FFFFFF)e(shadow)>M1 Abrams</c>"}
				{"m1a2tusk"								"<c(FFFFFF)e(shadow)>M1A2A TUSK</c>"}
				{"m60a3"								"<c(FFFFFF)e(shadow)>M60A3</c>"}
		;train_modern
			{"2te10"									"<c(FFFFFF)e(shadow)>2TE10</c>"}
			{"locomote_tgmz_1010"						"<c(FFFFFF)e(shadow)>TGM3 1010</c>"}
	;cannon
		{"browning_m2hb_stan"							"<c(FFFFFF)e(shadow)>Browning M2HB</c>"}
		{"kpvt"											"<c(FFFFFF)e(shadow)>KPVT</c>"}
;new_entities
	;-supply_crates
		;for_mp
			{"supply_nato_pvo_aviation"					"<c(FFFFFF)e(shadow)>AVN Ammunition</c>"}
			{"supply_rus_art_eng"						"<c(FFFFFF)e(shadow)>Fuel & Arty/SAM Ammunition</c>"}
			{"supply_rus_bmp_btr_tanks"					"<c(FFFFFF)e(shadow)>Mechanized Ammunition</c>"}
			{"supply_rus_light_weap"					"<c(FFFFFF)e(shadow)>Ammunition</c>"}
			{"supply_rus_pvo_aviation"					"<c(FFFFFF)e(shadow)>AVN Ammunition</c>"}
			{"supply_usa_art_eng"						"<c(FFFFFF)e(shadow)>Arty/SAM Ammunition</c>"}
			{"supply_usa_bmp_btr_tanks"					"<c(FFFFFF)e(shadow)>Mechanized Ammunition</c>"}
			{"supply_usa_light_weap"					"<c(FFFFFF)e(shadow)>Ammunition</c>"}
			{"supply_usa_pvo_aviation"					"<c(FFFFFF)e(shadow)>AVN Ammunition</c>"}
;service
	;for_mp
		;mp_flag
			{"abn_mp_flag"								"<c(FFFFFF)e(shadow)>NATO Field Artillery</c>"}
			{"armbr_mp_flag"							"<c(FFFFFF)e(shadow)>SVR Tank Brigade</c>"}
			{"artbr_mp_flag"							"<c(FFFFFF)e(shadow)>SVR Artillery Brigade</c>"}
			{"bund_mp_flag"								"<c(FFFFFF)e(shadow)>Bundeswehr</c>"}
			{"cbn_mp_flag"								"<c(FFFFFF)e(shadow)>Combined Joint Expeditionary Force</c>"}
			{"chi_dummy_flag"							"<c(FFFFFF)e(shadow)>People's Republic of China</c>"}
			{"cnair_mp_flag"							"<c(FFFFFF)e(shadow)>PLA Air Force (PLAAF)</c>"}
			{"cnart_mp_flag"							"<c(FFFFFF)e(shadow)>PLA Artillery & Rocket Forces</c>"}
			{"cnheavy_mp_flag"							"<c(FFFFFF)e(shadow)>PLA Heavy Combined Arms Brigade</c>"}
			{"cnmed_mp_flag"							"<c(FFFFFF)e(shadow)>PLA Medium Combined Arms Brigade</c>"}
			{"cnsam_mp_flag"							"<c(FFFFFF)e(shadow)>PLA Air Defence Force</c>"}
			{"cnsco_mp_flag"							"<c(FFFFFF)e(shadow)>SCO Joint Task Force</c>"}
			{"fra_mp_flag"								"<c(FFFFFF)e(shadow)>Forces Armées Françaises</c>"}
			{"gb_mp_flag"								"<c(FFFFFF)e(shadow)>Her Majesty's Armed Forces</c>"}
			{"idf_mp_flag"								"<c(FFFFFF)e(shadow)>Tzahal (IDF)</c>"}
			{"mot_mp_flag"								"<c(FFFFFF)e(shadow)>SVR Motorized Rifle Brigade</c>"}
			{"nato_aa_mp_flag"							"<c(FFFFFF)e(shadow)>NATO Integrated Air and Missile Defence</c>"}
			{"nato_dummy_flag"							"<c(FFFFFF)e(shadow)>NATO</c>"}
			{"nrf_mp_flag"								"<c(FFFFFF)e(shadow)>NATO Allied Air Command</c>"}
			{"pvo_mp_flag"								"<c(FFFFFF)e(shadow)>Troops of National Air Defense (PVO)</c>"}
			{"rus_dummy_flag"							"<c(FFFFFF)e(shadow)>Russian Federation</c>"}
			{"specbr_mp_flag"							"<c(FFFFFF)e(shadow)>BV Naval Infantry Brigade</c>"}
			{"usa_aa_mp_flag"							"<c(FFFFFF)e(shadow)>U.S. Aerospace Defense Command</c>"}
			{"usa_dummy_flag"							"<c(FFFFFF)e(shadow)>U.S.</c>"}
			{"usaf_mp_flag"								"<c(FFFFFF)e(shadow)>U.S. Air Force (USAF)</c>"}
			{"usarmy_mp_flag"							"<c(FFFFFF)e(shadow)>U.S. Army</c>"}
			{"usart_mp_flag"							"<c(FFFFFF)e(shadow)>U.S. Army Field Artillery Branch</c>"}
			{"usmc_mp_flag"								"<c(FFFFFF)e(shadow)>U.S. Marine Corps (USMC)</c>"}
			{"vdv_mp_flag"								"<c(FFFFFF)e(shadow)>RU Airborne Forces (VDV)</c>"}
			{"vvs_mp_flag"								"<c(FFFFFF)e(shadow)>RU Air Force (VVS)</c>"}
		;persistent_marker
			{"persistent_marker_cn"						"<c(FFFFFF)e(shadow)>Target location</c>"}
			{"persistent_marker_nato"					"<c(FFFFFF)e(shadow)>Target location</c>"}
			{"persistent_marker_rus"					"<c(FFFFFF)e(shadow)>Target location</c>"}
			{"persistent_marker_usa"					"<c(FFFFFF)e(shadow)>Target location</c>"}
;vehicle+infantry
	;cn
		{"pzrk2_cn"										"<c(FFFFFF)e(shadow)><e(shadow)>Mechanized MANPADS team</c>"}
	;nato
		{"pzrk2_nato"									"<c(FFFFFF)e(shadow)><e(shadow)>Mechanized MANPADS team</c>"}
	;rus
		{"pzrk2_rus"									"<c(FFFFFF)e(shadow)><e(shadow)>Mechanized MANPADS team</c>"}
	;usa
		{"pzrk2_usa"									"<c(FFFFFF)e(shadow)><e(shadow)>Mechanized MANPADS team</c>"}
;AS2
	;faunua
		{"chiken"										"<c(FFFFFF)>Chicken</c>"}
		{"cow"											"<c(FFFFFF)>Cow</c>"}
		{"horse"										"<c(FFFFFF)>Horse</c>"}
		{"horse_bones"									"<c(FFFFFF)>Horse</c>"}
;CTA
	;cta_entities
		;fanua
			{"carp"										"<c(FFFFFF)>Carp</c>"}
			{"crab"										"<c(FFFFFF)>Crab</c>"}
			{"dog"										"<c(FFFFFF)>Dog</c>"}
			{"fish"										"<c(FFFFFF)>Fish</c>"}
			{"goat"										"<c(FFFFFF)>Goat</c>"}
			{"hawk"										"<c(FFFFFF)>Hawk</c>"}
			{"pig"										"<c(FFFFFF)>Pig</c>"}
			{"raven"									"<c(FFFFFF)>Raven"}
			{"seagull"									"<c(FFFFFF)>Seagull</c>"}
			{"shark"									"<c(FFFFFF)>Shark</c>"}
			{"sheep"									"<c(FFFFFF)>Sheep</c>"}
			{"swan"										"<c(FFFFFF)>Swan</c>"}
		;vehicle
			;civilian
				;car
					{"car"								"<c(FFFFFF)>Civilian car</c>"}
					{"car_taxi"							"<c(FFFFFF)>Civilian taxi</c>"}
				;truck
					{"truck"							"<c(FFFFFF)>Civilian truck</c>"}
					{"truck_low_loader"					"<c(FFFFFF)>Civilian truck</c>"}
					{"truck_trailer"					"<c(FFFFFF)>Dump truck</c>"}
					{"truck_trailer_cementmixer"		"<c(FFFFFF)>Civilian truck</c>"}
					{"truck_trailer_closed"				"<c(FFFFFF)>Civilian truck</c>"}
				{"bus"									"<c(FFFFFF)>Civilian minibus</c>"}
				{"car_small"							"<c(FFFFFF)>Civilian car</c>"}
				{"train_cabin"							"<c(FFFFFF)>Passenger carriage</c>"}
				{"train_engine"							"<c(FFFFFF)>Civilian locomotive</c>"}
				{"train_fuelwagen"						"<c(FFFFFF)>Fuel tank</c>"}
				{"train_wagen"							"<c(FFFFFF)>Freight platform</c>"}
				{"train_wagen_2"						"<c(FFFFFF)>Freight platform</c>"}
				{"train_wagen_3"						"<c(FFFFFF)>Freight platform</c>"}
				{"train_wagen_container"				"<c(FFFFFF)>Cargo container</c>"}
				{"truck_small"							"<c(FFFFFF)>Civilian truck</c>"}
;unavailable
	;nato
		{"abn_hqcar"									"<c(FFFFFF)e(shadow)>Artillery brigade</c>"}
		{"cbn_hqcar"									"<c(FFFFFF)e(shadow)>Combined Joint Expeditionary Force</c>"}
		{"fra_hqcar"									"<c(FFFFFF)e(shadow)>Armee de terre</c>"}
		{"gb_hqcar"										"<c(FFFFFF)e(shadow)>Her Majesty's Armed Forces</c>"}
		{"mq9_nato"										"<c(FFFFFF)e(shadow)>RAF MQ-9 Reaper</c>"}
		{"nrf_hqcar"									"<c(FFFFFF)e(shadow)>Airforce</c>"}
		{"patriot_launcher_nato"						"<c(FFFFFF)e(shadow)>MIM-104 Patriot PU</c>"}
		{"patriot_radar_nato"							"<c(FFFFFF)e(shadow)>MIM-104 Patriot AN/MPQ-53</c>"}
		{"uh60_nato"									"<c(FFFFFF)e(shadow)>UH-60 Black Hawk</c>"}
	;rus
		{"9k57_uragan"									"<c(FFFFFF)e(shadow)>BM-27</c>"}
		{"bmp1"											"<c(FFFFFF)e(shadow)>BMP-1</c>"}
		{"bmp2"											"<c(FFFFFF)e(shadow)>BMP-2</c>"}
		{"bmp2m"										"<c(FFFFFF)e(shadow)>BMP-2 Berezhok<</c>"}
		{"mtlb_no_ammobox"								"<c(FFFFFF)e(shadow)>MT-LB</c>"}
		{"t62"											"<c(FFFFFF)e(shadow)>T-62 Mod.1972</c>"}
	;usa
		{"Humvee"										"<c(FFFFFF)e(shadow)>HUMVEE</c>"}
		{"M1A1"											"<c(FFFFFF)e(shadow)>M1A1HA</c>"}
		{"cougar"										"<c(FFFFFF)e(shadow)>Cougar 4x4</c>"}
		{"m1a1_shield_new"								"<c(FFFFFF)e(shadow)>M1A1HA</c>"}
		{"m1a2_all_model"								"<c(FFFFFF)e(shadow)>M1A2B</c>"}
		{"m1a2tusk_new"									"<c(FFFFFF)e(shadow)>M1A2A TUSK</c>"}
		{"m1ip"											"<c(FFFFFF)e(shadow)>M1IP</c>"}
		{"m2a3_btr"										"<c(FFFFFF)e(shadow)>M2A3 Bradley</c>"}
		{"m2a3_new"										"<c(FFFFFF)e(shadow)>M2A3 Bradley</c>"}
		{"mortarfru"									"<c(FFFFFF)e(shadow)>MO-120 RT61</c>"}
		{"ngrd_mp_flag"									"<c(FFFFFF)e(shadow)>National Guard of the U.S.</c>"}