;Revised by maaa - DTTGOC
;LocalGen2
;Extra data placeholder
;Extra data placeholder
;rev 04.07.2022

;-vehicle
	;-modern
		;air_modern
			;cn
				;j-10c
					{"j-10c_aa"					"<c(FFFF00)>ASF/MRCA</c>"}
					{"j-10c_ab"					"<c(FFFF00)>ASF/MRCA</c>"}
					{"j-10c_patrol"					"<c(FFFF00)>ASF/MRCA</c>"}
				;jh-7a
					{"jh-7a_antirad"					"<c(FFFF00)>MRCA</c>"}
					{"jh-7a_at"							"<c(FFFF00)>MRCA</c>"}
					{"jh-7a_bomber"						"<c(FFFF00)>MRCA</c>"}
					{"jh-7a_kab"						"<c(FFFF00)>MRCA</c>"}
					{"jh-7a_light"						"<c(FFFF00)>MRCA</c>"}
					{"jh-7a_strike"						"<c(FFFF00)>MRCA</c>"}
				{"ch802"								"<c(FFFF00)>Recon UAV</c>"}
				{"mi171_china"							"<c(FFFF00)>Utility helicopter</c>"}
				{"su-35_aa_china"						"<c(FFFF00)>ASF/MRCA</c>"}
				{"z-10_support"							"<c(FFFF00)>Attack helicopter</c>"}
			;fr
				;nh90
					{"nh90"								"<c(FFFF00)>Utility helicopter</c>"}
					{"nh90_sas"							"<c(FFFF00)>Utility helicopter</c>"}
				;tiger_hap
					{"tiger_hap_at"						"<c(FFFF00)>Attack helicopter</c>"}
					{"tiger_hap_escort"					"<c(FFFF00)>Attack helicopter</c>"}
					{"tiger_hap_support"				"<c(FFFF00)>Attack helicopter</c>"}
			;gb
				;eurofighter
					{"eurofighter_aa"					"<c(FFFF00)>MRCA</c>"}
					{"eurofighter_ab"					"<c(FFFF00)>MRCA</c>"}
					{"eurofighter_antirad"				"<c(FFFF00)>MRCA</c>"}
					{"eurofighter_strike"				"<c(FFFF00)>MRCA</c>"}
					{"eurofighter_support"				"<c(FFFF00)>MRCA</c>"}
				;tornado
					{"tornado_gr1_bomber"				"<c(FFFF00)>MRCA</c>"}
					{"tornado_gr1_carpet"				"<c(FFFF00)>MRCA</c>"}
					{"tornado_gr4_antirad"				"<c(FFFF00)>MRCA</c>"}
					{"tornado_gr4_at"					"<c(FFFF00)>MRCA</c>"}
					{"tornado_gr4_bomber1"				"<c(FFFF00)>MRCA</c>"}
					{"tornado_gr4_strike"				"<c(FFFF00)>MRCA</c>"}
					{"tornado_gr4_support"				"<c(FFFF00)>MRCA</c>"}
					{"tornado_gr4_support_light"		"<c(FFFF00)>MRCA</c>"}
				{"f-35b_stealthaa_british"				"<c(FFFF00)>Stealth MRCA</c>"}
			;ger
				{"aladin"								"<c(FFFF00)>Recon UAV</c>"}
			;ir
				{"shahed136_base"						"<c(FFFF00)>Loitering munition</c>"}
			;rus
				;an-12
					{"an-12"							"<c(FFFF00)>Tactical airlifter</c>"}
					{"an-12bk"							"<c(FFFF00)>Tactical airlifter</c>"}
				;eleron
					{"eleron3sv"						"<c(FFFF00)>Recon UAV</c>"}
					{"eleron_catapult"					"<c(FFFF00)>Pneumatic catapult</c>"}
					{"eleron_control"					"<c(FFFF00)>MCU</c>"}
				;ka52
					{"ka52"								"<c(FFFF00)>Attack helicopter</c>"}
					{"ka52_germes"						"<c(FFFF00)>Attack helicopter</c>"}
					{"ka52k"							"<c(FFFF00)>Attack helicopter</c>"}
				;mi-24v
					{"mi-24v"							"<c(FFFF00)>Attack helicopter</c>"}
					{"mi-24v_2"							"<c(FFFF00)>Attack helicopter</c>"}
				;mi17
					{"mi17"								"<c(FFFF00)>Utility helicopter</c>"}
					{"mi17_b8"							"<c(FFFF00)>Utility helicopter</c>"}
					{"mi17_china"						"<c(FFFF00)>Utility helicopter</c>"}
					{"mi17_unarmed"						"<c(FFFF00)>Utility helicopter</c>"}
				;mi8amtsh
					{"mi8amtsh"							"<c(FFFF00)>Utility helicopter</c>"}
					{"mi8amtsh1"						"<c(FFFF00)>Utility helicopter</c>"}
					{"mi8amtsh1_mgnar"					"<c(FFFF00)>Utility helicopter</c>"}
					{"mi8amtsh1_mgun"					"<c(FFFF00)>Utility helicopter</c>"}
				;mig-21bis
					{"mig-21bis_aa"						"<c(FFFF00)>Fighter-interceptor aircraft</c>"}
					{"mig-21bis_bomber"					"<c(FFFF00)>Fighter-interceptor aircraft</c>"}
					{"mig-21bis_support"				"<c(FFFF00)>Fighter-interceptor aircraft</c>"}
				;mig-29k
					{"mig-29k_aa"						"<c(FFFF00)>ASF/MRCA</c>"}
					{"mig-29k_ab"						"<c(FFFF00)>ASF/MRCA</c>"}
					{"mig-29k_antiship"					"<c(FFFF00)>ASF/MRCA</c>"}
				;mig-29s
					{"mig-29s_aa"						"<c(FFFF00)>ASF/MRCA</c>"}
					{"mig-29s_aa_vks"					"<c(FFFF00)>ASF/MRCA</c>"}
					{"mig-29s_ab"						"<c(FFFF00)>ASF/MRCA</c>"}
				;su-25sm_part1
					{"su-25sm_accurate"					"<c(FFFF00)>CAS attack aircraft</c>"}
					{"su-25sm_miner"					"<c(FFFF00)>CAS attack aircraft</c>"}
					{"su-25sm_support"					"<c(FFFF00)>CAS attack aircraft</c>"}
					{"su-25sm_support_light"			"<c(FFFF00)>CAS attack aircraft</c>"}
				;su-25sm_part2
					{"su-25sm_at"						"<c(FFFF00)>CAS attack aircraft</c>"}
					{"su-25sm_strike"					"<c(FFFF00)>CAS attack aircraft</c>"}
				;su-34
					{"su-34_accurate_2"					"<c(FFFF00)>MRCA</c>"}
					{"su-34_antiair"					"<c(FFFF00)>MRCA</c>"}
					{"su-34_antirad"					"<c(FFFF00)>MRCA</c>"}
					{"su-34_antisam"					"<c(FFFF00)>MRCA</c>"}
					{"su-34_antitank"					"<c(FFFF00)>MRCA</c>"}
					{"su-34_bomber"						"<c(FFFF00)>MRCA</c>"}
					{"su-34_medbomber"					"<c(FFFF00)>MRCA</c>"}
					{"su-34_strike"						"<c(FFFF00)>MRCA</c>"}
					{"su-34_support"					"<c(FFFF00)>MRCA</c>"}
				;su-35
					{"su-35_aa"							"<c(FFFF00)>ASF/MRCA</c>"}
					{"su-35_at"							"<c(FFFF00)>ASF/MRCA</c>"}
					{"su-35_strike"						"<c(FFFF00)>ASF/MRCA</c>"}
				;su-50
					{"su-50_aa"							"<c(FFFF00)>MRCA</c>"}
					{"su-50_ab"							"<c(FFFF00)>MRCA</c>"}
					{"su-50_at"							"<c(FFFF00)>MRCA</c>"}
				{"il-76td"								"<c(FFFF00)>Strategic and tactical airlifter</c>"}
				{"Ka50"									"<c(FFFF00)>Attack helicopter</c>"}
				{"Ka50sh"								"<c(FFFF00)>Attack helicopter</c>"}
				{"mi-24vm"								"<c(FFFF00)>Attack helicopter</c>"}
				{"mi28n"								"<c(FFFF00)>Attack helicopter</c>"}
				{"mi28ub"								"<c(FFFF00)>Training/Attack helicopter</c>"}
			;usa
				;a-10_csupport
					{"a-10c_AT"							"<c(FFFF00)>CAS attack aircraft</c>"}
					{"a-10c_support"					"<c(FFFF00)>CAS attack aircraft</c>"}
					{"a-10c_support_light"				"<c(FFFF00)>CAS attack aircraft</c>"}
				;apache
					{"apache"							"<c(FFFF00)>Attack helicopter</c>"}
					{"apache_brit"						"<c(FFFF00)>Attack helicopter</c>"}
					{"apache_spike"						"<c(FFFF00)>Attack helicopter</c>"}
				;e-2c_hawkeye
					{"e-2c_hawkeye"						"<c(FFFF00)>AWACS</c>"}
					{"e-2c_hawkeye_france"				"<c(FFFF00)>AWACS</c>"}
				;f-16c
					{"f-16c_aa"							"<c(FFFF00)>MRCA/ASF</c>"}
					{"f-16c_antirad"					"<c(FFFF00)>MRCA/ASF</c>"}
					{"f-16c_antirad_2"					"<c(FFFF00)>MRCA/ASF</c>"}
					{"f-16c_antiship"					"<c(FFFF00)>MRCA/ASF</c>"}
					{"f-16c_strike"						"<c(FFFF00)>MRCA/ASF</c>"}
					{"f-16c_support"					"<c(FFFF00)>MRCA/ASF</c>"}
					{"f-16c_support_pol"				"<c(FFFF00)>MRCA/ASF</c>"}
				;f-22
					{"f-22_antiair"						"<c(FFFF00)>Stealth ASF</c>"}
					{"f-22_fighter-bomber"				"<c(FFFF00)>Stealth ASF</c>"}
				;f-35b
					{"f-35b_aa"							"<c(FFFF00)>Stealth MRCA</c>"}
					{"f-35b_stealthaa"					"<c(FFFF00)>Stealth MRCA</c>"}
					{"f-35b_stealthab"					"<c(FFFF00)>Stealth MRCA</c>"}
					{"f-35b_strike"						"<c(FFFF00)>Stealth MRCA</c>"}
					{"f-35b_support"					"<c(FFFF00)>Stealth MRCA</c>"}
				;f-35c
					{"f-35c_aa"							"<c(FFFF00)>Stealth MRCA</c>"}
					{"f-35c_stealthaa"					"<c(FFFF00)>Stealth MRCA</c>"}
					{"f-35c_stealthab"					"<c(FFFF00)>Stealth MRCA</c>"}
					{"f-35c_strike"						"<c(FFFF00)>Stealth MRCA</c>"}
					{"f-35c_support"					"<c(FFFF00)>Stealth MRCA</c>"}
				;uh60
					{"sikorsky s-70c2"					"<c(FFFF00)>Utility helicopter</c>"}
					{"uh60"								"<c(FFFF00)>Utility helicopter</c>"}
				{"a-10c_bomber"							"<c(FFFF00)>CAS attack aircraft</c>"}
				{"ah1z"									"<c(FFFF00)>Attack helicopter</c>"}
				{"mh-6"									"<c(FFFF00)>Utility helicopter</c>"}
				{"mq9"									"<c(FFFF00)>UCAV</c>"}
				{"rq11raven"							"<c(FFFF00)>Recon UAV</c>"}
				{"uh1y"									"<c(FFFF00)>Utility helicopter</c>"}
		;art_modern
			;cn
				{"dong_feng_15b"						"<c(FFFF00)>TBM TEL</c>"}
				{"plz-05"								"<c(FFFF00)>SPG</c>"}
				{"phl_81"								"<c(FFFF00)>SPMRL</c>"}
			;gb
				{"as_90"								"<c(FFFF00)>SPG</c>"}
			;ger
				{"lars2"								"<c(FFFF00)>SPMRL</c>"}
				{"pzh2000"								"<c(FFFF00)>SPG</c>"}
			;rus
				;9k72
					{"9k72"								"<c(FFFF00)>TBM TEL</c>"}
					{"9k72_for_single"					"<c(FFFF00)>TBM TEL</c>"}
				;bm-30_tornado_s
					{"bm-30_smerch"						"<c(FFFF00)>MLRS</c>"}
					{"bm-30_tornado_s"					"<c(FFFF00)>MLRS</c>"}
				{"2c3_akaciya"							"<c(FFFF00)>SPG</c>"}
				{"2c9"									"<c(FFFF00)>Airborne amphibious SPG</c>"}
				{"iskander"								"<c(FFFF00)>TBM TEL</c>"}
				{"Koalition"							"<c(FFFF00)>SPG</c>"}
				{"Msta"									"<c(FFFF00)>SPG</c>"}
				{"Mstasm2"								"<c(FFFF00)>SPG</c>"}
				{"tos-1a_solntsepek"					"<c(FFFF00)>SMLRS</c>"}	
			;usa
				;m142_himars
					{"m142_himars"						"<c(FFFF00)>MLRS</c>"}
					{"m142_himarser"					"<c(FFFF00)>MLRS</c>"}
				;mlrs_new
					{"mrls"								"<c(FFFF00)>MLRS</c>"}
					{"mrls_2"							"<c(FFFF00)>MLRS</c>"}
					{"mrls_atacms"						"<c(FFFF00)>TML</c>"}
					{"mrls_atacms_2"					"<c(FFFF00)>TML</c>"}
					{"mrls_atacms_nato"					"<c(FFFF00)>TML</c>"}
				{"dana_152mm"							"<c(FFFF00)>SPG</c>"}
				{"paladin"								"<c(FFFF00)>SPG</c>"}
		;btr_modern
			;cn
				;zbl_08
					{"zbl_08"							"<c(FFFF00)>IFV</c>"}
					{"zbl_08_atgm"						"<c(FFFF00)>IFV</c>"}
				;zsl_92
					{"zsl-92a"							"<c(FFFF00)>APC</c>"}
					{"zsl-92b"							"<c(FFFF00)>APC</c>"}
				{"aft-10"								"<c(FFFF00)>ATMC</c>"}
				{"aft-9"								"<c(FFFF00)>ATMC</c>"}
				{"hq_7b"								"<c(FFFF00)>SAM TELAR</c>"}
				{"pgz-04"								"<c(FFFF00)>SPAAA</c>"}
				{"pgz-09"								"<c(FFFF00)>SPAAA</c>"}
				{"zbd-86"								"<c(FFFF00)>IFV</c>"}
				{"zbd04a"								"<c(FFFF00)>Amphibious IFV</c>"}
				{"zbd86a"								"<c(FFFF00)>IFV</c>"}
			;fr
				;amx10rcr
					{"amx10rc"							"<c(FFFF00)>FSV</c>"}
					{"amx10rcr"							"<c(FFFF00)>FSV</c>"}
				;vbi_reco
					{"vbl_anf"							"<c(FFFF00)>Recon vehicle</c>"}
					{"vbl_milan"						"<c(FFFF00)>ATMC</c>"}
					{"vbl_mistral"						"<c(FFFF00)>SAM TEL</c>"}
					{"vbl_reco"							"<c(FFFF00)>Recon vehicle</c>"}
				{"vab_mephisto"							"<c(FFFF00)>ATMC</c>"}
				{"vab_reco"								"<c(FFFF00)>ARV</c>"}
				{"vbci"									"<c(FFFF00)>IFV</c>"}
				{"vbci_2"								"<c(FFFF00)>IFV</c>"}
				{"vbci_vpc"								"<c(FFFF00)>CC vehicle</c>"}					
			;gb
				;warrior
					{"warrior"							"<c(FFFF00)>IFV</c>"}
					{"warrior_wrap2"					"<c(FFFF00)>IFV</c>"}
				{"ajax"									"<c(FFFF00)>ARV/AFV</c>"}
				{"boxer_artec_mgun"						"<c(FFFF00)>APC</c>"}
				{"boxer_gun_noptur_gb"					"<c(FFFF00)>IFV</c>"}
				{"fv432_mk2"							"<c(FFFF00)>APC</c>"}
				{"fv107scimitar_mk2"					"<c(FFFF00)>ARV</c>"}
			;ger
				;boxer_apc
					{"boxer_gmg"						"<c(FFFF00)>APC</c>"}
					{"boxer_mgun"						"<c(FFFF00)>APC</c>"}
				;boxer_gun
					{"boxer_gun"						"<c(FFFF00)>IFV</c>"}				
					{"boxer_gun_noptur"					"<c(FFFF00)>IFV</c>"}
				;fennek
					{"fennek"							"<c(FFFF00)>Recon vehicle</c>"}
					{"fennek_gmg"						"<c(FFFF00)>Recon vehicle</c>"}
				;tpz1a6
					{"tpz1a6"							"<c(FFFF00)>APC</c>"}
					{"tpz1a6_uk"						"<c(FFFF00)>ARV</c>"}
				{"marder_1a3"							"<c(FFFF00)>IFV</c>"}
				{"puma"									"<c(FFFF00)>IFV</c>"}
				{"puma_noptur"							"<c(FFFF00)>IFV</c>"}
				{"wiesel1_gun"							"<c(FFFF00)>Airborne AWC</c>"}
				{"wiesel1_tow"							"<c(FFFF00)>Airborne AWC</c>"}
			;pol
				{"kto_rosomak"							"<c(FFFF00)>APC</c>"}
			;rus
				;-mtlb_new
					{"mtlb"								"<c(FFFF00)>Amphibious APC</c>"}
					{"mtlb_new"							"<c(FFFF00)>Amphibious APC</c>"}
					{"mtlb_vmk"							"<c(FFFF00)>Amphibious APC</c>"}
					{"mtlb_vmk_no_ammobox"				"<c(FFFF00)>Amphibious APC</c>"}
				;9k35_sterla-10
					{"9k35_strela-10"					"<c(FFFF00)>SAM TEL</c>"}
					{"9k35_strela-10m3"					"<c(FFFF00)>SAM TEL</c>"}
					{"9k35_strela-10mn"					"<c(FFFF00)>SAM TEL</c>"}
				;bmd1
					{"bmd1"								"<c(FFFF00)>Airborne amphibious IFV</c>"}
					{"bmd1p"							"<c(FFFF00)>Airborne amphibious IFV</c>"}
				;bmd4m
					{"bmd4m"							"<c(FFFF00)>Airborne amphibious IFV</c>"}
					{"bmd4m_sadovnitsa"					"<c(FFFF00)>Airborne amphibious IFV</c>"}
				;bmp2_new
					{"bmp2_new"							"<c(FFFF00)>Amphibious IFV</c>"}
					{"bmp2_new_without_ptyr"			"<c(FFFF00)>Amphibious IFV</c>"}
				;bmp3
					{"bmp3"								"<c(FFFF00)>IFV</c>"}
					{"bmp3_2"							"<c(FFFF00)>IFV</c>"}
					{"bmp3_3"							"<c(FFFF00)>IFV</c>"}
					{"bmp3_derivation"					"<c(FFFF00)>IFV</c>"}
					{"bmp3_dz"							"<c(FFFF00)>IFV</c>"}
					{"bmp3m"							"<c(FFFF00)>IFV</c>"}
				;btr-d
					{"btr-d"							"<c(FFFF00)>Airborne amphibious utility APC</c>"}
					{"btr-d_zu"							"<c(FFFF00)>Airborne amphibious utility APC</c>"}
					{"btr-rd"							"<c(FFFF00)>Airborne amphibious utility APC</c>"}
				;btr80_new
					{"btr80_2_new"						"<c(FFFF00)>Amphibious APC</c>"}
					{"btr80_new"						"<c(FFFF00)>Amphibious APC</c>"}
				;btr80a.82a
					{"btr80a"							"<c(FFFF00)>Amphibious APC</c>"}
					{"btr82a"							"<c(FFFF00)>Amphibious APC</c>"}
					{"btr82a_mgun"						"<c(FFFF00)>Amphibious APC</c>"}
				;btr90_kom
					{"armbr_hqcar"						"<c(FFFF00)>CC vehicle</c>"}
					{"artbr_hqcar"						"<c(FFFF00)>CC vehicle</c>"}
					{"btr90_kom"						"<c(FFFF00)>CC vehicle</c>"}
					{"mot_hqcar"						"<c(FFFF00)>CC vehicle</c>"}
					{"specbr_hqcar"						"<c(FFFF00)>CC vehicle</c>"}
					{"vdv_hqcar"						"<c(FFFF00)>CC vehicle</c>"}
					{"vvs_hqcar"						"<c(FFFF00)>CC vehicle</c>"}
				;mtlb_6mx
					{"mtlb_6ma"							"<c(FFFF00)>APC</c>"}
					{"mtlb_6mb"							"<c(FFFF00)>APC</c>"}
				;uran9
					{"Uran9_assault"					"<c(FFFF00)>UCGV</c>"}
					{"Uran9_assault2"					"<c(FFFF00)>UCGV</c>"}
					{"Uran9_support"					"<c(FFFF00)>UCGV</c>"}
				{"9p149_shturm-s"						"<c(FFFF00)>ATMC</c>"}
				{"bmd2"									"<c(FFFF00)>Airborne amphibious IFV</c>"}
				{"bmp1_new"								"<c(FFFF00)>Amphibious IFV</c>"}
				{"bmp1_kliver"							"<c(FFFF00)>Amphibious IFV</c>"}
				{"bmp1_new_zbd-86"						"<c(FFFF00)>IFV</c>"}
				{"bmp2m_new"							"<c(FFFF00)>Amphibious IFV</c>"}
				{"brdm2"								"<c(FFFF00)>Amphibious ARV</c>"}
				{"brdm2_atgm"							"<c(FFFF00)>ATMC</c>"}
				{"brdm2_strela"							"<c(FFFF00)>SAM TEL</c>"}
				{"btr60"								"<c(FFFF00)>Amphibious IFV</c>"}
				{"btr70"								"<c(FFFF00)>Amphibious IFV</c>"}
				{"btr90"								"<c(FFFF00)>Amphibious APC</c>"}
				{"bumerang_k-16"						"<c(FFFF00)>Amphibious APC</c>"}
				{"bumerang_k-17"						"<c(FFFF00)>Amphibious IFV</c>"}
				{"kamaz_43269"							"<c(FFFF00)>MRAP vehicle</c>"}
				{"kurganec_b-10"						"<c(FFFF00)>APC</c>"}
				{"kurganec_b-11"						"<c(FFFF00)>IFV</c>"}
				{"sprutsd"								"<c(FFFF00)>Airborne amphibious AFV</c>"}
			;usa
				;bredly
					{"bredly"							"<c(FFFF00)>IFV</c>"}
					{"m2a3"								"<c(FFFF00)>IFV</c>"}
					{"m2a3_brat"						"<c(FFFF00)>IFV</c>"}
				;lav25_2
					{"bund_hqcar"						"<c(FFFF00)>CC vehicle</c>"}
					{"lav25_2"							"<c(FFFF00)>CC vehicle</c>"}
					{"ngrd_hqcar"						"<c(FFFF00)>CC vehicle</c>"}
					{"usaf_hqcar"						"<c(FFFF00)>CC vehicle</c>"}
					{"usarmy_hqcar"						"<c(FFFF00)>CC vehicle</c>"}
					{"usart_hqcar"						"<c(FFFF00)>CC vehicle</c>"}
					{"usmc_hqcar"						"<c(FFFF00)>CC vehicle</c>"}
				;m1126
					{"m1126"							"<c(FFFF00)>APC</c>"}
					{"m1126_jav"						"<c(FFFF00)>APC</c>"}
					{"m1126_mk19"						"<c(FFFF00)>APC</c>"}
				;m113
					{"m113a"							"<c(FFFF00)>APC</c>"}
					{"m113a_israel"						"<c(FFFF00)>APC</c>"}
				{"aavp7"								"<c(FFFF00)>Amphibious APC</c>"}
				{"lav-ad"								"<c(FFFF00)>SAM/SPAAG</c>"}
				{"lav-atws"								"<c(FFFF00)>ATMC</c>"}
				{"lav25"								"<c(FFFF00)>Amphibious ARV</c>"}
				{"m-1129"								"<c(FFFF00)>SPM</c>"}
				{"m1128"								"<c(FFFF00)>AFV</c>"}
				{"m1134"								"<c(FFFF00)>ATMC</c>"}
				{"M163"									"<c(FFFF00)>SPAAG</c>"}
				{"m163machbet"							"<c(FFFF00)>SAM/SPAAG</c>"}
				{"m2_adats"								"<c(FFFF00)>SAM/ATMC</c>"}
				{"shorad"								"<c(FFFF00)>SPAD</c>"}
		;cannon_modern
			;cn
				{"hj73_stan"							"<c(FFFF00)>ATGM</c>"}
				{"hj8_stan"								"<c(FFFF00)>ATGM</c>"}
				{"pbp-172"								"<c(FFFF00)>MTR</c>"}
				{"pl-66"								"<c(FFFF00)>Howitzer</c>"}
				{"qjz-89_stan"							"<c(FFFF00)>HMG</c>"}
				{"qlz04"								"<c(FFFF00)>AGL</c>"}
				{"radar_bs903"							"<c(FFFF00)>GSR</c>"}
				{"type63_rocket2"						"<c(FFFF00)>MLRS</c>"}
				{"type_pp87"							"<c(FFFF00)>MTR</c>"}
			;fr
				{"mistral_stan"							"<c(FFFF00)>MANPADS</c>"}
				{"mmp_stan"								"<c(FFFF00)>NLOS ATGM</c>"}
				{"mo_81_llr_f1"							"<c(FFFF00)>MTR</c>"}
				{"mortarfr"								"<c(FFFF00)>MTR</c>"}
			;gb
				;mstar_v6
					{"mstar_v6"							"<c(FFFF00)>GSR</c>"}
					{"mstar_v6usa"						"<c(FFFF00)>GSR</c>"}
				{"exactor_mk2"							"<c(FFFF00)>NLOS ATGM</c>"}
				{"l118"									"<c(FFFF00)>Howitzer</c>"}
				{"l16_mortar"							"<c(FFFF00)>MTR</c>"}
				{"m2_stan"								"<c(FFFF00)>HMG</c>"}
			;ger
				;gmg_stan
					{"gmg_stan"							"<c(FFFF00)>AGL</c>"}
					{"mg3_stan"							"<c(FFFF00)>GPMG</c>"}
				;spike_stan
					{"spike_stan"						"<c(FFFF00)>NLOS ATGM</c>"}
					{"spike_stan_idf"					"<c(FFFF00)>NLOS ATGM</c>"}
				{"fh-70"								"<c(FFFF00)>Howitzer</c>"}
				{"milan_stan"							"<c(FFFF00)>ATGM</c>"}
				{"ptur_tow_nato"						"<c(FFFF00)>ATGM</c>"}
			;rus
				;d30
					{"d30"								"<c(FFFF00)>Howitzer</c>"}
					{"pl-96"							"<c(FFFF00)>Howitzer</c>"}
				;psnr5
					{"psnr5"							"<c(FFFF00)>GSR</c>"}
					{"psnr5m"							"<c(FFFF00)>GSR</c>"}
				;ur83p
					{"ur_83p"							"<c(FFFF00)>Mineclearing system</c>"}
				{"2a65_msta_b"							"<c(FFFF00)>Howitzer</c>"}
				{"2b11"									"<c(FFFF00)>MTR</c>"}
				{"2b14_podnos"							"<c(FFFF00)>MTR</c>"}
				{"ags17"								"<c(FFFF00)>AGL</c>"}
				{"ags30_stan"							"<c(FFFF00)>AGL</c>"}
				{"kord_stan"							"<c(FFFF00)>HMG</c>"}
				{"kornet_base_stan"						"<c(FFFF00)>ATGM</c>"}
				{"kornet_stan"							"<c(FFFF00)>ATGM</c>"}
				{"malytka_stan"							"<c(FFFF00)>ATGM</c>"}
				{"metis_m"								"<c(FFFF00)>ATGM</c>"}
				{"mt12_rapira"							"<c(FFFF00)>AT gun</c>"}
				{"p-37"									"<c(FFFF00)>Radar</c>"}
				{"pkm_stan"								"<c(FFFF00)>GPMG</c>"}
				{"ptur_konkurs"							"<c(FFFF00)>ATGM</c>"}
				{"spg_9"								"<c(FFFF00)>RR</c>"}
				{"vant_vm_shield"						"<c(FFFF00)>Ballistic shield</c>"}
				{"vasilek"								"<c(FFFF00)>Gun-mortar</c>"}
				{"ZU23-2"								"<c(FFFF00)>AA gun</c>"}
			;usa
				;patriot
					{"patriot_launcher"					"<c(FFFF00)>SAM TEL</c>"}
					{"patriot_radar"					"<c(FFFF00)>Radar</c>"}
				{"hawk_rls"								"<c(FFFF00)>Radar</c>"}
				{"hawk_cwar"							"<c(FFFF00)>Radar</c>"}
				{"m119"									"<c(FFFF00)>Howitzer</c>"}
				{"m252"									"<c(FFFF00)>MTR</c>"}
				{"mk19"									"<c(FFFF00)>AGL</c>"}
				{"ptur_tow"								"<c(FFFF00)>ATGM</c>"}
		;car_modern
			;cn
				;shaanxi_sx2190_ammo
					{"shaanxi_sx2190_ammo"				"<c(FFFF00)>Utility truck</c>"}
					{"shaanxi_sx2190_ammo_track"		"<c(FFFF00)>Utility truck</c>"}
					{"shaanxi_sx2190_art_pvo"			"<c(FFFF00)>Utility truck</c>"}
					{"shaanxi_sx2190_avia"				"<c(FFFF00)>Utility truck</c>"}
				{"beijing_bj2022"						"<c(FFFF00)>Car</c>"}
				{"dongfeng__mengshi_sk131"				"<c(FFFF00)>Recon vehicle</c>"}
				{"dongfeng_mengshi_hj8"					"<c(FFFF00)>ATMC</c>"}
				{"hq-16b_launcher"						"<c(FFFF00)>SAM TEL</c>"}
				{"hq-16b_radar"							"<c(FFFF00)>Radar</c>"}
				{"lyt2021"								"<c(FFFF00)>Recon vehicle</c>"}
				{"pcp001_cs_sm1"						"<c(FFFF00)>SPM</c>"}
				{"shaanxi_sx2190_passenger"				"<c(FFFF00)>Utility truck</c>"}
				{"shaanxi_sx2190_repair"				"<c(FFFF00)>Utility truck</c>"}
				{"shaanxi_sx2190_tanker"				"<c(FFFF00)>Utility truck</c>"}
			;ir
				{"shahed136_truck"						"<c(FFFF00)>UAV mobile launcher</c>"}
			;cz
				{"tatra_t810"							"<c(FFFF00)>Utility truck</c>"}
			;fr
				{"peugeot_p4"							"<c(FFFF00)>Car</c>"}
				{"renault_gbc_180"						"<c(FFFF00)>Utility truck</c>"}
				{"sampt_arabel"							"<c(FFFF00)>Radar</c>"}
				{"sampt_mamba"							"<c(FFFF00)>SAM TEL</c>"}
			;gb
				;land_rover_truck
					{"land_rover_exactor"				"<c(FFFF00)>MCU Car</c>"}
					{"land_rover_snatch"				"<c(FFFF00)>Car</c>"}
				;land_rover_turret
					{"land_rover_atgm"					"<c(FFFF00)>ATMC</c>"}
					{"land_rover_mgun"					"<c(FFFF00)>Recon vehicle</c>"}
				;mwwmik_jackal2
					{"mwwik_jackal2_gmg"				"<c(FFFF00)>Recon vehicle</c>"}
					{"mwwik_jackal2_mgun"				"<c(FFFF00)>Recon vehicle</c>"}
				{"husky_tsv"							"<c(FFFF00)>MRAP</c>"}
				{"man_sx44"								"<c(FFFF00)>Tactical utility truck</c>"}
				{"pinzgauer_710m"						"<c(FFFF00)>Utility vehicle</c>"}
			;ger
				;dingo2a2
					{"dingo2a1"							"<c(FFFF00)>IMV</c>"}
					{"dingo2a2"							"<c(FFFF00)>IMV</c>"}
				{"dingo2a2_gun"							"<c(FFFF00)>IMV</c>"}
				;man
					{"man_ammo"							"<c(FFFF00)>Utility truck</c>"}
					{"man_art"							"<c(FFFF00)>Utility truck</c>"}
					{"man_avia"							"<c(FFFF00)>Utility truck</c>"}
					{"man_passenjer"					"<c(FFFF00)>Utility truck</c>"}
					{"man_repair"						"<c(FFFF00)>Utility truck</c>"}
				{"kwm_ampv"								"<c(FFFF00)>Armored Car</c>"}
				{"man_tanker"							"<c(FFFF00)>Utility truck</c>"}
				{"roland"								"<c(FFFF00)>SAM TELAR</c>"}
				{"wolf"									"<c(FFFF00)>Car</c>"}
			;rus
				;gas66
					{"gaz66"							"<c(FFFF00)>Utility truck</c>"}
					{"gaz66_inf"						"<c(FFFF00)>Utility truck</c>"}
				;gaz_tiger
					{"gaz_tigr"							"<c(FFFF00)>IMV</c>"}
					{"gaz_tigr_mgun"					"<c(FFFF00)>IMV</c>"}
					{"gaz_tigr_mgun2"					"<c(FFFF00)>IMV</c>"}
				;pantsir
					{"pantsir_s"						"<c(FFFF00)>SPAAW</c>"}
					{"pantsir_s1"						"<c(FFFF00)>SPAAW</c>"}
				;ural-4320_all
					{"ural-4320_fuel"					"<c(FFFF00)>Utility truck</c>"}
					{"ural-4320_kamaz_tent"				"<c(FFFF00)>Utility truck</c>"}
					{"ural-4320_kung"					"<c(FFFF00)>Utility truck</c>"}
					{"ural-4320_long_tent"				"<c(FFFF00)>Utility truck</c>"}
					{"ural-4320_long_tent2"				"<c(FFFF00)>Utility truck</c>"}
					{"ural-4320_long_zu23-2"			"<c(FFFF00)>SPAAG</c>"}
					{"ural-4320_tent2"					"<c(FFFF00)>Utility truck</c>"}
					{"ural-4320_tornado_g"				"<c(FFFF00)>SPMRL</c>"}
					{"ural-4320_tractor"				"<c(FFFF00)>Tractor unit</c>"}
					{"ural375"							"<c(FFFF00)>Utility truck</c>"}
					{"ural375_inf"						"<c(FFFF00)>Utility truck</c>"}
					{"ural375_zu"						"<c(FFFF00)>SPAAG</c>"}
					{"ural_art"							"<c(FFFF00)>Utility truck</c>"}
					{"ural_art_pvo"						"<c(FFFF00)>Utility truck</c>"}
					{"ural_avia"						"<c(FFFF00)>Utility truck</c>"}
					{"ural_eng"							"<c(FFFF00)>Utility truck</c>"}
					{"ural_grad"						"<c(FFFF00)>SPMRL</c>"}
					{"ural_umz"							"<c(FFFF00)>Minelaying truck</c>"}
				{"gaz66_zu"								"<c(FFFF00)>SPAAG</c>"}
				{"kamaz"								"<c(FFFF00)>Utility truck</c>"}
				{"kamaz-4326"							"<c(FFFF00)>Utility truck</c>"}
				{"kamaz-6350"							"<c(FFFF00)>Utility truck</c>"}
				{"kamaz-r142nm"							"<c(FFFF00)>CC vehicle</c>"}
				{"kamaz_taifun"							"<c(FFFF00)>Utility MRAP</c>"}
				{"kornet-d"								"<c(FFFF00)>Missile Carrier</c>"}
				{"kraz255b1_pmp"						"<c(FFFF00)>Utility truck</c>"}
				{"maz7410"								"<c(FFFF00)>Tractor unit</c>"}
				{"maz7410_pricep"						"<c(FFFF00)>Heavy semi-trailer</c>"}
				{"uaz2"									"<c(FFFF00)>Car</c>"}
			;usa
				;hemtt
					{"hemtt_refueller"					"<c(FFFF00)>Tactical utility truck</c>"}
					{"hemtt_tent"						"<c(FFFF00)>Tactical utility truck</c>"}
				;hmmwv_m998_tent
					{"hmmwv_m998"						"<c(FFFF00)>LUV</c>"}
					{"hmmwv_m998_tent"					"<c(FFFF00)>LUV</c>"}
				;hmmwv_turret
					{"hmmwv_for_single"					"<c(FFFF00)>LUV</c>"}
					{"hmmwv_for_single_turret"			"<c(FFFF00)>MMD</c>"}
					{"hmmwv_turret"						"<c(FFFF00)>LUV</c>"}
				;m939
					{"m939"								"<c(FFFF00)>Utility truck</c>"}
					{"m939_inf"							"<c(FFFF00)>Utility truck</c>"}
				;m939_art
					{"m939_art"							"<c(FFFF00)>Utility truck</c>"}
					{"m939_art_pvo"						"<c(FFFF00)>Utility truck</c>"}
					{"m939_avia"						"<c(FFFF00)>Utility truck</c>"}
				;oshkosh_m-atv
					{"oshkosh_m-atv_m2"					"<c(FFFF00)>MRAP vehicle</c>"}
					{"oshkosh_m-atv_m240"				"<c(FFFF00)>MRAP vehicle</c>"}
					{"oshkosh_m-atv_mk19"				"<c(FFFF00)>MRAP vehicle</c>"}
				{"Hmmwv"								"<c(FFFF00)>LUV</c>"}
				{"hmmwv_m1035"							"<c(FFFF00)>LUV</c>"}
				{"Hmmwv_TOW"							"<c(FFFF00)>ATMC</c>"}
				{"m939_eng"								"<c(FFFF00)>Utility truck</c>"}
				{"m1097_avenger"						"<c(FFFF00)>SAM TEL</c>"}
				{"mtvr_m2"								"<c(FFFF00)>Tactical utility truck</c>"}
				{"oshkosh_m-atv"						"<c(FFFF00)>MRAP vehicle</c>"}
				{"oshkosh_mtvr_ammo_mk25"				"<c(FFFF00)>Tactical utility truck</c>"}
				{"oshkosh_mtvr_cargo_mk25"				"<c(FFFF00)>Tactical utility truck</c>"}
				{"oshkosh_mtvr_tanker_mk25"				"<c(FFFF00)>Tactical utility truck</c>"}
				{"patriot_truck"						"<c(FFFF00)>Tractor unit</c>"}
		;car_other
			;uaz_car
				{"UAZ_car"								"<c(FFFF00)>Car</c>"}
				{"UAZ_car_konkurs"						"<c(FFFF00)>Car</c>"}
			{"chevrolet_bel_air"						"<c(FFFF00)>Car</c>"}
			{"chevy_s10"								"<c(FFFF00)>Car</c>"}
			{"dodje"									"<c(FFFF00)>Car</c>"}
			{"dodje_police"								"<c(FFFF00)>Police car</c>"}
			{"fire_department"							"<c(FFFF00)>Fire engine</c>"}
			{"ford_f150"								"<c(FFFF00)>Pickup</c>"}
			{"furgon"									"<c(FFFF00)>Van</c>"}
			{"furgon_swat"								"<c(FFFF00)>Police van</c>"}
			{"gaz_24"									"<c(FFFF00)>Car</c>"}
			{"motorcycle"								"<c(FFFF00)>Motorcycle</c>"}
			{"mtz_80"									"<c(FFFF00)>Tractor</c>"}
			{"prado"									"<c(FFFF00)>Full-size SUV</c>"}																			
			{"toyota_hilux"								"<c(FFFF00)>NSTV</c>"}
			{"toyota_hilux_ammo"						"<c(FFFF00)>NSTV</c>"}
			{"toyota_hilux_dshkm"						"<c(FFFF00)>NSTV</c>"}
			{"toyota_hilux_spg9"						"<c(FFFF00)>NSTV</c>"}
			{"toyota_hilux_transport"					"<c(FFFF00)>NSTV</c>"}
			{"tractor_fiat25"							"<c(FFFF00)>Tracktor</c>"}
			{"uaz_van"									"<c(FFFF00)>Van</c>"}
			{"vaz_2106"									"<c(FFFF00)>Car</c>"}
			{"volkswagen_beetle"						"<c(FFFF00)>Car</c>"}
		;marine_modern
			;rus
				;bpk1155
					{"bpk1155_harlamov"					"<c(FFFF00)>Udaloy-class DDG</c>"}
					{"bpk1155_levchenko"				"<c(FFFF00)>Udaloy-class DDG</c>"}
					{"bpk1155_panteleev"				"<c(FFFF00)>Udaloy-class DDG</c>"}
					{"bpk1155_severomorsk"				"<c(FFFF00)>Udaloy-class DDG</c>"}
					{"bpk1155_tribuc"					"<c(FFFF00)>Udaloy-class DDG</c>"}
					{"bpk1155_vinogradov"				"<c(FFFF00)>Udaloy-class DDG</c>"}
				;linked_entities
					;ak630
						{"ak630"						"<c(FFFF00)>CIWS</c>"}
						{"ak630_side"					"<c(FFFF00)>CIWS</c>"}
					;torpedotube_rus_x2
						{"torpedotube_rus_x2_left"		"<c(FFFF00)>Deck-mounted torpedo launchers</c>"}
						{"torpedotube_rus_x2_right"		"<c(FFFF00)>Deck-mounted torpedo launchers</c>"}
					;torpedotube_rus_x4
						{"torpedotube_rus_x4_left"		"<c(FFFF00)>Deck-mounted torpedo launchers</c>"}
						{"torpedotube_rus_x4_right"		"<c(FFFF00)>Deck-mounted torpedo launchers</c>"}
					;torpedotube_rus_x5
						{"torpedotube_rus_x5_left"		"<c(FFFF00)>Deck-mounted torpedo launchers</c>"}
						{"torpedotube_rus_x5_right"		"<c(FFFF00)>Deck-mounted torpedo launchers</c>"}
					{"a22_ogon"							"<c(FFFF00)>MRL</c>"}
					{"ak100_maingun"					"<c(FFFF00)>Naval gun</c>"}
					{"ak130_maingun"					"<c(FFFF00)>Naval gun</c>"}
					{"ak176"							"<c(FFFF00)>Naval gun</c>"}
					{"ak630_rls"						"<c(FFFF00)>FCR</c>"}
					{"ak630_rls_1"						"<c(FFFF00)>FCR</c>"}
					{"basalt_pu"						"<c(FFFF00)>AShM</c>"}
					{"flag_rls"							"<c(FFFF00)>Radar</c>"}
					{"fort_m_rls"						"<c(FFFF00)>FCR</c>"}
					{"fort_rls"							"<c(FFFF00)>FCR</c>"}
					{"fregat710"						"<c(FFFF00)>Radar</c>"}
					{"fregat710m1"						"<c(FFFF00)>Radar</c>"}
					{"fregat750"						"<c(FFFF00)>Radar</c>"}
					{"granit1144_pu"					"<c(FFFF00)>AShM</c>"}
					{"kinjal_1144"						"<c(FFFF00)>Naval SAM</c>"}
					{"kinjal_1155back"					"<c(FFFF00)>Naval SAM</c>"}
					{"kinjal_1155front"					"<c(FFFF00)>Naval SAM</c>"}
					{"kinjal_rls"						"<c(FFFF00)>FCR</c>"}
					{"kortik"							"<c(FFFF00)>CIWS</c>"}
					{"lev_rls"							"<c(FFFF00)>FCR</c>"}
					{"malahit_pu"						"<c(FFFF00)>AShM</c>"}
					{"moskit_pu"						"<c(FFFF00)>AShM</c>"}
					{"osa_ma_pu"						"<c(FFFF00)>Naval SAM</c>"}
					{"osa_am_rls"						"<c(FFFF00)>FCR</c>"}
					{"podberezovik_rls"					"<c(FFFF00)>Radar</c>"}
					{"podkat_rls"						"<c(FFFF00)>Radar</c>"}
					{"rastrub_pu"						"<c(FFFF00)>AShM/ASW</c>"}
					{"rbu1000"							"<c(FFFF00)>ASW/Torpedo defense system</c>"}
					{"rbu12000"							"<c(FFFF00)>ASW/Torpedo defense system</c>"}
					{"rbu6000"							"<c(FFFF00)>ASW/Torpedo defense system</c>"}
					{"s300f_1144"						"<c(FFFF00)>Naval SAM</c>"}
					{"s300f_1164"						"<c(FFFF00)>Naval SAM</c>"}
					{"uragan_pu"						"<c(FFFF00)>Naval SAM</c>"}
					{"uragan_rls"						"<c(FFFF00)>FCR</c>"}
				;orlan
					{"orlan_body1"						"<c(FFFF00)>Kirov-class battlecruiser</c>"}
					{"orlan_body2"						"<c(FFFF00)>Kirov-class battlecruiser</c>"}
					{"orlan_body3"						"<c(FFFF00)>Kirov-class battlecruiser</c>"}
					{"orlan_body4"						"<c(FFFF00)>Kirov-class battlecruiser</c>"}
					{"orlan_main"						"<c(FFFF00)>Kirov-class battlecruiser</c>"}
				;pr1164
					{"pr1164_moskva"					"<c(FFFF00)>Slava-class cruiser</c>"}
					{"pr1164_ustinov"					"<c(FFFF00)>Slava-class cruiser</c>"}
					{"pr1164_varyag"					"<c(FFFF00)>Slava-class cruiser</c>"}
				;pr1234_ovod
					{"pr1234_ovod"						"<c(FFFF00)>Nanuchka III-class corvette</c>"}
				;zubr
					{"zubr"								"<c(FFFF00)>Zubr-class landing craft</c>"}
				{"636_3varshavyanka"					"<c(FFFF00)>Kilo-class DPEL submarine</c>"}
				{"boat338m"								"<c(FFFF00)>Rescue/guard boat</c>"}
				{"boat1390"								"<c(FFFF00)>Rescue/guard boat</c>"}
				{"boat1402"								"<c(FFFF00)>Rescue/guard boat</c>"}
				{"boat1404"								"<c(FFFF00)>Rescue/guard boat</c>"}
				{"pr949a"								"<c(FFFF00)>Oscar-class SSGN</c>"}
				{"pr956"								"<c(FFFF00)>Sovremenny-class destroyer</c>"}
			;usa
				;arly_burke
					;arly_burke
						{"arley_burke"					"<c(FFFF00)>Arleigh Burke-class DDG</c>"}
						{"arley_burke_a2"				"<c(FFFF00)>Arleigh Burke-class DDG</c>"}
						{"arley_burke_laser"			"<c(FFFF00)>Arleigh Burke-class DDG</c>"}
						{"arley_burke_with_land"		"<c(FFFF00)>Arleigh Burke-class DDG</c>"}
					;weaponry
						{"laws"							"<c(FFFF00)>DEW</c>"}
						{"mk32_left"					"<c(FFFF00)>SVTT</c>"}
						{"mk32_right"					"<c(FFFF00)>SVTT</c>"}
						{"mk38_mod2"					"<c(FFFF00)>Chain gun</c>"}
						{"mk41_32"						"<c(FFFF00)>MLS</c>"}
						{"mk41_64"						"<c(FFFF00)>MLS</c>"}
						{"mk45"							"<c(FFFF00)>Naval gun</c>"}
						{"naval_browning"				"<c(FFFF00)>HMG</c>"}
						{"spg62_radar"					"<c(FFFF00)>FCR</c>"}
				;linked_entities
					{"carrier_cst"						"<c(FFFF00)>CV tow tractor</c>"}
					{"carrier_lifter"					"<c(FFFF00)>Forklift</c>"}
				;nimitz
					;nimitz_body3
						{"nimitz_body3"					"<c(FFFF00)>Nimitz-class CV</c>"}
						{"nimitz_body3_cvn68"			"<c(FFFF00)>Nimitz-class CV</c>"}
						{"nimitz_body3_cvn69"			"<c(FFFF00)>Nimitz-class CV</c>"}
						{"nimitz_body3_cvn73"			"<c(FFFF00)>Nimitz-class CV</c>"}
						{"nimitz_body3_cvn75"			"<c(FFFF00)>Nimitz-class CV</c>"}
					;nimitz_body4
						{"nimitz_body4"					"<c(FFFF00)>Nimitz-class CV</c>"}
						{"nimitz_body4_cvn68"			"<c(FFFF00)>Nimitz-class CV</c>"}
						{"nimitz_body4_cvn69"			"<c(FFFF00)>Nimitz-class CV</c>"}
						{"nimitz_body4_cvn73"			"<c(FFFF00)>Nimitz-class CV</c>"}
						{"nimitz_body4_cvn75"			"<c(FFFF00)>Nimitz-class CV</c>"}
					;nimitz_main
						{"nimitz_main"					"<c(FFFF00)>Nimitz-class CV</c>"}
						{"nimitz_main_cvn68"			"<c(FFFF00)>Nimitz-class CV</c>"}
						{"nimitz_main_cvn69"			"<c(FFFF00)>Nimitz-class CV</c>"}
						{"nimitz_main_cvn73"			"<c(FFFF00)>Nimitz-class CV</c>"}
						{"nimitz_main_cvn75"			"<c(FFFF00)>Nimitz-class CV</c>"}
					{"nimitz_body"						"<c(FFFF00)>Nimitz-class CV</c>"}
					{"nimitz_body1"						"<c(FFFF00)>Nimitz-class CV</c>"}
					;weaponry
						{"mk95_radar"					"<c(FFFF00)>FCR</c>"}
						{"phalanx"						"<c(FFFF00)>CIWS</c>"}
						{"sea_sparrow"					"<c(FFFF00)>SAM</c>"}
						{"searam"						"<c(FFFF00)>SAM</c>"}
				{"boat_rhib"							"<c(FFFF00)>RIB</c>"}
				{"lcac"									"<c(FFFF00)>Landing craft</c>"}
				{"los_angeles"							"<c(FFFF00)>Los Angeles-class SSN</c>"}
		;missile_modern
			;aim-9l
				{"aim-9l"								"<c(FFFF00)>SRAAM</c>"}
				{"aim-9l_ammo"							"<c(FFFF00)>SRAAM</c>"}
				{"aim-9l_impactor"						"<c(FFFF00)>SRAAM</c>"}
			;service_stuff
				{"rus_las_designator"					"<c(FFFF00)>GLTD/Range finder</c>"}
			{"48n6e2"									"<c(FFFF00)>SAM</c>"}
			{"maverick"									"<c(FFFF00)>AGM</c>"}
			{"x-25ml"									"<c(FFFF00)>AGM</c>"}
		;proj_2
			;atgm_carrier
				{"mmp_missile_carrier"					"<c(FFFF00)>NLOS ATGM</c>"}
				{"red_arrow_10b_carrier"				"<c(FFFF00)>NLOS ATGM</c>"}
				{"Spike-er2_carrier"					"<c(FFFF00)>ATGM</c>"}
				{"spike-er_carrier"						"<c(FFFF00)>ATGM</c>"}
				{"spike-lr_carrier"						"<c(FFFF00)>ATGM</c>"}
				{"spike_nlos_carrier"					"<c(FFFF00)>NLOS ATGM</c>"}
				{"spike_nlos_fg_carrier"				"<c(FFFF00)>NLOS ATGM</c>"}
				{"switchblade300_carrier"				"<c(FFFF00)>Loitering munition</c>"}
				{"shahed136_base_carrier"				"<c(FFFF00)>Loitering munition</c>"}
			;sam_carrier
				{"x59m_carrier"							"<c(FFFF00)>ALCM</c>"}
		;tank_modern
			;cn
				{"ztz-96a"								"<c(FFFF00)>MBT</c>"}
				{"ztz-99a"								"<c(FFFF00)>MBT</c>"}
				{"ztz_99_phase_2"						"<c(FFFF00)>MBT</c>"}
			;fr
				;lecrerc
					{"leclerc"							"<c(FFFF00)>MBT</c>"}
					{"leclerc_azur"						"<c(FFFF00)>MBT</c>"}
			;gb
				;challenger_2
					{"challenger_2"						"<c(FFFF00)>MBT</c>"}
					{"challenger_2_applique"			"<c(FFFF00)>MBT</c>"}
			;gr
				;leopard_1a4_c1
					{"leopard_1a4"						"<c(FFFF00)>MBT</c>"}
					{"leopard_1a5"						"<c(FFFF00)>MBT</c>"}
					{"leopard_c1"						"<c(FFFF00)>MBT</c>"}
				;leopard_2a0_2a4
					{"leopard_2a0"						"<c(FFFF00)>MBT</c>"}
					{"leopard_2a4"						"<c(FFFF00)>MBT</c>"}
				;leopard_2a5_2a6
					{"leopard_2a5"						"<c(FFFF00)>MBT</c>"}
					{"leopard_2a6"						"<c(FFFF00)>MBT</c>"}
				;leopard_2a7plus
					{"leopard_2a7plus"					"<c(FFFF00)>MBT</c>"}
					{"leopard_2a7plus_gmg"				"<c(FFFF00)>MBT</c>"}
				{"gepard"								"<c(FFFF00)>SPAAG</c>"}
			;idf
				;merkava_mk4
					{"merkava_mk4"						"<c(FFFF00)>MBT</c>"}
					{"merkava_trophy"					"<c(FFFF00)>MBT</c>"}	
				{"magach7"								"<c(FFFF00)>MBT</c>"}
				{"namer"								"<c(FFFF00)>APC</c>"}
			;nato
				{"pt-91"								"<c(FFFF00)>MBT</c>"}
				{"t72m4cz"								"<c(FFFF00)>MBT</c>"}
		;tank_modern
			;rus
				;buk_m1
					{"buk_m1"							"<c(FFFF00)>SAM TELAR</c>"}
					{"buk_m2"							"<c(FFFF00)>SAM TELAR</c>"}
				;pak_t72_new
					;t72(era_k5)_all
						{"t72b3"						"<c(FFFF00)>MBT</c>"}
						{"t72b3_single"					"<c(FFFF00)>MBT</c>"}
						{"t72b_1989year"				"<c(FFFF00)>MBT</c>"}
						{"t72ba"						"<c(FFFF00)>MBT</c>"}
					;t72a_all
						{"t72_yral"						"<c(FFFF00)>MBT</c>"}
						{"t72a"							"<c(FFFF00)>MBT</c>"}
						{"t72m1"						"<c(FFFF00)>MBT</c>"}
						{"t72m_siriya"					"<c(FFFF00)>MBT</c>"}
					;t72b3_2017
						{"t72b3_2017"					"<c(FFFF00)>MBT</c>"}
						{"t72b3_2017_2"					"<c(FFFF00)>MBT</c>"}
					;t72b_all
						{"t72a_1984year"				"<c(FFFF00)>MBT</c>"}
						{"t72b"							"<c(FFFF00)>MBT</c>"}
						{"t72b1"						"<c(FFFF00)>MBT</c>"}
						{"t72b_single"					"<c(FFFF00)>MBT</c>"}
					{"t72av"							"<c(FFFF00)>MBT</c>"}
					{"t72b3_gorod_komplect"				"<c(FFFF00)>MBT/CEV</c>"}
				;pak_t80
					;t80b_all
						{"t80b"							"<c(FFFF00)>MBT</c>"}
						{"t80b_2"						"<c(FFFF00)>MBT</c>"}
						{"t80bv"						"<c(FFFF00)>MBT</c>"}
						{"t80bv_2"						"<c(FFFF00)>MBT</c>"}
						{"t80bvm"						"<c(FFFF00)>MBT</c>"}
						{"t80bvm_2"						"<c(FFFF00)>MBT</c>"}
					;t80y_all
						{"t80y"							"<c(FFFF00)>MBT</c>"}
						{"t80y_2"						"<c(FFFF00)>MBT</c>"}
						{"t80ye-1"						"<c(FFFF00)>MBT</c>"}
						{"t80yk"						"<c(FFFF00)>MBT</c>"}
						{"t80ym1"						"<c(FFFF00)>MBT</c>"}
				;shilka
					{"Shilka"							"<c(FFFF00)>SPAAG</c>"}
					{"Shilka_nato"						"<c(FFFF00)>SPAAG</c>"}
				;t15
					{"t-15"								"<c(FFFF00)>HIFV</c>"}
					{"t-15_au220"						"<c(FFFF00)>HIFV</c>"}
				;t62_cw
					{"t62_cw"							"<c(FFFF00)>MBT</c>"}
					{"t62m"								"<c(FFFF00)>MBT</c>"}
					{"t62m_v2"							"<c(FFFF00)>MBT</c>"}
					{"t62md"							"<c(FFFF00)>Medium tank</c>"}
				;t90sm
					{"t90sm"							"<c(FFFF00)>MBT</c>"}
					{"t90sm_zpy12"						"<c(FFFF00)>MBT</c>"}
				{"9s18_kupol"							"<c(FFFF00)>Radar</c>"}
				{"bmpt"									"<c(FFFF00)>AFV</c>"}
				{"bmr-3"								"<c(FFFF00)>CEV</c>"}
				{"t-14"									"<c(FFFF00)>MBT</c>"}
				{"t-55"									"<c(FFFF00)>MBT</c>"}
				{"t-90a"								"<c(FFFF00)>MBT</c>"}
				{"t34-85_cw"							"<c(FFFF00)>Medium tank</c>"}
				{"t64"									"<c(FFFF00)>MBT</c>"}
				{"tunguska"								"<c(FFFF00)>SPAAW</c>"}
			;ukr
				{"bm_oplot"								"<c(FFFF00)>MBT</c>"}
				{"t-64b"								"<c(FFFF00)>MBT</c>"}
				{"t-64bv"								"<c(FFFF00)>MBT</c>"}
				{"t-64bm1"								"<c(FFFF00)>MBT</c>"}
				{"t-64bm2"								"<c(FFFF00)>MBT</c>"}
			;usa
				;m1a1_all_model
					{"m1a1_FEP"							"<c(FFFF00)>MBT</c>"}
					{"m1a1_new"							"<c(FFFF00)>MBT</c>"}
					{"m1a2_sep"							"<c(FFFF00)>MBT</c>"}
					{"m1a2sep3"							"<c(FFFF00)>MBT</c>"}
					{"m1ip_1"							"<c(FFFF00)>MBT</c>"}
					{"m1ip_2"							"<c(FFFF00)>MBT</c>"}
				;m1a1tusk_2_new
					{"m1a2tusk_2_new"					"<c(FFFF00)>MBT</c>"}
					{"m1a2tusk_2_m2_new"				"<c(FFFF00)>MBT</c>"}
				{"M1_Abrams"							"<c(FFFF00)>MBT</c>"}
				{"m1a2tusk"								"<c(FFFF00)>MBT</c>"}
				{"m60a3"								"<c(FFFF00)>MBT</c>"}
		;train_modern
			{"2te10"									"<c(FFFF00)>Diesel-electric locomotive</c>"}
			{"locomote_tgmz_1010"						"<c(FFFF00)>Diesel locomotive</c>"}
	;cannon
		{"browning_m2hb_stan"							"<c(FFFF00)>HMG</c>"}
		{"kpvt"											"<c(FFFF00)>HMG</c>"}
;new_entities
	;-supply_crates
		;for_mp
			{"supply_nato_pvo_aviation"					"<c(FFFF00)>Ammunition box</c>"}
			{"supply_rus_art_eng"						"<c(FFFF00)>Ammunition box</c>"}
			{"supply_rus_bmp_btr_tanks"					"<c(FFFF00)>Ammunition box</c>"}
			{"supply_rus_light_weap"					"<c(FFFF00)>Ammunition box</c>"}
			{"supply_rus_pvo_aviation"					"<c(FFFF00)>Ammunition box</c>"}
			{"supply_usa_art_eng"						"<c(FFFF00)>Ammunition box</c>"}
			{"supply_usa_bmp_btr_tanks"					"<c(FFFF00)>Ammunition box</c>"}
			{"supply_usa_light_weap"					"<c(FFFF00)>Ammunition box</c>"}
			{"supply_usa_pvo_aviation"					"<c(FFFF00)>Ammunition box</c>"}
;service
	;for_mp
		;mp_flag
			{"abn_mp_flag"								"<c(FFFF00)>Flag</c>"}
			{"armbr_mp_flag"							"<c(FFFF00)>Flag</c>"}
			{"artbr_mp_flag"							"<c(FFFF00)>Flag</c>"}
			{"bund_mp_flag"								"<c(FFFF00)>Flag</c>"}
			{"cbn_mp_flag"								"<c(FFFF00)>Flag</c>"}
			{"chi_dummy_flag"							"<c(FFFF00)>Flag</c>"}
			{"cnair_mp_flag"							"<c(FFFF00)>Flag</c>"}
			{"cnart_mp_flag"							"<c(FFFF00)>Flag</c>"}
			{"cnheavy_mp_flag"							"<c(FFFF00)>Flag</c>"}
			{"cnmed_mp_flag"							"<c(FFFF00)>Flag</c>"}
			{"cnsam_mp_flag"							"<c(FFFF00)>Flag</c>"}
			{"cnsco_mp_flag"							"<c(FFFF00)>Flag</c>"}
			{"fra_mp_flag"								"<c(FFFF00)>Flag</c>"}
			{"gb_mp_flag"								"<c(FFFF00)>Flag</c>"}
			{"idf_mp_flag"								"<c(FFFF00)>Flag</c>"}
			{"mot_mp_flag"								"<c(FFFF00)>Flag</c>"}
			{"nato_aa_mp_flag"							"<c(FFFF00)>Flag</c>"}
			{"nato_dummy_flag"							"<c(FFFF00)>Flag</c>"}
			{"nrf_mp_flag"								"<c(FFFF00)>Flag</c>"}
			{"pvo_mp_flag"								"<c(FFFF00)>Flag</c>"}
			{"rus_dummy_flag"							"<c(FFFF00)>Flag</c>"}
			{"specbr_mp_flag"							"<c(FFFF00)>Flag</c>"}
			{"usa_aa_mp_flag"							"<c(FFFF00)>Flag</c>"}
			{"usa_dummy_flag"							"<c(FFFF00)>Flag</c>"}
			{"usaf_mp_flag"								"<c(FFFF00)>Flag</c>"}
			{"usarmy_mp_flag"							"<c(FFFF00)>Flag</c>"}
			{"usart_mp_flag"							"<c(FFFF00)>Flag</c>"}
			{"usmc_mp_flag"								"<c(FFFF00)>Flag</c>"}
			{"vdv_mp_flag"								"<c(FFFF00)>Flag</c>"}
			{"vvs_mp_flag"								"<c(FFFF00)>Flag</c>"}
		;persistent_marker
			{"persistent_marker_cn"						"<c(FFFFFF)e(shadow)>Marker</c>"}
			{"persistent_marker_nato"					"<c(FFFFFF)e(shadow)>Marker</c>"}
			{"persistent_marker_rus"					"<c(FFFFFF)e(shadow)>Marker</c>"}
			{"persistent_marker_usa"					"<c(FFFFFF)e(shadow)>Marker</c>"}
;vehicle+infantry
	;cn
		{"pzrk2_cn"										"<c(FFFF00)>Car</c>"}
	;nato
		{"pzrk2_nato"									"<c(FFFF00)>APC</c>"}
	;rus
		{"pzrk2_rus"									"<c(FFFF00)>APC</c>"}
	;usa
		{"pzrk2_usa"									"<c(FFFF00)>Utility vehicle</c>"}
;AS2
	;faunua
		{"chiken"										"<c(FFFF00)>Animal</c>"}
		{"cow"											"<c(FFFF00)>Animal</c>"}
		{"horse"										"<c(FFFF00)>Animal</c>"}
		{"horse_bones"									"<c(FFFF00)>Animal</c>"}
;CTA
	;cta_entities
		;fanua
			{"carp"										"<c(FFFF00)>Animal</c>"}
			{"crab"										"<c(FFFF00)>Animal</c>"}
			{"dog"										"<c(FFFF00)>Animal</c>"}
			{"fish"										"<c(FFFF00)>Animal</c>"}
			{"goat"										"<c(FFFF00)>Animal</c>"}
			{"hawk"										"<c(FFFF00)>Animal</c>"}
			{"pig"										"<c(FFFF00)>Animal</c>"}
			{"raven"									"<c(FFFF00)>Animal</c>"}
			{"seagull"									"<c(FFFF00)>Animal</c>"}
			{"shark"									"<c(FFFF00)>Animal</c>"}
			{"sheep"									"<c(FFFF00)>Animal</c>"}
			{"swan"										"<c(FFFF00)>Animal</c>"}
		;vehicle
			;civilian
				;car
					{"car"								"<c(FFFF00)>Car</c>"}
					{"car_taxi"							"<c(FFFF00)>Car</c>"}
				;truck
					{"truck"							"<c(FFFF00)>Tractor unit</c>"}
					{"truck_low_loader"					"<c(FFFF00)>Tractor unit</c>"}
					{"truck_trailer"					"<c(FFFF00)>Tipper truck</c>"}
					{"truck_trailer_cementmixer"		"<c(FFFF00)>Cement mixer truck</c>"}
					{"truck_trailer_closed"				"<c(FFFF00)>Goods truck</c>"}
				{"bus"									"<c(FFFF00)>Minibus</c>"}
				{"car_small"							"<c(FFFF00)>Car</c>"}
				{"train_cabin"							"<c(FFFF00)>Passenger wagon</c>"}
				{"train_engine"							"<c(FFFF00)>Locomotive</c>"}
				{"train_fuelwagen"						"<c(FFFF00)>Tank wagon</c>"}
				{"train_wagen"							"<c(FFFF00)>Flat wagon</c>"}
				{"train_wagen_2"						"<c(FFFF00)>Flat wagon</c>"}
				{"train_wagen_3"						"<c(FFFF00)>Flat wagon</c>"}
				{"train_wagen_container"				"<c(FFFF00)>Flat wagon</c>"}
				{"truck_small"							"<c(FFFF00)>Dump truck</c>"}
;unavailable
	;nato
		{"abn_hqcar"									"<c(FFFF00)>CC vehicle</c>"}
		{"cbn_hqcar"									"<c(FFFF00)>CC vehicle</c>"}
		{"fra_hqcar"									"<c(FFFF00)>CC vehicle</c>"}
		{"gb_hqcar"										"<c(FFFF00)>CC vehicle</c>"}
		{"mq9_nato"										"<c(FFFF00)>UCAV</c>"}
		{"nrf_hqcar"									"<c(FFFF00)>CC vehicle</c>"}
		{"patriot_launcher_nato"						"<c(FFFF00)>SAM TEL</c>"}
		{"patriot_radar_nato"							"<c(FFFF00)>Radar</c>"}
		{"uh60_nato"									"<c(FFFF00)>Utility helicopter</c>"}
	;rus
		{"9k57_uragan"									"<c(FFFF00)>SPMRL</c>"}
		{"bmp1"											"<c(FFFF00)>Amphibious IFV</c>"}
		{"bmp2"											"<c(FFFF00)>Amphibious IFV</c>"}
		{"bmp2m"										"<c(FFFF00)>Amphibious IFV</c>"}
		{"mtlb_no_ammobox"								"<c(FFFF00)>APC</c>"}
		{"t62"											"<c(FFFF00)>Medium tank</c>"}
	;usa
		{"Humvee"										"<c(FFFF00)>Armored Car</c>"}
		{"M1A1"											"<c(FFFF00)>MBT</c>"}
		{"cougar"										"<c(FFFF00)>MRAP vehicle</c>"}
		{"m1a1_shield_new"								"<c(FFFF00)>MBT</c>"}
		{"m1a2_all_model"								"<c(FFFF00)>MBT</c>"}
		{"m1a2tusk_new"									"<c(FFFF00)>MBT</c>"}
		{"m1ip"											"<c(FFFF00)>MBT</c>"}
		{"m2a3_btr"										"<c(FFFF00)>IFV</c>"}
		{"m2a3_new"										"<c(FFFF00)>IFV</c>"}
		{"mortarfru"									"<c(FFFF00)>MTR</c>"}
		{"ngrd_mp_flag"									"<c(FFFF00)>Flag</c>"}