;Revised by maaa - DTTGOC
;LocalGen2
;Extra data placeholder
;Extra data placeholder
;rev 05.07.2022

;Note:
;1- Row order is from left to right.
;2- Item definers can be extracted from set\multiplayer\units (unit_nation.set,and soldiers.set) or from the in-game multiplayer reinforcements menu

;Ordinal number of row:
	;1st row
	;2nd row
	;3rd row
	;4th row
	;5th row 
	;6th row
	
;nation
	;brigade name
		;ordinal number of row
			;item definer(squad, vehicle, etc.)		;item name	
	
;________________________________________________________________________________________________________											
;china
	;common troops
		;1st row
			{"bazookers2(cn)"						"<c(FFFFFF)e(shadow)>Red Arrow 12 anti-armor team</c>"}
			{"pzrk(cn)"								"<c(FFFFFF)e(shadow)>MANPADS team</c>"}
		;4th row
			{"zsl-92ai"								"<c(FFFFFF)e(shadow)>Mechanized INF. squad on ZSL-92</c>"}
			{"shaanxi_sx2190_passengeri"			"<c(FFFFFF)e(shadow)>Motorized INF. squad on Shaanxi SX2190</c>"}
	;support and auxiliary units
		;2nd row
			{"tankman(cn)"							"<c(FFFFFF)e(shadow)>Armor crew</c>"}
			{"tankmans(cn)"							"<c(FFFFFF)e(shadow)>Armor crew</c>"}
			{"tankman3(cn)"							"<c(FFFFFF)e(shadow)>Armor crew</c>"}
			{"tankmans3(cn)"						"<c(FFFFFF)e(shadow)>Armor crew</c>"}
			{"vehicle_supporter(cn)"				"<c(FFFFFF)e(shadow)>Weapon OPR./Driver</c>"}
		;3rd row
			{"pilot(cn)"							"<c(FFFFFF)e(shadow)>Pilot</c>"}
			{"operator_bpla(cn)"					"<c(FFAF00)e(shadow)>CH-802<c(00FF00)e(shadow)> Rainbow<c(FFFFFF)e(shadow)> UAV</c>"}
	;pla air force (plaaf)
		;3rd row
			{"sso_cn"								"<c(FFFFFF)e(shadow)>SOF squad on Mi-171Sh</c>"}
	;pla air defence force
			{"p-37_cn"								"<c(FFFFFF)e(shadow)>P-37 Radar</c>"}
	;pla artillery & rocket forces
		;1st row
			{"miners(cn)"							"<c(FFFFFF)e(shadow)>Engineers</c>"}		
			{"sappers(cn)"							"<c(FFFFFF)e(shadow)>Combat engineers</c>"}
			{"spotters(cn)"							"<c(FFFFFF)e(shadow)>Forward observers</c>"}
	;pla heavy combined arms brigade
		;1st row
			{"elite(cn)"							"<c(FFFFFF)e(shadow)>SOF INF. squad</c>"}
			{"shaanxi_sx2190_passengeri_cnheavy"	"<c(FFFFFF)e(shadow)>Motorized Marines INF. squad on Shaanxi SX2190</c>"}
			{"zbd86ai"								"<c(FFFFFF)e(shadow)>Mechanized INF. squad on ZBD-86A</c>"}
		;2nd row
			{"zbd04ai"								"<c(FFFFFF)e(shadow)>Mechanized INF. squad on ZBD-04A</c>"}
			{"snipers2(cn)"							"<c(FFFFFF)e(shadow)>Sniper team</c>"}
			{"at_rifle(cn)"							"<c(FFFFFF)e(shadow)>Anti-materiel sniper team</c>"}
	;pla medium combined arms brigade
		;1st row
			{"elite2(cn)"							"<c(FFFFFF)e(shadow)>SOF INF. squad</c>"}
			{"shaanxi_sx2190_passengeri_cnmed"		"<c(FFFFFF)e(shadow)>Motorized Marines INF. squad on Shaanxi SX2190</c>"}
			{"zsl-92bi"								"<c(FFFFFF)e(shadow)>Mechanized Marines INF. squad on ZSL-92B</c>"}
			{"zbl_08_atgmi"							"<c(FFFFFF)e(shadow)>Mechanized Marines INF. squad on ZBL-08</c>"}
		;2nd row
			{"flamers(cn)"							"<c(FFFFFF)e(shadow)>Flamethrower team</c>"}
	;sco joint task force
;________________________________________________________________________________________________________
;nato
	;common troops
		;1st row
			{"cz_rpg(nato)"							"<c(FFFFFF)e(shadow)>M3 MAAWS anti-armor team</c>"}
			{"pzrk(nato)"							"<c(FFFFFF)e(shadow)>MANPADS team</c>"}
		;4th row	
			{"tatra_t810i"							"<c(FFFFFF)e(shadow)>Motorized Czech INF. squad on TATRA T810</c>"}
		;5th row
			{"warrior_wrap2i"						"<c(FFFFFF)e(shadow)>Mechanized Czech INF. squad on MCV-80 Warrior WRAP-2</c>"}
	;support and auxiliary units
		;2nd row
			{"tankman(nato)"						"<c(FFFFFF)e(shadow)>Armor crew</c>"}
			{"vehicle_supporter(nato)"				"<c(FFFFFF)e(shadow)>Weapon OPR./Driver</c>"}
		;3rd row
			{"pilot(nato)"							"<c(FFFFFF)e(shadow)>Pilot</c>"}
			{"operator_bpla(nato)"					"<c(FFFFFF)e(shadow)>EMT Aladin UAV</c>"}
	;nato allied air command
		;4th row
			{"nh90sas"								"<c(FFFFFF)e(shadow)>SAS INF. squad on NH-90</c>"}
	;nato integrated air and missile defence		
		;2nd row
			{"hawk_rls_nato"						"<c(FFFFFF)e(shadow)>MIM-23 Hawk AN/MPQ-50 IPAR</c>"}
	;nato field artillery
		;1st row
			{"miner(nato)"							"<c(FFFFFF)e(shadow)>Engineers</c>"}
			{"sappers(nato)"						"<c(FFFFFF)e(shadow)>Combat engineers</c>"}
			{"brit_scouts(nato)"					"<c(FFFFFF)e(shadow)>SAS saboteurs team</c>"}
	;bundeswehr
		;1st row
			{"frg_ksk(nato)"						"<c(FFFFFF)e(shadow)>Kommando Spezialkräfte INF. squad</c>"}
			{"frg_snip(nato)"						"<c(FFFFFF)e(shadow)>Sniper team</c>"}
			{"frg_h_snip(nato)"						"<c(FFFFFF)e(shadow)>Anti-material sniper team</c>"}
		;2nd row
		    {"man_passenjeri" 						"<c(FFFFFF)e(shadow)>Panzergrenadier squad on MAN KAT1</c>"}
			{"marder_1a3i"							"<c(FFFFFF)e(shadow)>Panzergrenadier squad on Marder 1A3</c>"}
		;3rd row
			{"boxer_mguni"							"<c(FFFFFF)e(shadow)>Panzergrenadier squad on Boxer A1</c>"}
			{"boxer_guni"							"<c(FFFFFF)e(shadow)>Panzergrenadier squad on Boxer IFV Lance</c>"}
			{"pumai"								"<c(FFFFFF)e(shadow)>Panzergrenadier squad on SpZ Puma</c>"}
	;her majesty's armed forces
		;1st row
			{"brit_squad_elite(nato)"				"<c(FFFFFF)e(shadow)>SAS special forces INF. squad</c>"}
			{"man_sx44i"							"<c(FFFFFF)e(shadow)>Motorized British INF. squad on MAN SX44</c>"}
			{"warriori"								"<c(FFFFFF)e(shadow)>Mechanized British INF. squad on MCV-80 Warrior</c>"}
		;2nd row
			{"fv432_mk2i"							"<c(FFFFFF)e(shadow)>Mechanized British INF. squad on FV432</c>"}
			{"boxer_gun_noptur_gbi"					"<c(FFFFFF)e(shadow)>Mechanized British INF. squad on ARTEC Boxer Block 1</c>"}
		;3rd row
			{"brit_jav(nato)"						"<c(FFFFFF)e(shadow)>FGM-148 Javelin anti-armor team</c>"}
			{"brit_shipers(nato)"					"<c(FFFFFF)e(shadow)>Sniper team</c>"}
		;4th row
			{"at_rifle_brit(nato)"					"<c(FFFFFF)e(shadow)>Anti-material sniper team</c>"}
	;forces armées françaises	
		;1st
			{"fr_squad_elite(nato)"					"<c(FFFFFF)e(shadow)>1er RPIMa special Forces INF. squad</c>"}
			{"at_rifle_fr(nato)"					"<c(FFFFFF)e(shadow)>Anti-material sniper team</c>"}
			{"marksman_squad_fr(nato)"				"<c(FFFFFF)e(shadow)>1er RPIMa sniper team</c>"}
		;3rd
			{"renault_gbc_180i"						"<c(FFFFFF)e(shadow)>Motorized French INF. squad on Renault GBC 180"}
			{"vbci_vpci"							"<c(FFFFFF)e(shadow)>Mechanized French INF. squad with ATGM on VBCI VPC</c>"}
			{"vbcii"								"<c(FFFFFF)e(shadow)>Mechanized French INF. squad on VBCI</c>"}
		;4th row
			{"vbci_2i"								"<c(FFFFFF)e(shadow)>Mechanized French INF. squad on VBCI-2</c>"}
;________________________________________________________________________________________________________
;russia
	;common troops
		;1st row
			{"bazookers2(rus)"						"<c(FFFFFF)e(shadow)>RPG-29 anti-armor team</c>"}
			{"pzrk(rus)"							"<c(FFFFFF)e(shadow)>MANPADS team</c>"}
		;3rd row
			{"btr80_newi"							"<c(FFFFFF)e(shadow)>Mechanized INF. squad on BTR-80 Mod.2008</c>"}
		;4th row
			{"btr82ai"								"<c(FFFFFF)e(shadow)>Mechanized INF. squad on BTR-82А</c>"} 
			{"Ural375i"								"<c(FFFFFF)e(shadow)>Motorized INF. squad on Ural-4320</c>"}
	;support and auxiliary units
		;2nd row
			{"tankman(rus)"							"<c(FFFFFF)e(shadow)>Armor crew</c>"}
			{"tankmans(rus)"						"<c(FFFFFF)e(shadow)>Armor crew</c>"}
			{"tankman3(rus)"						"<c(FFFFFF)e(shadow)>Armor crew</c>"}
			{"tankmans3(rus)"						"<c(FFFFFF)e(shadow)>Armor crew</c>"}
		;3rd row
			{"vehicle_supporter(rus)"				"<c(FFFFFF)e(shadow)>Weapon OPR./Driver</c>"}
			{"pilot(rus)"							"<c(FFFFFF)e(shadow)>Pilot</c>"}	
	;russian air force (vvs)
		;3 ряд
			{"su-34_accurate_2"						"<c(FFFFFF)e(shadow)>Su-34 <c(FFAF00)e(shadow)>Precision Strike</c>"}
		;5th row
			{"sso"									"<c(FFFFFF)e(shadow)>SSO INF. squad on Mi-8MTV</c>"}
	;svr artillery
		;1st row
			{"miners(rus)"							"<c(FFFFFF)e(shadow)>Engineers</c>"}
			{"sappers(rus)"							"<c(FFFFFF)e(shadow)>Combat engineers</c>"}
			{"spotters(rus)"						"<c(FFFFFF)e(shadow)>Forward observers</c>"}
	;ru airborne forces (vdv)
		;1st row
			{"stormtroopers2(rus)"					"<c(FFFFFF)e(shadow)>VDV INF. squad</c>"}
		;2nd row
			{"mi17_unarmedi"						"<c(FFFFFF)e(shadow)>VDV INF. squad on Mi-8MTV</c>"}
	;svr motorized rifle brigade
		;1st row
			{"elite(rus)"							"<c(FFFFFF)e(shadow)>SSO INF. squad</c>"}
			{"ural375i_mot"							"<c(FFFFFF)e(shadow)>Motorized INF. squad on Ural-4320</c>"}
			{"BMP2_newi"							"<c(FFFFFF)e(shadow)>Mechanized INF. squad on BMP-2</c>"}
		;2nd row
			{"bmp3_2i"								"<c(FFFFFF)e(shadow)>Mechanized INF. squad on BMP-3</c>"}
			{"bmp2m_newi"							"<c(FFFFFF)e(shadow)>Mechanized INF. squad on BMP-2M Berezhok</c>"}
			{"minmen(rus)"							"<c(FFFFFF)e(shadow)>Grenadier</c>"}
		;3rd row
			{"snipers2(rus)"						"<c(FFFFFF)e(shadow)>Sniper team</c>"}
			{"at_rifle(rus)"						"<c(FFFFFF)e(shadow)>Anti-materiel sniper team</c>"}
		;5th row
			{"t72b3m"								"<c(FFFFFF)e(shadow)>T-72B3M</c>"}
	;svr tank brigade
	;bv naval infantry brigade
		;1st row
			{"morspec(rus)"							"<c(FFFFFF)e(shadow)>Spetsnaz VMF INF. squad</c>"}
			{"ural375i_mor"							"<c(FFFFFF)><e(shadow)>Motorized Marines INF. squad on Ural-4320</c>"} 
			{"bmp2_newi2"							"<c(FFFFFF)><e(shadow)>Mechanized Marines INF. squad on BMP-2</c>"}
		;2nd row
			{"bmp3i"								"<c(FFFFFF)e(shadow)>Mechanized Marines INF. squad on BMP-3</c>"}
			{"snipers(rus)"							"<c(FFFFFF)e(shadow)>Sniper team</c>"}
			{"at_rifle_mor(rus)"					"<c(FFFFFF)e(shadow)>Anti-materiel sniper team</c>"}
		;3rd row	
			{"mtlbo"								"<c(FFFFFF)e(shadow)>Mechanized flamethrower team on MT-LB</c>"} 
;________________________________________________________________________________________________________
;usa
	;common troops
		;1st row
			{"bazookers(usa)"						"<c(FFFFFF)e(shadow)>M3 MAAWS anti-armor team</c>"}
			{"bazookers2(usa)"						"<c(FFFFFF)e(shadow)>FGM-148 Javelin anti-armor team</c>"}
			{"pzrk(usa)"							"<c(FFFFFF)e(shadow)>MANPADS team</c>"}
		;3rd row
			{"m939i"								"<c(FFFFFF)e(shadow)>Motorized RFLM INF. squad on M939</c>"} 
		;4th row
			{"mtvr_m2i"								"<c(FFFFFF)e(shadow)>Motorized RFLM INF. squad on Oshkosh MTVR Mk27</c>"}
	;support and auxiliary units
		;2nd row
			{"tankman(usa)"							"<c(FFFFFF)e(shadow)>Armor crew</c>"}
			{"tankmans(usa)"						"<c(FFFFFF)e(shadow)>Armor crew</c>"}
			{"tankman3(usa)"						"<c(FFFFFF)e(shadow)>Armor crew</c>"}
			{"tankmans3(usa)"						"<c(FFFFFF)e(shadow)>Armor crew</c>"}
			{"vehicle_supporter(usa)"				"<c(FFFFFF)e(shadow)>Weapon OPR./Driver</c>"}
		;3rd row
			{"operator_bpla(usa)"					"<c(FFAF00)e(shadow)>RQ-11<c(FFFFFF)e(shadow)> Raven<c(FFFFFF)e(shadow)> UAV</c>"}
			{"pilot(usa)"							"<c(FFFFFF)e(shadow)>Pilot</c>"}
	;u.s. air force (usaf)
		;6th row
			{"sso_usa"								"<c(FFFFFF)e(shadow)>Delta force INF. squad on MH-6</c>"}
	;u.s. army field artillery branch
		;1st row	
			{"miners(usa)"							"<c(FFFFFF)e(shadow)>Engineers</c>"}
			{"sappers(usa)"							"<c(FFFFFF)e(shadow)>Combat engineers</c>"}
			{"usaspot(usa)"							"<c(FFFFFF)e(shadow)>Forward observer</c>"}
	;tzahal (idf)
		;1st row
			{"idf_vdv(usa)"							"<c(FFFFFF)e(shadow)>Sayeret Matkal INF. squad</c>"}
			{"m113ai"								"<c(FFFFFF)e(shadow)>Mechanized INF. squad on M113</c>"}
			{"nameri"								"<c(FFFFFF)e(shadow)>Mechanized INF. squad on Namer</c>"}
		;2nd row
			{"idf_at_rifle(usa)"					"<c(FFFFFF)e(shadow)>Anti-materiel sniper team</c>"}
			{"idf_sniper(usa)"						"<c(FFFFFF)e(shadow)>Sniper team</c>"}
	;u.s. army
		;1st row
			{"defend(usa)"							"<c(FFFFFF)e(shadow)>Delta force INF. squad</c>"}
			{"m939i_usarmy"							"<c(FFFFFF)e(shadow)>Motorized Ranger INF. squad on M939</c>"}
			{"m2a3_brati"							"<c(FFFFFF)e(shadow)>Mechanized RFLM INF. squad on M2A3 Bradley Busk III</c>"}
		;2nd row
			{"m1126jav"								"<c(FFFFFF)e(shadow)>Mechanized Ranger INF. squad on M1126 Stryker ICV - Javelin CCM</c>"}
			{"m1126i"								"<c(FFFFFF)e(shadow)>Mechanized Ranger INF. squad on M1126 Stryker ICV</c>"}
			{"us_army_sniper(usa)"					"<c(FFFFFF)e(shadow)>Sniper team</c>"}
		;3rd row
			{"at_rifle(usa)"						"<c(FFFFFF)e(shadow)>Anti-materiel sniper team</c>"}
	;u.s. marine corps (usmc)
		;1st row
			{"navy_seals(usa)"						"<c(FFFFFF)e(shadow)>Navy SEALs INF. squad</c>"}
			{"m939i_usmc"							"<c(FFFFFF)e(shadow)>Motorized Marines INF. squad on M939</c>"}
			{"aavp7i"								"<c(FFFFFF)e(shadow)>Mechanized Marines INF. squad on AAVP-7A1 EAKK</c>"}
		;2nd row
			{"lav25i"								"<c(FFFFFF)e(shadow)>Mechanized Marines INF. squad on LAV-25</c>"}
			{"usmc_sturm(usa)"						"<c(FFFFFF)e(shadow)>Assault squad</c>"}
		;3rd row
			{"usmc_mgun(usa)"						"<c(FFFFFF)e(shadow)>Machine gun squad</c>"}
			{"usmc_sniper(usa)"						"<c(FFFFFF)e(shadow)>Sniper team</c>"}
			{"usmc_heavy_sniper(usa)"				"<c(FFFFFF)e(shadow)>Anti-materiel sniper team</c>"}
;________________________________________________________________________________________________________
;other (obsolete)
	;nato
		{"bazooker_idf(nato)"						"AT infantry"}
		{"brit_squad(nato)"							"Infantry British"}
		{"cz_squad(nato)"							"Infantry Czech"}
		{"fr_ptrk(nato)"							"ATGM ERYX"}
		{"fr_scouts(nato)"							"1er RPIMa saboteur team"}
		{"fr_scouts(nato)"							"Diversant"}
		{"fr_squad(nato)"							"Infantry French"}
		{"frg_rpg(nato)"							"AT infantry"}
		{"frg_scouts(nato)"							"Diversant"}
		{"frg_squad(nato)"							"Panzergrenadiers"}
		{"hun_rpg(nato)"							"Squad RPG-7 Vengrii"}
		{"hun_squad(nato)"							"Legkaja pekhota"}
		{"idf_squad(nato)"							"Infantry TsАKhАL"}
		{"sapper(nato)"								"Sappers"}
		{"tpz1a6_uki"								"Mechanized British INF. squad on NBC «Fox»"}
		{"tpz1a6i"									"Infantry Czech on TpZ 1A6 Fuchs"}
		{"vab_recoi"								"Mechanized French INF. squad on VAB Reco"}
	;russia
		{"ap_miners(rus)"							"AP miners"}
		{"at_miners(rus)"							"AT miners"}
		{"bazookers(rus)"							"Squad RPG-7"}
		{"bazookers3(rus)"							"AT infantry"}
		{"defend(rus)"								"Marines"}
		{"engineer(rus)"							"Engineer"}
		{"flamers(rus)"								"Flamer"}
		{"flamers2(rus)"							"Flamer"}
		{"mgs(rus)"									"Machinegunner"}
		{"nav(rus)"									"Spotter"}
		{"officer(rus)"								"Officer"}
		{"scout2(rus)"								"Scout"}
		{"scouts(rus)"								"Scout"}
		{"smgs(rus)"								"Motorized infantry squad"}
		{"spec(rus)"								"Spetsnaz"}
		{"stormtroopers(rus)"						"OMON squad"}
	;usa
		{"ap_miners(usa)"							"AP miners"}
		{"at_miners(usa)"							"AT miners"}
		{"bazookers3(usa)"							"AT infantry"}
		{"elite(usa)"								"Rangers"}
		{"engineer(usa)"							"Engineer"}
		{"flamers(usa)"								"Flamer"}
		{"idf_squad(usa)"							"Infantry TsАKhАL"}
		{"marksman(usa)"							"Marksman"}
		{"minmen(usa)"								"Grenadier"}
		{"officer(usa)"								"Officer"}
		{"scouts(usa)"								"Scout"}
		{"smgs(usa)"								"Infantry"}
		{"snipers(usa)"								"Sniper team"}
		{"stormtroopers2(usa)"						"Marines"}
;________________________________________________________________________________________________________
;other
;________________________________________________________________________________________________________
