		{"special"
			{"ger"
				{"spy1" "Peter German"}
				{"spy2" "Torsten Shafer"}
			}
			{"hint" "Hint"}
		}
		{"mp"

		}
               
		{"mp2"
			{"rus"
				{"antipersonel_miner" "<c(FFFFFF)>AP miner<c(FFFFFF)>"}
				{"antitank_miner" "<c(FFFFFF)>AT miner<c(FFFFFF)>"}
				{"bazooker" "<c(FFFFFF)>AT infantry<c(FFFFFF)>"}
				{"bazooker2" "<c(FFFFFF)>AT infantry<c(FFFFFF)>"}
				{"bazooker2_help" "<c(FFFFFF)>Assistant for AT infantry<c(FFFFFF)>"}
				{"engineer" "<c(FFFFFF)>injener<c(FFFFFF)>"}
				{"engineer2" "<c(FFFFFF)>injener<c(FFFFFF)>"}
				{"flamer" "<c(FFFFFF)>ognemetchik<c(FFFFFF)>"}
				{"flamer2" "<c(FFFFFF)>ognemetchik<c(FFFFFF)>"}
				{"mgun" "<c(FFFFFF)>pulemetchik<c(FFFFFF)>"}
				{"oficer" "<c(FFFFFF)>ofitser<c(FFFFFF)>"}
				{"nav" "<c(FFFFFF)>navodchik<c(FFFFFF)>"}
				{"pilot" "<c(FFFFFF)>Pilot<c(FFFFFF)>"}
				{"vertpilot" "<c(FFFFFF)>Heli pilot<c(FFFFFF)>"}
				{"saper" "<c(FFFFFF)>saper<c(FFFFFF)>"}
				{"scout" "<c(FFFFFF)>razvedchik<c(FFFFFF)>"}
				{"scout2" "<c(FFFFFF)>razvedchik<c(FFFFFF)>"}
				{"smg" "<c(FFFFFF)>soldat<c(FFFFFF)>"}
				{"sniper" "<c(FFFFFF)>snajper<c(FFFFFF)>"}
				{"omon" "<c(FFFFFF)>omon<c(FFFFFF)>"}
				{"omon2" "<c(FFFFFF)>omon<c(FFFFFF)>"}
				{"omon3" "<c(FFFFFF)>omon<c(FFFFFF)>"}
				{"minmen" "<c(FFFFFF)>Grenadier<c(FFFFFF)>"}
				{"tankman" "<c(FFFFFF)>Tankman<c(FFFFFF)>"}
				{"tankman2" "<c(FFFFFF)>Tankman<c(FFFFFF)>"}
				{"tankman3" "<c(FFFFFF)>Tankman<c(FFFFFF)>"}
				{"vehicle_supporter" "<c(FFFFFF)>Operator<c(FFFFFF)>"}
				{"at_rifle" "<c(FFFFFF)>tjaj. snajper<c(FFFFFF)>"}
				{"pzrk" "<c(FFFFFF)>MANPAD operator<c(FFFFFF)>"}
				{"pzrkhelp" "<c(FFFFFF)>MANPAD operator 2nd<c(FFFFFF)>"}

				{"morspec_com" "<c(FFFFFF)>Squad com<c(FFFFFF)>"}
				{"morspec_mgun2" "<c(FFFFFF)>Machinegunner<c(FFFFFF)>"}
				{"morspec_mgun" "<c(FFFFFF)>Machinegunner<c(FFFFFF)>"}
				{"morspec_sniper1" "<c(FFFFFF)>Sniper<c(FFFFFF)>"}
				{"morspec_rpg" "<c(FFFFFF)>AT infantry<c(FFFFFF)>"}
				{"morspec_rpghelp" "<c(FFFFFF)>Assistantfor AT infantry<c(FFFFFF)>"}
				{"morspec_smg" "<c(FFFFFF)>Soldier<c(FFFFFF)>"}
				{"morspec_smg2" "<c(FFFFFF)>Soldier<c(FFFFFF)>"}
				{"morspec_smg3" "<c(FFFFFF)>Soldier<c(FFFFFF)>"}
				{"morspec_sniper" "<c(FFFFFF)>Sniper<c(FFFFFF)>"}
				{"morspec_zamcom" "<c(FFFFFF)>Sergeant<c(FFFFFF)>"}

				{"gru_com" "<c(FFFFFF)>Squad com<c(FFFFFF)>"}
				{"gru_mgun2" "<c(FFFFFF)>Scout-pulemetchik<c(FFFFFF)>"}
				{"gru_mgun" "<c(FFFFFF)>Scout-pulemetchik<c(FFFFFF)>"}
				{"gru_radio" "<c(FFFFFF)>Scout-radist<c(FFFFFF)>"}
				{"gru_rpg" "<c(FFFFFF)>Scout-grenade launcherchik<c(FFFFFF)>"}
				{"gru_rpghelp" "<c(FFFFFF)>Scout-grenade launcherchik<c(FFFFFF)>"}
				{"gru_smg" "<c(FFFFFF)>Scout-strelok<c(FFFFFF)>"}
				{"gru_smg2" "<c(FFFFFF)>Scout-strelok<c(FFFFFF)>"}
				{"gru_smg3" "<c(FFFFFF)>Scout-strelok<c(FFFFFF)>"}
				{"gru_sniper" "<c(FFFFFF)>Scout-snajper<c(FFFFFF)>"}
				{"gru_zamcom" "<c(FFFFFF)>Starshij razvedchik<c(FFFFFF)>"}
				{"gru_com_art" "<c(FFFFFF)>Spotter<c(FFFFFF)>"}

				{"mor_com" "<c(FFFFFF)>Squad com<c(FFFFFF)>"}
				{"mor_mgun2" "<c(FFFFFF)>Machinegunner<c(FFFFFF)>"}
				{"mor_mgun" "<c(FFFFFF)>Machinegunner<c(FFFFFF)>"}
				{"mor_mgunhelp" "<c(FFFFFF)>Assistantfor machinegunner<c(FFFFFF)>"}
				{"mor_radio" "<c(FFFFFF)>Radioman<c(FFFFFF)>"}
				{"mor_rpg" "<c(FFFFFF)>AT infantry<c(FFFFFF)>"}
				{"mor_rpghelp" "<c(FFFFFF)>Assistantfor AT infantry<c(FFFFFF)>"}
				{"mor_smg4" "<c(FFFFFF)>Flamer<c(FFFFFF)>"}
				{"mor_smg2" "<c(FFFFFF)>Soldier<c(FFFFFF)>"}
				{"mor_smg3" "<c(FFFFFF)>Soldier<c(FFFFFF)>"}
				{"mor_sniper" "<c(FFFFFF)>Sniper<c(FFFFFF)>"}
				{"mor_zamcom" "<c(FFFFFF)>Sergeant<c(FFFFFF)>"}
				{"mor_at_rifle" "<c(FFFFFF)>tjaj. snajper<c(FFFFFF)>"}

				{"mso_com" "<c(FFFFFF)>Squad com<c(FFFFFF)>"}
				{"mso_mgun" "<c(FFFFFF)>Machinegunner<c(FFFFFF)>"}
				{"mso_mgunhelp" "<c(FFFFFF)>Assistantfor machinegunner<c(FFFFFF)>"}
				{"mso_radio" "<c(FFFFFF)>Radioman<c(FFFFFF)>"}
				{"mso_rpg" "<c(FFFFFF)>AT infantry<c(FFFFFF)>"}
				{"mso_rpghelp" "<c(FFFFFF)>Assistantfor AT infantry<c(FFFFFF)>"}
				{"mso_smg" "<c(FFFFFF)>Soldier<c(FFFFFF)>"}
				{"mso_smg2" "<c(FFFFFF)>Soldier<c(FFFFFF)>"}
				{"mso_sniper" "<c(FFFFFF)>Sniper<c(FFFFFF)>"}

				{"spec_com" "<c(FFFFFF)>Squad com<c(FFFFFF)>"}
				{"spec_flamer" "<c(FFFFFF)>Flamer<c(FFFFFF)>"}
				{"spec_mgun" "<c(FFFFFF)>Machinegunner<c(FFFFFF)>"}
				{"spec_radio" "<c(FFFFFF)>Radioman<c(FFFFFF)>"}
				{"spec_rpg" "<c(FFFFFF)>AT infantry<c(FFFFFF)>"}
				{"spec_rpghelp" "<c(FFFFFF)>Assistantfor AT infantry<c(FFFFFF)>"}
				{"spec_smg" "<c(FFFFFF)>Soldier<c(FFFFFF)>"}
				{"spec_smg2" "<c(FFFFFF)>Soldier<c(FFFFFF)>"}
				{"spec_zamcom" "<c(FFFFFF)>Sergeant<c(FFFFFF)>"}
				{"spec_sniper" "<c(FFFFFF)>Sniper<c(FFFFFF)>"}
				

				{"vdv_com" "<c(FFFFFF)>Squad com<c(FFFFFF)>"}
				{"vdv_mgun" "<c(FFFFFF)>Machinegunner<c(FFFFFF)>"}
				{"vdv_radio" "<c(FFFFFF)>Radioman<c(FFFFFF)>"}
				{"vdv_rpg" "<c(FFFFFF)>AT infantry<c(FFFFFF)>"}
				{"vdv_rpghelp" "<c(FFFFFF)>Assistantfor AT infantry<c(FFFFFF)>"}
				{"vdv_smg" "<c(FFFFFF)>Soldier<c(FFFFFF)>"}
				{"vdv_smg2" "<c(FFFFFF)>Soldier<c(FFFFFF)>"}
				{"vdv_zamcom" "<c(FFFFFF)>Sergeant<c(FFFFFF)>"}
				{"vdv_sniper" "<c(FFFFFF)>Sniper<c(FFFFFF)>"}
				{"vdv_tankman" "<c(FFFFFF)>Tankman<c(FFFFFF)>"}
				{"vdv_tankman2" "<c(FFFFFF)>Tankman<c(FFFFFF)>"}

				{"morpeh_sniper" "<c(FFFFFF)>Sniper for marines<c(FFFFFF)>"}
				{"morpeh_spotter" "<c(FFFFFF)>Spotter<c(FFFFFF)>"}
				{"motostrelk_sniper" "<c(FFFFFF)>Sniper<c(FFFFFF)>"}
				{"motostrelk_spotter" "<c(FFFFFF)>Spotter<c(FFFFFF)>"}

				{"scout_mso_com" "<c(FFFFFF)>Scout<c(FFFFFF)>"}
				{"scout_mso_mgun" "<c(FFFFFF)>Scout<c(FFFFFF)>"}
				{"scout_mso_smg" "<c(FFFFFF)>Scout<c(FFFFFF)>"}
				{"scout_mso_smg2" "<c(FFFFFF)>Scout<c(FFFFFF)>"}
				{"scout_mso_sniper" "<c(FFFFFF)>Scout<c(FFFFFF)>"}
            }
			{"usa"
				{"antipersonel_miner" "<c(FFFFFF)>AP miner<c(FFFFFF)>"}
				{"antitank_miner" "<c(FFFFFF)>AT miner<c(FFFFFF)>"}
				{"bazooker" "<c(FFFFFF)>AT infantry<c(FFFFFF)>"}
				{"bazooker2" "<c(FFFFFF)>AT infantry<c(FFFFFF)>"}
				{"engineer" "<c(FFFFFF)>Engineer<c(FFFFFF)>"}
				{"flamer" "<c(FFFFFF)>Flamer<c(FFFFFF)>"}
				{"mgun" "<c(FFFFFF)>Machinegunner<c(FFFFFF)>"}
				{"oficer" "<c(FFFFFF)>Officer<c(FFFFFF)>"}
				{"pilot" "<c(FFFFFF)>Pilot<c(FFFFFF)>"}
				{"vertpilot" "<c(FFFFFF)>Heli pilot<c(FFFFFF)>"}
				{"vertpilot_apache" "<c(FFFFFF)>Heli pilot<c(FFFFFF)>"}
				{"vertpilot_viper" "<c(FFFFFF)>Heli pilot<c(FFFFFF)>"}
				{"saper" "<c(FFFFFF)>Sapper<c(FFFFFF)>"}
				{"scout" "<c(FFFFFF)>Scout<c(FFFFFF)>"}
				{"at_rifle" "<c(FFFFFF)>Heavy snajper<c(FFFFFF)>"}
				{"smg" "<c(FFFFFF)>Soldier<c(FFFFFF)>"}
				{"sniper" "<c(FFFFFF)>Sniper<c(FFFFFF)>"}
				{"sniper1" "<c(FFFFFF)>Sniper<c(FFFFFF)>"}
				{"vdv" "<c(FFFFFF)>Navy SEAL<c(FFFFFF)>"}
				{"minmen" "<c(FFFFFF)>Grenadier<c(FFFFFF)>"}
				{"tankman" "<c(FFFFFF)>Tankman<c(FFFFFF)>"}
				{"tankman2" "<c(FFFFFF)>Tankman<c(FFFFFF)>"}
				{"tankman3" "<c(FFFFFF)>Tankman<c(FFFFFF)>"}
				{"vehicle_supporter" "<c(FFFFFF)>Operator<c(FFFFFF)>"}
				{"vehicle_supporter1" "<c(FFFFFF)>Driver<c(FFFFFF)>"}
				{"vehicle_supporter2" "<c(FFFFFF)>Driver<c(FFFFFF)>"}
				{"vehicle_supporter3" "<c(FFFFFF)>Driver<c(FFFFFF)>"}
				{"pzrk" "<c(FFFFFF)>MANPAD operator<c(FFFFFF)>"}
				{"pzrkhelp" "<c(FFFFFF)>MANPAD operator 2nd<c(FFFFFF)>"}
				{"pzrk_new" "<c(FFFFFF)>MANPAD operator<c(FFFFFF)>"}
				{"pzrkhelp_new" "<c(FFFFFF)>MANPAD operator 2nd<c(FFFFFF)>"}
				{"smg2" "<c(FFFFFF)>Soldier<c(FFFFFF)>"}
				{"smg3" "<c(FFFFFF)>Soldier<c(FFFFFF)>"}
				{"vdv2" "<c(FFFFFF)>Navy SEAL<c(FFFFFF)>"}
				{"vdv3" "<c(FFFFFF)>Navy SEAL<c(FFFFFF)>"}
				{"vdv4" "<c(FFFFFF)>Navy SEAL<c(FFFFFF)>"}
				{"defend" "<c(FFFFFF)>Delta<c(FFFFFF)>"}
				{"defend2" "<c(FFFFFF)>Delta<c(FFFFFF)>"}
				{"defend3" "<c(FFFFFF)>Delta<c(FFFFFF)>"}
				{"defend4" "<c(FFFFFF)>Delta<c(FFFFFF)>"}
				{"defend5" "<c(FFFFFF)>Delta<c(FFFFFF)>"}

				{"defend_com" "<c(FFFFFF)>Delta<c(FFFFFF)>"}
				{"defend_mgun" "<c(FFFFFF)>Delta<c(FFFFFF)>"}

				{"delta_bazooker" "<c(FFFFFF)>AT infantry Delta Force<c(FFFFFF)>"}
				{"delta_com" "<c(FFFFFF)>Squad com Delta Force<c(FFFFFF)>"}
				{"delta_marksman" "<c(FFFFFF)>Sniper Delta Force<c(FFFFFF)>"}
				{"delta_mgun" "<c(FFFFFF)>Machinegunner Delta Force<c(FFFFFF)>"}
				{"delta_smg" "<c(FFFFFF)>Operator Delta Force<c(FFFFFF)>"}
				{"delta_smg2" "<c(FFFFFF)>Operator Delta Force<c(FFFFFF)>"}
				{"delta_smg3" "<c(FFFFFF)>Operator Delta Force<c(FFFFFF)>"}

				{"navyseal_bazooker" "<c(FFFFFF)>AT infantry Navy Seal<c(FFFFFF)>"}
				{"navyseal_com" "<c(FFFFFF)>Squad com Navy Seal<c(FFFFFF)>"}
				{"navyseal_marksman" "<c(FFFFFF)>Sniper Navy Seal<c(FFFFFF)>"}
				{"navyseal_mgun" "<c(FFFFFF)>Operator Navy Seal<c(FFFFFF)>"}
				{"navyseal_smg" "<c(FFFFFF)>Operator Navy Seal<c(FFFFFF)>"}
				{"navyseal_smg2" "<c(FFFFFF)>Operator Navy Seal<c(FFFFFF)>"}
				{"navyseal_smg3" "<c(FFFFFF)>Operator Navy Seal<c(FFFFFF)>"}

				{"elite_com" "<c(FFFFFF)>Squad com<c(FFFFFF)>"}
				{"elite_snip" "<c(FFFFFF)>Sniper<c(FFFFFF)>"}
				{"oficer_smg" "<c(FFFFFF)>Officer<c(FFFFFF)>"}
				{"sailor" "<c(FFFFFF)>Sailor<c(FFFFFF)>"}
				{"sailor1" "<c(FFFFFF)>Sailor<c(FFFFFF)>"}
				{"sailor2" "<c(FFFFFF)>Sailor<c(FFFFFF)>"}
				{"smg_bazooker" "<c(FFFFFF)>AT infantry<c(FFFFFF)>"}
				{"smg_gren" "<c(FFFFFF)>Soldier<c(FFFFFF)>"}
				{"smg_helpmgun" "<c(FFFFFF)>Assistant for machinegunner<c(FFFFFF)>"}
				{"smg_marksman" "<c(FFFFFF)>Marksman<c(FFFFFF)>"}
				{"smg_mgun" "<c(FFFFFF)>Machinegunner<c(FFFFFF)>"}
				{"smg_new" "<c(FFFFFF)>Shooter<c(FFFFFF)>"}
				{"smg_newcom" "<c(FFFFFF)>Kom. Fire Team<c(FFFFFF)>"}
				{"smg_jav" "<c(FFFFFF)>Operator FGM-148 Javelin<c(FFFFFF)>"}
				{"smg_helpjav" "<c(FFFFFF)>Assistantoperator's FGM-148 Javelin<c(FFFFFF)>"}

				{"tankman_new" "<c(FFFFFF)>Tankman<c(FFFFFF)>"}

				{"usara_com" "<c(FFFFFF)>Fire team com<c(FFFFFF)>"}
				{"usara_grenade" "<c(FFFFFF)>Ranger<c(FFFFFF)>"}
				{"usara_bazooker" "<c(FFFFFF)>Operator FGM-148 Javelin<c(FFFFFF)>"}
				{"usara_heavy_mgun" "<c(FFFFFF)>Machinegunner<c(FFFFFF)>"}
				{"usara_at_rifle" "<c(FFFFFF)>Heavy snajper<c(FFFFFF)>"}
				{"usara_helpbazooker" "<c(FFFFFF)>Assistant operator's FGM-148 Javelin<c(FFFFFF)>"}
				{"usara_help_mgun" "<c(FFFFFF)>Assistantfor machinegunner<c(FFFFFF)>"}
				{"usara_light_mgun" "<c(FFFFFF)>Machinegunner<c(FFFFFF)>"}
				{"usara_smg" "<c(FFFFFF)>Ranger<c(FFFFFF)>"}
				{"usara_spotter" "<c(FFFFFF)>Spotter<c(FFFFFF)>"}
				{"usara_xm25" "<c(FFFFFF)>Sniper grenadier<c(FFFFFF)>"}

				{"usmc_com" "<c(FFFFFF)>Fire team com<c(FFFFFF)>"}
				{"usmc_heavy_mgun" "<c(FFFFFF)>Machinegunner<c(FFFFFF)>"}
				{"usmc_help_heavy_mgun" "<c(FFFFFF)>Assistantfor machinegunner<c(FFFFFF)>"}
				{"usmc_light_mgun" "<c(FFFFFF)>Machinegunner<c(FFFFFF)>"}
				{"usmc_zamcom" "<c(FFFFFF)>Sharpshooter<c(FFFFFF)>"}
				{"usmc_bazooker" "<c(FFFFFF)>AT infantry<c(FFFFFF)>"}
				{"usmc_bazooker_jav" "<c(FFFFFF)>Operator FGM-148 Javelin<c(FFFFFF)>"}
				{"usmc_bazooker_jav_support" "<c(FFFFFF)>Assistantoperator's FGM-148 Javelin<c(FFFFFF)>"}
				{"usmc_sraw" "<c(FFFFFF)>AT infantry<c(FFFFFF)>"}
				{"usmc_marksman" "<c(FFFFFF)>Marksman<c(FFFFFF)>"}
				{"usmc_medic" "<c(FFFFFF)>Medic<c(FFFFFF)>"}
				{"usmc_saper" "<c(FFFFFF)>Sapper<c(FFFFFF)>"}
				{"usmc_smg" "<c(FFFFFF)>Shooter<c(FFFFFF)>"}
;===============================================================
				{"us_army_sniper" "<c(FFFFFF)>Sniper US Army<c(FFFFFF)>"}
				{"us_army_spotter" "<c(FFFFFF)>Spotter<c(FFFFFF)>"}
				{"usmc_sniper" "<c(FFFFFF)>Sniper USMC<c(FFFFFF)>"}
				{"usmc_spotter" "<c(FFFFFF)>Spotter<c(FFFFFF)>"}
				{"usmc_smg2" "<c(FFFFFF)>Shooter<c(FFFFFF)>"}
				{"usmc_heavy_sniper" "<c(FFFFFF)>Heavy snajper<c(FFFFFF)>"}
				{"operator_bpla" "<c(FFFFFF)>Operator UAV<c(FFFFFF)>"}
				
				{"2smg_bazooker" "<c(FFFFFF)>AT infantry<c(FFFFFF)>"}
				{"2smg_bazooker2" "<c(FFFFFF)>AT infantry<c(FFFFFF)>"}
				{"2smg_heavy_mgun" "<c(FFFFFF)>Machinegunner<c(FFFFFF)>"}
				{"2smg_gren" "<c(FFFFFF)>Grenadier<c(FFFFFF)>"}
				{"2smg_help_bazooker2" "<c(FFFFFF)>Assistantfor AT infantry<c(FFFFFF)>"}
				{"2smg_helpmgun" "<c(FFFFFF)>Assistantfor machinegunner<c(FFFFFF)>"}
				{"2smg_marksman" "<c(FFFFFF)>Marksman<c(FFFFFF)>"}
				{"2smg_mgun" "<c(FFFFFF)>Machinegunner<c(FFFFFF)>"}
				{"2smg_new" "<c(FFFFFF)>Shooter<c(FFFFFF)>"}
				{"2smg_newcom" "<c(FFFFFF)>Fire team com<c(FFFFFF)>"}
				
				{"delta_bazooker_sso" "<c(FFFFFF)>AT infantry Delta Force<c(FFFFFF)>"}
				{"delta_com_sso" "<c(FFFFFF)>Squad com Delta Force<c(FFFFFF)>"}
				{"delta_marksman_sso" "<c(FFFFFF)>Sniper Delta Force<c(FFFFFF)>"}
				{"delta_mgun_sso" "<c(FFFFFF)>Machinegunner Delta Force<c(FFFFFF)>"}
				{"delta_smg_sso" "<c(FFFFFF)>Operator Delta Force<c(FFFFFF)>"}
				{"delta_smg2_sso" "<c(FFFFFF)>Operator Delta Force<c(FFFFFF)>"}

				{"navyseal_com_art" "<c(FFFFFF)>Squad com Navy Seal<c(FFFFFF)>"}
				{"navyseal_marksman_art" "<c(FFFFFF)>Sniper Navy Seal<c(FFFFFF)>"}
				{"navyseal_smg_art" "<c(FFFFFF)>Operator Navy Seal<c(FFFFFF)>"}

				{"tankman_usmc" "<c(FFFFFF)>Tankman<c(FFFFFF)>"}
				{"tankman_usmc2" "<c(FFFFFF)>Tankman<c(FFFFFF)>"}
				{"tankman_usmc3" "<c(FFFFFF)>Tankman<c(FFFFFF)>"}

				{"vehicle_supporter_usmc" "<c(FFFFFF)>Operator<c(FFFFFF)>"}
			}
			{"idf"
				{"pilot" "<c(FFFFFF)>Pilot<c(FFFFFF)>"}
				{"scout" "<c(FFFFFF)>Scout<c(FFFFFF)>"}
				{"tankman" "<c(FFFFFF)>Tankman<c(FFFFFF)>"}
				{"tankman2" "<c(FFFFFF)>Tankman<c(FFFFFF)>"}
				{"tankman3" "<c(FFFFFF)>Tankman<c(FFFFFF)>"}
				{"vehicle_supporter" "<c(FFFFFF)>Operator<c(FFFFFF)>"}
				{"idf_bazooker" "<c(FFFFFF)>AT infantry<c(FFFFFF)>"}
				{"idf_bazooker2" "<c(FFFFFF)>AT infantry<c(FFFFFF)>"}
				{"idf_com" "<c(FFFFFF)>Squad com<c(FFFFFF)>"}
				{"idf_marksman" "<c(FFFFFF)>Marksman<c(FFFFFF)>"}
				{"idf_mgun" "<c(FFFFFF)>Machinegunner<c(FFFFFF)>"}
				{"idf_smg" "<c(FFFFFF)>Shooter<c(FFFFFF)>"}
				{"idf_smg2" "<c(FFFFFF)>Shooter<c(FFFFFF)>"}
				{"idf_at_rifle" "<c(FFFFFF)>Heavy snajper<c(FFFFFF)>"}
				{"idf_hmgun" "<c(FFFFFF)>Machinegunner<c(FFFFFF)>"}
				{"idf_hmgun_help" "<c(FFFFFF)>Assistantfor machinegunner<c(FFFFFF)>"}
				{"idf_sniper" "<c(FFFFFF)>Sniper<c(FFFFFF)>"}
				{"idf_spotter" "<c(FFFFFF)>Spotter<c(FFFFFF)>"}
				{"sayeret_matkal_bazooker" "<c(FFFFFF)>AT infantry Sayeret Matkal<c(FFFFFF)>"}
				{"sayeret_matkal_bazooker2" "<c(FFFFFF)>AT infantry Sayeret Matkal<c(FFFFFF)>"}
				{"sayeret_matkal_com" "<c(FFFFFF)>Squad com Sayeret Matkal<c(FFFFFF)>"}
				{"sayeret_matkal_heavy_mgun" "<c(FFFFFF)>Machinegunner Sayeret Matkal<c(FFFFFF)>"}
				{"sayeret_matkal_marksman" "<c(FFFFFF)>Marksman Sayeret Matkal<c(FFFFFF)>"}
				{"sayeret_matkal_mgun" "<c(FFFFFF)>Machinegunner Sayeret Matkal<c(FFFFFF)>"}
				{"sayeret_matkal_smg" "<c(FFFFFF)>Shooter Sayeret Matkal<c(FFFFFF)>"}
				{"sayeret_matkal_smg2" "<c(FFFFFF)>Shooter Sayeret Matkal<c(FFFFFF)>"}

			}
            {"frg"
				{"frg_com" "<c(FFFFFF)>Squad com<c(FFFFFF)>"}
				{"frg_gren" "<c(FFFFFF)>Grenadier<c(FFFFFF)>"}
				{"frg_light_mgun" "<c(FFFFFF)>Machinegunner<c(FFFFFF)>"}
				{"frg_medic" "<c(FFFFFF)>Medic<c(FFFFFF)>"}
				{"frg_mgun" "<c(FFFFFF)>Machinegunner<c(FFFFFF)>"}
				{"frg_mgunhelp" "<c(FFFFFF)>Assistantfor machinegunner<c(FFFFFF)>"}
				{"engineer" "<c(FFFFFF)>Engineer<c(FFFFFF)>"}
				{"tankman" "<c(FFFFFF)>Tankman<c(FFFFFF)>"}
				{"tankman2" "<c(FFFFFF)>Tankman<c(FFFFFF)>"}
				{"tankman3" "<c(FFFFFF)>Tankman<c(FFFFFF)>"}
				{"frg_rifleman" "<c(FFFFFF)>Shooter<c(FFFFFF)>"}
				{"frg_rpg" "<c(FFFFFF)>AT infantry<c(FFFFFF)>"}
				{"frg_rpghelp" "<c(FFFFFF)>Assistantfor AT infantry<c(FFFFFF)>"}
				{"frg_rpghelp2" "<c(FFFFFF)>Operator SPIKE-SR<c(FFFFFF)>"}
				{"frg_heavy_sniper" "<c(FFFFFF)>Heavy snajper<c(FFFFFF)>"}
				{"frg_heavy_sniper_spotter" "<c(FFFFFF)>Spotter<c(FFFFFF)>"}
				{"frg_sniper" "<c(FFFFFF)>Sniper<c(FFFFFF)>"}
				{"frg_spotter" "<c(FFFFFF)>Spotter<c(FFFFFF)>"}
				{"ksk_com" "<c(FFFFFF)>Squad com KSK<c(FFFFFF)>"}
				{"ksk_smg3" "<c(FFFFFF)>Operator KSK<c(FFFFFF)>"}
				{"ksk_mgun" "<c(FFFFFF)>Machinegunner KSK<c(FFFFFF)>"}
				{"scout" "<c(FFFFFF)>Scout-diversant<c(FFFFFF)>"}
				{"ksk_smg" "<c(FFFFFF)>Operator KSK<c(FFFFFF)>"}
				{"ksk_smg2" "<c(FFFFFF)>Operator KSK<c(FFFFFF)>"}
				{"ksk_rpg" "<c(FFFFFF)>AT infantry KSK<c(FFFFFF)>"}
				{"ksk_marksman" "<c(FFFFFF)>Sniper KSK<c(FFFFFF)>"}
				{"spec_ksk" "<c(FFFFFF)>Soldier<c(FFFFFF)>"}	
				{"pilot" "<c(FFFFFF)>Pilot<c(FFFFFF)>"}	
				{"vehicle_supporter" "<c(FFFFFF)>Operator<c(FFFFFF)>"}	
				{"frg_operator_bpla" "<c(FFFFFF)>Operator UAV<c(FFFFFF)>"}				
				{"gren_ksk" "<c(FFFFFF)>Grenadier KSK<c(FFFFFF)>"}				
				{"ksk_com_art" "<c(FFFFFF)>Squad com KSK<c(FFFFFF)>"}				
				{"ksk_com_sso" "<c(FFFFFF)>Squad com KSK<c(FFFFFF)>"}				
				{"ksk_marksman_art" "<c(FFFFFF)>Marksman KSK<c(FFFFFF)>"}				
				{"ksk_marksman_sso" "<c(FFFFFF)>Marksman KSK<c(FFFFFF)>"}				
				{"ksk_mgun_sso" "<c(FFFFFF)>Machinegunner KSK<c(FFFFFF)>"}				
				{"ksk_rpg_sso" "<c(FFFFFF)>AT infantry KSK<c(FFFFFF)>"}				
				{"ksk_smg_art" "<c(FFFFFF)>Operator KSK<c(FFFFFF)>"}				
				{"ksk_smg_sso" "<c(FFFFFF)>Operator KSK<c(FFFFFF)>"}				
				{"ksk_smg2_sso" "<c(FFFFFF)>Operator KSK<c(FFFFFF)>"}				
				{"ksk_smg3_sso" "<c(FFFFFF)>Operator KSK<c(FFFFFF)>"}				
				{"marksman_ksk" "<c(FFFFFF)>Marksman KSK<c(FFFFFF)>"}				
				{"medik_ksk" "<c(FFFFFF)>Sanitar KSK<c(FFFFFF)>"}				
				{"recon_ksk" "<c(FFFFFF)>Scout KSK<c(FFFFFF)>"}				
				{"mgun_ksk" "<c(FFFFFF)>Machinegunner KSK<c(FFFFFF)>"}				
				{"oficer" "<c(FFFFFF)>Officer<c(FFFFFF)>"}
				{"pzrk" "<c(FFFFFF)>MANPAD operator<c(FFFFFF)>"}
				{"saper" "<c(FFFFFF)>Sapper<c(FFFFFF)>"}
				{"vertpilot" "<c(FFFFFF)>Heli pilot<c(FFFFFF)>"}
			}
			{"fr"
				{"fr_com" "<c(FFFFFF)>Squad com<c(FFFFFF)>"}
				{"fr_gren" "<c(FFFFFF)>Grenadier<c(FFFFFF)>"}
				{"fr_light_mgun" "<c(FFFFFF)>Machinegunner<c(FFFFFF)>"}
				{"fr_heavy_mgun" "<c(FFFFFF)>Machinegunner<c(FFFFFF)>"}
				{"fr_heavy_mgun_help" "<c(FFFFFF)>Assistantfor machinegunner<c(FFFFFF)>"}
				{"fr_marksman" "<c(FFFFFF)>Marksman<c(FFFFFF)>"}
				{"fr_smg" "<c(FFFFFF)>Soldier<c(FFFFFF)>"}
				{"fr_smg2" "<c(FFFFFF)>Soldier<c(FFFFFF)>"}
				{"fr_bazooker" "<c(FFFFFF)>AT infantry<c(FFFFFF)>"}
				{"fr_rpghelp" "<c(FFFFFF)>Assistantgranatometchika<c(FFFFFF)>"}
				{"fr_eryx" "<c(FFFFFF)>Operator ATGM<c(FFFFFF)>"}
				{"fr_eryx_help" "<c(FFFFFF)>Pom.operator's ATGM<c(FFFFFF)>"}
				{"tankman" "<c(FFFFFF)>Tankman<c(FFFFFF)>"}
				{"tankman2" "<c(FFFFFF)>Tankman<c(FFFFFF)>"}
				{"tankman3" "<c(FFFFFF)>Tankman<c(FFFFFF)>"}
				{"fr_at_rifle" "<c(FFFFFF)>Antisniper<c(FFFFFF)>"}
				{"fr_at_rifle_spotter" "<c(FFFFFF)>Spotter<c(FFFFFF)>"}
				{"vehicle_supporter" "<c(FFFFFF)>Operator<c(FFFFFF)>"}
				{"fr_vehicle_supporter" "<c(FFFFFF)>Operator<c(FFFFFF)>"}
				{"saper" "<c(FFFFFF)>Sapper<c(FFFFFF)>"}
				{"1er_rpima_fr_bazooker" "<c(FFFFFF)>AT infantry 1ER Rpima<c(FFFFFF)>"}
				{"1er_rpima_fr_com" "<c(FFFFFF)>Squad com 1ER Rpima<c(FFFFFF)>"}
				{"1er_rpima_fr_gren" "<c(FFFFFF)>Grenadier 1ER Rpima<c(FFFFFF)>"}
				{"1er_rpima_fr_heavy_mgun" "<c(FFFFFF)>Machinegunner 1ER Rpima<c(FFFFFF)>"}
				{"1er_rpima_fr_light_mgun" "<c(FFFFFF)>Machinegunner 1ER Rpima<c(FFFFFF)>"}
				{"1er_rpima_fr_marksman" "<c(FFFFFF)>Marksman 1ER Rpima<c(FFFFFF)>"}
				{"1er_rpima_fr_smg" "<c(FFFFFF)>Shooter 1ER Rpima<c(FFFFFF)>"}
				{"1er_rpima_fr_smg2" "<c(FFFFFF)>Shooter 1ER Rpima<c(FFFFFF)>"}
				{"1er_rpima_fr_smg3" "<c(FFFFFF)>Shooter 1ER Rpima<c(FFFFFF)>"}
				{"1er_rpima_fr_zamcom" "<c(FFFFFF)>Sharpshooter 1ER Rpima<c(FFFFFF)>"}
				{"antipersonel_miner" "<c(FFFFFF)>AP miner<c(FFFFFF)>"}
				{"antitank_miner" "<c(FFFFFF)>AT miner<c(FFFFFF)>"}
				{"fr_scout" "<c(FFFFFF)>Scout<c(FFFFFF)>"}
				{"fr_scout_com" "<c(FFFFFF)>Scout<c(FFFFFF)>"}
				{"fr_scout_mgun" "<c(FFFFFF)>Scout<c(FFFFFF)>"}
				{"fr_scout_smg" "<c(FFFFFF)>Scout<c(FFFFFF)>"}
				{"vertpilot" "<c(FFFFFF)>Heli pilot<c(FFFFFF)>"}
				{"oficer" "<c(FFFFFF)>Officer<c(FFFFFF)>"}
			}
			{"hun"
				{"hun_bazooker" "<c(FFFFFF)>AT infantry<c(FFFFFF)>"}
				{"hun_rpghelp" "<c(FFFFFF)>Assistantgranatometchika<c(FFFFFF)>"}

			}
			{"brit"
				{"brit_at_rifle" "<c(FFFFFF)>Antisniper<c(FFFFFF)>"}
				{"brit_at_rifle_help" "<c(FFFFFF)>Spotter<c(FFFFFF)>"}
				{"brit_marksman" "<c(FFFFFF)>Marksman<c(FFFFFF)>"}
				{"brit_com" "<c(FFFFFF)>Squad com<c(FFFFFF)>"}
				{"brit_bazooker" "<c(FFFFFF)>AT infantry<c(FFFFFF)>"}
				{"brit_bazooker_help" "<c(FFFFFF)>Assistantfor AT infantry<c(FFFFFF)>"}
				{"brit_gren" "<c(FFFFFF)>Grenadier<c(FFFFFF)>"}
				{"brit_light_mgun" "<c(FFFFFF)>Machinegunner<c(FFFFFF)>"}
				{"brit_smg" "<c(FFFFFF)>Shooter<c(FFFFFF)>"}
				{"brit_sniper" "<c(FFFFFF)>Sniper<c(FFFFFF)>"}
				{"brit_spotter" "<c(FFFFFF)>Spotter<c(FFFFFF)>"}
				{"brit_heavy_mgun" "<c(FFFFFF)>Machinegunner<c(FFFFFF)>"}
                {"brit_jav" "<c(FFFFFF)>Operator FGM-148 Javelin<c(FFFFFF)>"}
                {"brit_javhelp" "<c(FFFFFF)>Assistant operator's FGM-148 Javelin<c(FFFFFF)>"}
				{"2sas_com" "<c(FFFFFF)>Squad com SAS<c(FFFFFF)>"}
				{"2sas_heavy_mgun" "<c(FFFFFF)>Machinegunner SAS<c(FFFFFF)>"}
				{"2sas_marksman" "<c(FFFFFF)>Marksman SAS<c(FFFFFF)>"}
				{"2sas_rocket_launcher" "<c(FFFFFF)>AT infantry SAS<c(FFFFFF)>"}
				{"2sas_smg" "<c(FFFFFF)>Shooter SAS<c(FFFFFF)>"}
				{"2sas_smg2" "<c(FFFFFF)>Shooter SAS<c(FFFFFF)>"}
				{"oficer" "<c(FFFFFF)>Officer<c(FFFFFF)>"}
				{"pilot" "<c(FFFFFF)>Pilot<c(FFFFFF)>"}	
				{"sas_bazooker" "<c(FFFFFF)>AT infantry SAS<c(FFFFFF)>"}
				{"sas_com" "<c(FFFFFF)>Squad com SAS<c(FFFFFF)>"}
				{"sas_heavy_mgun" "<c(FFFFFF)>Machinegunner SAS<c(FFFFFF)>"}
				{"sas_light_mgun" "<c(FFFFFF)>Machinegunner SAS<c(FFFFFF)>"}
				{"sas_marksman" "<c(FFFFFF)>Marksman SAS<c(FFFFFF)>"}
				{"sas_mgun" "<c(FFFFFF)>Machinegunner SAS<c(FFFFFF)>"}
				{"sas_rifleman" "<c(FFFFFF)>Shooter SAS<c(FFFFFF)>"}
				{"sas_rocket_launcher" "<c(FFFFFF)>Granatametchik SAS<c(FFFFFF)>"}
				{"sas_scout_bazooker" "<c(FFFFFF)>Diversant  SAS<c(FFFFFF)>"}
				{"sas_scout_com" "<c(FFFFFF)>Diversant  SAS<c(FFFFFF)>"}
				{"sas_scout_rifleman" "<c(FFFFFF)>Diversant  SAS<c(FFFFFF)>"}
				{"sas_smg" "<c(FFFFFF)>Shooter SAS<c(FFFFFF)>"}
				{"sas_smg2" "<c(FFFFFF)>Shooter SAS<c(FFFFFF)>"}
				{"sas_smg3" "<c(FFFFFF)>Shooter SAS<c(FFFFFF)>"}
				{"tankman" "<c(FFFFFF)>Tankman<c(FFFFFF)>"}
				{"tankman2" "<c(FFFFFF)>Tankman<c(FFFFFF)>"}
				{"tankman3" "<c(FFFFFF)>Tankman<c(FFFFFF)>"}
				{"vehicle_supporter" "<c(FFFFFF)>Operator<c(FFFFFF)>"}
				{"vertpilot" "<c(FFFFFF)>Heli pilot<c(FFFFFF)>"}
				{"vertpilot_apache" "<c(FFFFFF)>Heli pilot<c(FFFFFF)>"}
			}
            {"cz"
				{"cz_bazooker" "<c(FFFFFF)>AT infantry<c(FFFFFF)>"}
				{"cz_bazooker2" "<c(FFFFFF)>AT infantry<c(FFFFFF)>"}
				{"2cz_bazooker2" "<c(FFFFFF)>AT infantry<c(FFFFFF)>"}
				{"cz_rpghelp" "<c(FFFFFF)>Assistantgranatometchika<c(FFFFFF)>"}
				{"2cz_rpghelp" "<c(FFFFFF)>Assistantgranatometchika<c(FFFFFF)>"}
				{"cz_mgunhelper" "<c(FFFFFF)>Assistantfor machinegunner<c(FFFFFF)>"}
				{"cz_com" "<c(FFFFFF)>Squad com<c(FFFFFF)>"}
				{"cz_gren" "<c(FFFFFF)>Grenadier<c(FFFFFF)>"}
				{"cz_medic" "<c(FFFFFF)>Medic<c(FFFFFF)>"}
				{"cz_mgun" "<c(FFFFFF)>Machinegunner<c(FFFFFF)>"}
				{"cz_mgunhelper" "<c(FFFFFF)>Assistantfor machinegunner<c(FFFFFF)>"}
				{"cz_smg" "<c(FFFFFF)>Soldier<c(FFFFFF)>"}	
				{"cz_smg2" "<c(FFFFFF)>Soldier<c(FFFFFF)>"}	
				{"cz_sniper" "<c(FFFFFF)>Marksman<c(FFFFFF)>"}
				{"elite" "<c(FFFFFF)>Diversant<c(FFFFFF)>"}
				{"elite2" "<c(FFFFFF)>Machinegunner<c(FFFFFF)>"}
				{"elite3" "<c(FFFFFF)>Diversant<c(FFFFFF)>"}
				{"engineer" "<c(FFFFFF)>Engineer<c(FFFFFF)>"}
				{"oficer" "<c(FFFFFF)>Officer<c(FFFFFF)>"}
				{"pilot" "<c(FFFFFF)>Pilot<c(FFFFFF)>"}		
				{"pzrk_soldier" "<c(FFFFFF)>MANPAD operator<c(FFFFFF)>"}
				{"pzrk_help_soldier" "<c(FFFFFF)>MANPAD operator 2nd<c(FFFFFF)>"}
				{"pzrk" "<c(FFFFFF)>MANPAD operator<c(FFFFFF)>"}
				{"pzrkhelp" "<c(FFFFFF)>MANPAD operator 2nd<c(FFFFFF)>"}
				{"scout" "<c(FFFFFF)>Diversant<c(FFFFFF)>"}
				{"sniper_cz" "<c(FFFFFF)>Sniper<c(FFFFFF)>"}
				{"tankman" "<c(FFFFFF)>Tankman<c(FFFFFF)>"}
				{"tankman2" "<c(FFFFFF)>Tankman<c(FFFFFF)>"}
				{"tankman3" "<c(FFFFFF)>Tankman<c(FFFFFF)>"}
				{"vehicle_supporter" "<c(FFFFFF)>Operator<c(FFFFFF)>"}
			}
            {"pol"
				{"pol_borderguard" "<c(FFFFFF)>Borderguard<c(FFFFFF)>"}
				{"pol_bazooker" "<c(FFFFFF)>Operator FGM-148 Javelin<c(FFFFFF)>"}
				{"pol_rpghelp" "<c(FFFFFF)>Assistantgranatometchika<c(FFFFFF)>"}
				{"pol_com" "<c(FFFFFF)>Squad com<c(FFFFFF)>"}
				{"pol_gren" "<c(FFFFFF)>Grenadier<c(FFFFFF)>"}
				{"pol_medic" "<c(FFFFFF)>Medic<c(FFFFFF)>"}
				{"pol_mgun" "<c(FFFFFF)>Machinegunner<c(FFFFFF)>"}
				{"pol_mgunhelper" "<c(FFFFFF)>Assistantfor machinegunner<c(FFFFFF)>"}
				{"pol_rpg" "<c(FFFFFF)>AT infantry<c(FFFFFF)>"}
				{"pol_rpghelp" "<c(FFFFFF)>Assistant for AT infantry <c(FFFFFF)>"}
				{"pol_smg" "<c(FFFFFF)>Soldier<c(FFFFFF)>"}	
				{"pol_smg2" "<c(FFFFFF)>Soldier<c(FFFFFF)>"}	
				{"pol_sniper" "<c(FFFFFF)>Marksman<c(FFFFFF)>"}
				{"oficer" "<c(FFFFFF)>Officer<c(FFFFFF)>"}
				{"pilot" "<c(FFFFFF)>Pilot<c(FFFFFF)>"}		
				{"pzrk_soldier" "<c(FFFFFF)>MANPAD operator<c(FFFFFF)>"}
				{"pzrk_help_soldier" "<c(FFFFFF)>MANPAD operator 2nd<c(FFFFFF)>"}
				{"scout" "<c(FFFFFF)>Diversant<c(FFFFFF)>"}
				{"tankman" "<c(FFFFFF)>Tankman<c(FFFFFF)>"}
				{"tankman2" "<c(FFFFFF)>Tankman<c(FFFFFF)>"}
				{"tankman3" "<c(FFFFFF)>Tankman<c(FFFFFF)>"}
				{"vehicle_supporter" "<c(FFFFFF)>Operator<c(FFFFFF)>"}
			}
            {"cn"
				{"antipersonel_miner" "<c(FFFFFF)>AP miner<c(FFFFFF)>"}
				{"antitank_miner" "<c(FFFFFF)>AT miner<c(FFFFFF)>"}
				{"at_rifle" "<c(FFFFFF)>Heavy snajper<c(FFFFFF)>"}
				{"bazooker2" "<c(FFFFFF)>AT infantry<c(FFFFFF)>"}
				{"bazooker2_help" "<c(FFFFFF)>Assistant for AT infantry<c(FFFFFF)>"}
			
				{"elite_com" "<c(FFFFFF)>Squad com for specnaz 82nd Group Army<c(FFFFFF)>"}
				{"elite_mgun" "<c(FFFFFF)>Machinegunner for specnaz 82nd Group Army<c(FFFFFF)>"}
				{"elite_rpg" "<c(FFFFFF)>AT infantry for specnaz 82nd Group Army<c(FFFFFF)>"}
				{"elite_rpghelp" "<c(FFFFFF)>Assistant for AT infantry for specnaz 82nd Group Army<c(FFFFFF)>"}
				{"elite_smg" "<c(FFFFFF)>Shooter for specnaz 82nd Group Army<c(FFFFFF)>"}
				{"elite_smg2" "<c(FFFFFF)>Shooter for specnaz 82nd Group Army<c(FFFFFF)>"}
				{"elite_sniper" "<c(FFFFFF)>Sniper for specnaz 82nd Group Army<c(FFFFFF)>"}
				{"engineer" "<c(FFFFFF)>Engineer<c(FFFFFF)>"}
				{"engineer2" "<c(FFFFFF)>Engineer<c(FFFFFF)>"}
				{"flamer" "<c(FFFFFF)>Flamer<c(FFFFFF)>"}

				{"mso_com" "<c(FFFFFF)>Squad com<c(FFFFFF)>"}
				{"mso_medic" "<c(FFFFFF)>Sanitar<c(FFFFFF)>"}
				{"mso_mgun" "<c(FFFFFF)>Machinegunner<c(FFFFFF)>"}
				{"mso_rpg" "<c(FFFFFF)>AT infantry<c(FFFFFF)>"}
				{"mso_rpghelp" "<c(FFFFFF)>Assistantfor AT infantry<c(FFFFFF)>"}
				{"mso_smg" "<c(FFFFFF)>Soldier<c(FFFFFF)>"}
				{"mso_smg2" "<c(FFFFFF)>Soldier<c(FFFFFF)>"}
				{"mso_sniper" "<c(FFFFFF)>Sniper<c(FFFFFF)>"}
			
				{"oficer" "<c(FFFFFF)>ofitser<c(FFFFFF)>"}
				{"pilot" "<c(FFFFFF)>Pilot<c(FFFFFF)>"}
				{"pilot_fighter" "<c(FFFFFF)>Pilot<c(FFFFFF)>"}
				{"pzrk" "<c(FFFFFF)>MANPAD operator<c(FFFFFF)>"}
				{"pzrkhelp" "<c(FFFFFF)>MANPAD operator 2nd<c(FFFFFF)>"}
				{"saper" "<c(FFFFFF)>Sapper<c(FFFFFF)>"}
				{"sniper" "<c(FFFFFF)>Sniper<c(FFFFFF)>"}
			
				{"spec_com" "<c(FFFFFF)>Squad com<c(FFFFFF)>"}
				{"spec_mgun" "<c(FFFFFF)>Machinegunner<c(FFFFFF)>"}
				{"spec_rpg" "<c(FFFFFF)>AT infantry<c(FFFFFF)>"}
				{"spec_rpghelp" "<c(FFFFFF)>Assistantfor AT infantry<c(FFFFFF)>"}
				{"spec_smg" "<c(FFFFFF)>Soldier<c(FFFFFF)>"}
				{"spec_smg2" "<c(FFFFFF)>Soldier<c(FFFFFF)>"}
				{"spec_sniper" "<c(FFFFFF)>Sniper<c(FFFFFF)>"}
			
				{"spotter" "<c(FFFFFF)>Spotter<c(FFFFFF)>"}
				{"tankman" "<c(FFFFFF)>Tankman<c(FFFFFF)>"}
				{"tankman2" "<c(FFFFFF)>Tankman<c(FFFFFF)>"}
				{"tankman3" "<c(FFFFFF)>Tankman<c(FFFFFF)>"}
				{"vehicle_supporter" "<c(FFFFFF)>Operator<c(FFFFFF)>"}
				{"vehicle_supporter_art" "<c(FFFFFF)>Operator<c(FFFFFF)>"}
				{"vertpilot" "<c(FFFFFF)>Heli pilot<c(FFFFFF)>"}
				{"vertpilot_z10" "<c(FFFFFF)>Heli pilot<c(FFFFFF)>"}
				{"operator_bpla" "<c(FFFFFF)>Operator UAV<c(FFFFFF)>"}
			}
            {"odkb"
				{"bel_borderguard" "<c(FFFFFF)>Borderguard<c(FFFFFF)>"}
				{"bel_com" "<c(FFFFFF)>Squad com<c(FFFFFF)>"}
				{"bel_mgun" "<c(FFFFFF)>Machinegunner<c(FFFFFF)>"}
				{"bel_mgunhelp" "<c(FFFFFF)>Assistantfor machinegunner<c(FFFFFF)>"}
				{"bel_rpg" "<c(FFFFFF)>AT infantry<c(FFFFFF)>"}
				{"bel_rpghelp" "<c(FFFFFF)>Assistantfor AT infantry<c(FFFFFF)>"}
				{"bel_smg" "<c(FFFFFF)>Soldier<c(FFFFFF)>"}
				{"bel_smg2" "<c(FFFFFF)>Soldier<c(FFFFFF)>"}
				{"bel_sniper" "<c(FFFFFF)>Sniper<c(FFFFFF)>"}
				{"bel_vertpilot" "<c(FFFFFF)>Pilot<c(FFFFFF)>"}
				{"bel_tankman" "<c(FFFFFF)>Tankman<c(FFFFFF)>"}
				{"bel_tankman2" "<c(FFFFFF)>Tankman<c(FFFFFF)>"}
				{"bel_tankman3" "<c(FFFFFF)>Tankman<c(FFFFFF)>"}
			
				{"iran_bazooker2" "<c(FFFFFF)>AT infantry<c(FFFFFF)>"}
				{"iran_bazooker2_help" "<c(FFFFFF)>AT infantry<c(FFFFFF)>"}
				{"iran_com" "<c(FFFFFF)>Squad com<c(FFFFFF)>"}
				{"iran_mgun" "<c(FFFFFF)>Machinegunner<c(FFFFFF)>"}
				{"iran_mgunhelp" "<c(FFFFFF)>Assistantfor machinegunner<c(FFFFFF)>"}
				{"iran_pilot" "<c(FFFFFF)>Pilot<c(FFFFFF)>"}
				{"iran_pzrk" "<c(FFFFFF)>MANPAD operator<c(FFFFFF)>"}
				{"iran_pzrkhelp" "<c(FFFFFF)>MANPAD operator 2nd<c(FFFFFF)>"}
				{"iran_rpg" "<c(FFFFFF)>AT infantry<c(FFFFFF)>"}
				{"iran_rpghelp" "<c(FFFFFF)>Assistantfor AT infantry<c(FFFFFF)>"}
				{"iran_smg" "<c(FFFFFF)>Soldier<c(FFFFFF)>"}
				{"iran_smg2" "<c(FFFFFF)>Soldier<c(FFFFFF)>"}
				{"iran_sniper" "<c(FFFFFF)>Sniper<c(FFFFFF)>"}
				{"iran_tankman" "<c(FFFFFF)>Tankman<c(FFFFFF)>"}
				{"iran_tankman2" "<c(FFFFFF)>Tankman<c(FFFFFF)>"}
				{"iran_tankman3" "<c(FFFFFF)>Tankman<c(FFFFFF)>"}
				{"iran_vehicle_supporter" "<c(FFFFFF)>Operator<c(FFFFFF)>"}
			
				{"kz_com" "<c(FFFFFF)>Squad com<c(FFFFFF)>"}
				{"kz_mgun" "<c(FFFFFF)>Machinegunner<c(FFFFFF)>"}
				{"kz_mgunhelp" "<c(FFFFFF)>Assistantfor machinegunner<c(FFFFFF)>"}
				{"kz_rpg" "<c(FFFFFF)>AT infantry<c(FFFFFF)>"}
				{"kz_rpghelp" "<c(FFFFFF)>Assistantfor AT infantry<c(FFFFFF)>"}
				{"kz_smg" "<c(FFFFFF)>Soldier<c(FFFFFF)>"}
				{"kz_smg2" "<c(FFFFFF)>Soldier<c(FFFFFF)>"}
				{"kz_sniper" "<c(FFFFFF)>Sniper<c(FFFFFF)>"}
				{"kz_tankman" "<c(FFFFFF)>Tankman<c(FFFFFF)>"}
				{"kz_tankman2" "<c(FFFFFF)>Tankman<c(FFFFFF)>"}
				{"kz_tankman3" "<c(FFFFFF)>Tankman<c(FFFFFF)>"}
			
				{"taj_com" "<c(FFFFFF)>Squad com<c(FFFFFF)>"}
				{"taj_mgun" "<c(FFFFFF)>Machinegunner<c(FFFFFF)>"}
				{"taj_mgunhelp" "<c(FFFFFF)>Assistantfor machinegunner<c(FFFFFF)>"}
				{"taj_rpg" "<c(FFFFFF)>AT infantry<c(FFFFFF)>"}
				{"taj_rpghelp" "<c(FFFFFF)>Assistantfor AT infantry<c(FFFFFF)>"}
				{"taj_smg" "<c(FFFFFF)>Soldier<c(FFFFFF)>"}
				{"taj_smg2" "<c(FFFFFF)>Soldier<c(FFFFFF)>"}
				{"taj_sniper" "<c(FFFFFF)>Sniper<c(FFFFFF)>"}			
			
				{"tankman" "<c(FFFFFF)>Tankman<c(FFFFFF)>"}
				{"tankman2" "<c(FFFFFF)>Tankman<c(FFFFFF)>"}
				{"tankman3" "<c(FFFFFF)>Tankman<c(FFFFFF)>"}
			
				{"vdv_com" "<c(FFFFFF)>Squad com<c(FFFFFF)>"}
				{"vdv_mgun" "<c(FFFFFF)>Machinegunner<c(FFFFFF)>"}
				{"vdv_radio" "<c(FFFFFF)>Radioman<c(FFFFFF)>"}
				{"vdv_rpg" "<c(FFFFFF)>AT infantry<c(FFFFFF)>"}
				{"vdv_rpghelp" "<c(FFFFFF)>Assistantfor AT infantry<c(FFFFFF)>"}
				{"vdv_smg" "<c(FFFFFF)>Soldier<c(FFFFFF)>"}
				{"vdv_smg2" "<c(FFFFFF)>Soldier<c(FFFFFF)>"}
				{"vdv_zamcom" "<c(FFFFFF)>Sergeant<c(FFFFFF)>"}
				{"vdv_sniper" "<c(FFFFFF)>Sniper<c(FFFFFF)>"}
				{"vdv_tankman" "<c(FFFFFF)>Tankman<c(FFFFFF)>"}
				{"vdv_tankman2" "<c(FFFFFF)>Tankman<c(FFFFFF)>"}
			
				{"vehicle_supporter" "<c(FFFFFF)>Operator<c(FFFFFF)>"}
			}
		}

		{"single"
			{"rus"
				{"samoilov" "Aleksandr Samoilov"}
				{"filipov" "Roman Filippov"}
				{"sso" "SSO soldier RF"}
				{"doronin" "Vasiliy Doronin"}
				{"doronin_office" "Vasiliy Doronin"}
				{"pankratov" "Dmitriy Pankratov"}
				{"grishenko" "Victor Grishenko"}
				{"tretyak" "Andrey Tretyak"}
				{"rudzinskiy" "Andrey Rudzinskiy"}
				{"fomin" "Victor Fomin"}
				{"gromov" "Yuriy Gromov"}
				{"sorokin" "Stanislav Sorokin"}
				{"Podolansky" "Vladimir Podolanskiy"}
				{"spec_com_Mishin" "Alexey Mishin"}
				{"spec_sniper_Tihomirov" "Konstantin Tihomirov"}
				{"spec_smgpod_Pozolotin" "Valeriy Pozolotin"}
				{"spec_radio_Klimov" "Gleb Klimov"}
				{"spec_groza_Nasedkin" "Vasiliy Nasedkin"}
				{"spec_smgopt_Savin" "Victor Savin"}
				{"spec_smgrpg_Aleksandrov" "Vladimir Aleksandrov"}
				{"spec_mgun_Nasonov" "Makar Nasonov"}
				{"spec_mgun1_Romanov" "Zahar Romanov"}
				{"spec_rpg_Zaycev" "Roman Zaycev"}
				{"spec_rpghelp_Belov" "Vitaliy Belov"}
				{"jivaev" "Eduard Jivaev"}
				{"genne" "Alexandr Genne"}
				{"luchnikov" "Arkadiy Luchnikov"}
				{"sherbakov" "Victor Sherbakov"}
				{"arhipov" "Victor Arkhipov"}
				{"judin" "Evgeniy Yudin"}
				{"mayor" "Major Filimonov"}
				{"captain" "Captain Morozov"}
				{"guba" "Colonel Guba"}
				{"volkov" "Sn. lieutenant Volkov"}
				{"groz_burlakov" "Lieutenant Colonel Semyon Burlakov, Chief of Staff 81 regiment"}
				{"groz_chernutskiy" "Major A. Chernutsky"}
				{"groz_chmirev" "Captain Yuri Chmirev, com. 1 company"}
				{"groz_klapcov" "Lieutenant Colonel Yuri Klaptsov, com. Operations department 131omsbr"}
				{"groz_klupov" "Captain Rustem Klupov, com. 3 company"}
				{"groz_kojura" "Sn. Lieutenant Oleg Kozhura, medical service"}
				{"groz_pulikovskiy" "Major General Konstantin Pulikovsky, com. of group North"}
				{"groz_savin" "Colonel Ivan Savin, brigade commander 131omsbr"}
				{"groz_tupikov" "Lieutenant Colonel Nikolai Tupikov, Chief of medical services "}
				{"groz_vechkanov" "Captain Igor Vechkanov, com. 8 tank company"}
				{"leviaf_11div949" "Rear Admiral Valery Varfolomeev, com. 11 submarine divisions"}
				{"leviaf_956bistriy" "Cap-one Alexander Katkov, DDG \"Bistriy\""}
				{"leviaf_956ushakov" "Cap-two Sergey Rusakov, DDG \"Adm. Ushakov\""}
				{"leviaf_1144petr" "Cap-one Igor Nikitin, CGN \"Peter the Great\""}
				{"leviaf_1164ust" "Cap-one Vladimir Kuzmin, CG \"Adm. Ustinov\""}
				{"leviaf_fleetcom" "Vitse-admiral Аleksandr Moiseev, kom. Severnim flotom RF"}
				{"leviaf_kuznecov" "Cap-one Sergey Artamonov, CV \"Adm. Kuznetsov\""}
				{"leviaf_officer" "Officer VMF RF"}
				{"zguralsky" "Pavel Zguralsky"}
			}
			{"usa"
				{"pittard" "Dana Pittard"}
				{"jackson" "Oliver Jackson"}
                {"steffens" "Michael Steffens"}
				{"bazooker" "AT infantry"}
				{"bazooker2" "AT infantry"}
				{"gren" "Grenadier"}
				{"help_bazooker2" "Assistantfor AT infantry"}
				{"helpmgun" "Assistantfor machinegunner"}
				{"marksman" "Marksman"}
				{"mgun" "Machinegunner"}
				{"sailor" "Sailor"}
				{"smg" "Soldier"}
				{"smgcom" "Fire team com"}
				{"tankman" "Tankman"}
				{"us90-99_army_sniper" "<c(FFFFFF)>Sniper<c(FFFFFF)>"}
				{"us90-99_army_spotter" "<c(FFFFFF)>Spotter<c(FFFFFF)>"}
				{"us90-99_at" "<c(FFFFFF)>Heavy snajper<c(FFFFFF)>"}
				{"us90-99_help_at" "<c(FFFFFF)>Assistantfor sniper<c(FFFFFF)>"}
				{"us90-99_oficer" "<c(FFFFFF)>Officer<c(FFFFFF)>"}
				{"us90-99alpha_grenadier_smg" "<c(FFFFFF)>Soldier<c(FFFFFF)>"}
				{"us90-99alpha_heavy_mgun" "<c(FFFFFF)>Machinegunner<c(FFFFFF)>"}
				{"us90-99alpha_rifleman" "<c(FFFFFF)>Soldier<c(FFFFFF)>"}
				{"us90-99alpha_squad_leader" "<c(FFFFFF)>Squad com<c(FFFFFF)>"}
				{"us90-99alpha_team_leader" "<c(FFFFFF)>Kom. Fire team<c(FFFFFF)>"}
				{"us90-99bravo_automatic_rifleman" "<c(FFFFFF)>Soldier<c(FFFFFF)>"}
				{"us90-99bravo_grenadier_smg" "<c(FFFFFF)>Soldier<c(FFFFFF)>"}
				{"us90-99bravo_rifleman" "<c(FFFFFF)>Soldier<c(FFFFFF)>"}
				{"us90-99bravo_team_leader" "<c(FFFFFF)>Kom. Fire team<c(FFFFFF)>"}
				{"us90-99engineer" "<c(FFFFFF)>Engineer<c(FFFFFF)>"}
				{"us90-99pzrk" "<c(FFFFFF)>MANPAD operator<c(FFFFFF)>"}
				{"us90-99pzrkhelp_new" "<c(FFFFFF)>MANPAD operator 2nd<c(FFFFFF)>"}
				{"us90-99vehicle_supporter" "<c(FFFFFF)>Operator<c(FFFFFF)>"}
			}
			{"chn_summer"
				{"bazooker" "AT infantry"}
				{"defend" "Experienced boevik"}
				{"defend2" "Experienced boevik"}
				{"defend3" "Experienced boevik"}
				{"defend4" "Experienced boevik"}
				{"defend5" "Experienced boevik"}
				{"elite" "Experienced boevik"}
				{"elite2" "Experienced boevik"}
				{"elite3" "Experienced boevik"}
				{"lshturm" "Experienced boevik"}
				{"mg" "pulemetchik"}
				{"mg2" "pulemetchik"}
				{"mg3" "pulemetchik"}
				{"mgun" "pulemetchik"}
				{"minmen" "minometchik"}
				{"minmen2" "minometchik"}
				{"oficer" "ofitser"}
				{"saper" "saper"}
				{"shturm" "Experienced boevik"}
				{"shturm2" "Experienced boevik"}
				{"shturm3" "Experienced boevik"}
				{"smg" "soldat"}
				{"smg2" "soldat"}
				{"smg3" "soldat"}
				{"sniper" "snajper"}
				{"tankman" "Tankman"}
				{"tankman2" "Tankman"}
				{"tankman3" "Tankman"}
				{"vehicle_supporter" "Operator"}
				{"groz_kovalev" "Deputy Sergey Kovalev, human rights activist"}
				{"groz_maskhadov" "Aslan Maskhadov, Chief of ChRI General Staff "}
			}
			{"chn_winter"
				{"bazooker" "grenade launcherchik"}
				{"defend" "Experienced boevik"}
				{"defend2" "Experienced boevik"}
				{"defend3" "Experienced boevik"}
				{"defend4" "Experienced boevik"}
				{"defend5" "Experienced boevik"}
				{"elite" "Experienced boevik"}
				{"elite2" "Experienced boevik"}
				{"elite3" "Experienced boevik"}
				{"lshturm" "Experienced boevik"}
				{"mg" "pulemetchik"}
				{"mg2" "pulemetchik"}
				{"mg3" "pulemetchik"}
				{"mgun" "pulemetchik"}
				{"minmen" "minometchik"}
				{"minmen2" "minometchik"}
				{"oficer" "ofitser"}
				{"saper" "saper"}
				{"shturm" "Experienced boevik"}
				{"shturm2" "Experienced boevik"}
				{"shturm3" "Experienced boevik"}
				{"smg" "soldat"}
				{"smg2" "soldat"}
				{"smg3" "soldat"}
				{"sniper" "snajper"}
				{"tankman" "Tankman"}
				{"tankman2" "Tankman"}
				{"tankman3" "Tankman"}
				{"vehicle_supporter" "Operator"}
				{"groz_kovalev" "Deputy Sergey Kovalev, human rights activist"}
				{"groz_maskhadov" "Aslan Maskhadov, Chief of ChRI General Staff "}
			}
			{"fed_summer"
				{"antipersonel_miner" "AP miner"}
				{"antitank_miner" "AT miner"}
				{"bazooker" "AT infantry"}
				{"bazooker2" "AT infantry"}
				{"engineer" "Engineer"}
				{"flamer" "Flamer"}
				{"flamer2" "Flamer"}
				{"mgun" "Machinegunner"}
				{"oficer" "Officer"}
				{"nav" "Spotter"}
				{"pilot" "Pilot"}
				{"saper" "Sapper"}
				{"scout" "Scout"}
				{"scout2" "Scout"}
				{"smg" "Soldier"}
				{"sniper" "Sniper"}
				{"omon" "OMON"}
				{"vdv" "VDV"}
				{"minmen" "Grenadier"}
				{"tankman" "Tankman"}
				{"tankman2" "Tankman"}
				{"tankman3" "Tankman"}
				{"vehicle_supporter" "Operator"}
				{"at_rifle" "Heavy snajper"}
				{"elite" "Red beret"}
				{"elite2" "Red beret"}
				{"elite3" "Red beret"}
				{"smg2" "Soldier"}
				{"smg3" "Soldier"}
				{"omon2" "OMON"}
				{"omon3" "OMON"}
				{"vdv2" "VDV"}
				{"vdv3" "VDV"}
				{"defend" "Specnaz"}
				{"defend2" "Specnaz"}
				{"defend3" "Specnaz"}
				{"defend4" "Specnaz"}
				{"defend5" "Specnaz"}
            }
			{"fed_winter"
				{"antipersonel_miner" "AP miner"}
				{"antitank_miner" "AT miner"}
				{"bazooker" "AT infantry"}
				{"bazooker2" "AT infantry"}
				{"engineer" "Engineer"}
				{"flamer" "Flamer"}
				{"flamer2" "Flamer"}
				{"mgun" "Machinegunner"}
				{"oficer" "Officer"}
				{"nav" "Spotter"}
				{"pilot" "Pilot"}
				{"saper" "Sapper"}
				{"scout" "Scout"}
				{"scout2" "Scout"}
				{"smg" "Soldier"}
				{"sniper" "Sniper"}
				{"omon" "OMON"}
				{"vdv" "VDV"}
				{"minmen" "Grenadier"}
				{"tankman" "Tankman"}
				{"tankman2" "Tankman"}
				{"tankman3" "Tankman"}
				{"vehicle_supporter" "Operator"}
				{"at_rifle" "Heavy snajper"}
				{"elite" "Red beret"}
				{"elite2" "Red beret"}
				{"elite3" "Red beret"}
				{"smg2" "Soldier"}
				{"smg3" "Soldier"}
				{"omon2" "OMON"}
				{"omon3" "OMON"}
				{"vdv2" "VDV"}
				{"vdv3" "VDV"}
				{"defend" "Specnaz"}
				{"defend2" "Specnaz"}
				{"defend3" "Specnaz"}
				{"defend4" "Specnaz"}
				{"defend5" "Specnaz"}
            }
			{"ukr"
				{"smg" "<c(FFFFFF)>Soldier<c(FFFFFF)>"}
				{"vehicle_supporter" "<c(FFFFFF)>Operator<c(FFFFFF)>"}
				{"tankman" "<c(FFFFFF)>Tankman<c(FFFFFF)>"}
				{"tankman2" "<c(FFFFFF)>Tankman<c(FFFFFF)>"}
				{"tankman3" "<c(FFFFFF)>Tankman<c(FFFFFF)>"}
				{"pilot" "<c(FFFFFF)>Pilot<c(FFFFFF)>"}

				{"mso_com" "<c(FFFFFF)>Squad com<c(FFFFFF)>"}
				{"mso_mgun" "<c(FFFFFF)>Machinegunner<c(FFFFFF)>"}
				{"mso_mgunhelp" "<c(FFFFFF)>Assistantfor machinegunner<c(FFFFFF)>"}
				{"mso_radio" "<c(FFFFFF)>Radioman<c(FFFFFF)>"}
				{"mso_rpg" "<c(FFFFFF)>AT infantry<c(FFFFFF)>"}
				{"mso_rpghelp" "<c(FFFFFF)>Assistantfor AT infantry<c(FFFFFF)>"}
				{"mso_smg" "<c(FFFFFF)>Soldier<c(FFFFFF)>"}
				{"mso_smg2" "<c(FFFFFF)>Soldier<c(FFFFFF)>"}
				{"mso_sniper" "<c(FFFFFF)>Sniper<c(FFFFFF)>"}

				{"vdv_com" "<c(FFFFFF)>Squad com<c(FFFFFF)>"}
				{"vdv_mgun" "<c(FFFFFF)>Machinegunner<c(FFFFFF)>"}
				{"vdv_radio" "<c(FFFFFF)>Radioman<c(FFFFFF)>"}
				{"vdv_rpg" "<c(FFFFFF)>AT infantry<c(FFFFFF)>"}
				{"vdv_rpghelp" "<c(FFFFFF)>Assistantfor AT infantry<c(FFFFFF)>"}
				{"vdv_smg" "<c(FFFFFF)>Soldier<c(FFFFFF)>"}
				{"vdv_smg2" "<c(FFFFFF)>Soldier<c(FFFFFF)>"}
				{"vdv_zamcom" "<c(FFFFFF)>Sergeant<c(FFFFFF)>"}
				{"vdv_sniper" "<c(FFFFFF)>Sniper<c(FFFFFF)>"}
				{"vdv_tankman" "<c(FFFFFF)>Tankman<c(FFFFFF)>"}
				{"vdv_tankman2" "<c(FFFFFF)>Tankman<c(FFFFFF)>"}
			}
			{"arb"
				{"army_vehicle_rpg" "AT infantry"}
				{"army_com" "Squad com"}
				{"army_mgun" "Machinegunner"}			
				{"army_mgunhelp" "Assistantfor machinegunner"}
				{"army_radio" "Radioman"}
				{"army_rpg" "AT infantry"}
				{"army_rpghelp" "Assistantfor AT infantry"}
				{"army_smg" "Soldier"}
				{"army_smg2" "Soldier"}
				{"army_sniper" "Sniper"}
				{"army_tankman" "Tankman"}
				{"army_vehicle_supporter" "Operator"}
				{"army_saper" "Sapper"}				
				{"army_engineer" "Engineer"}
				{"boevik_mgun" "Machinegunner"}
				{"boevik_rpg" "AT infantry"}
				{"boevik_rpghelp" "Assistantfor AT infantry"}
				{"boevik_sharpshooter" "Shooter"}
				{"boevik_smg" "Bandit"}
				{"boevik_smg1" "Bandit"}
				{"boevik_smg2" "Bandit"}
				{"boevik_sniper" "Sniper"}
				{"boevik_tankman" "Tankman"}
				{"boevik_saper" "Sapper"}				
				{"boevik_engineer" "Engineer"}
				{"informator" "Abbas Hurshid"}
				{"rus_spec_com_Mishin" "Alexey Mishin"}
				{"rus_spec_sniper_Tihomirov" "Konstantin Tihomirov"}
				{"rus_spec_smgpod_Pozolotin" "Valeriy Pozolotin"}
				{"rus_spec_radio_Klimov" "Gleb Klimov"}
				{"rus_spec_groza_Nasedkin" "Vasiliy Nasedkin"}
				{"rus_spec_smgopt_Savin" "Victor Savin"}
				{"rus_spec_smgrpg_Aleksandrov" "Vladimir Aleksandrov"}
				{"rus_spec_mgun_Nasonov" "Makar Nasonov"}
				{"rus_spec_mgun1_Romanov" "Zahar Romanov"}
				{"rus_spec_rpg_Zaycev" "Roman Zaycev"}
				{"rus_spec_rpghelp_Belov" "Vitaliy Belov"}
				{"syr_hero_halid" "Zahir Halid"}
				{"syr_hero_jabril" "Hasan Jabril"}
				{"syr_hero_mahmud" "Tofik Mahmud"}
				{"syr_hero_malik" "Jusuf Malik"}
				{"syr_hero_mustafa" "Bakir Mustafa"}
				{"somani" "Farid Somani"}
				{"hussain" "Saddam Hussain"}
				{"haddad" "Jerab Haddad"}
				{"umar" "Umar Abbas"}
				{"sso" "SSO"}
			}
			{"geo"
				{"geo_bazooker" "AT infantry"}
				{"geo_sniper" "Sniper"}
				{"geo_mgun" "Machinegunner"}
				{"geo_smg" "Soldier"}
				{"geo_smg2" "Soldier"}
				{"geo_specforces" "Specnaz"}
				{"geo_specforcesb" "AT infantry"}
				{"geo_specforcesm" "Machinegunner"}
				{"geo_specforcess" "Sniper"}	
				{"pilot" "Pilot"}
				{"tankman" "Tankman"}
				{"vehicle_supporter" "Operator"}		
 			}
			{"hun"
				{"engineer" "<c(FFFFFF)>Engineer<c(FFFFFF)>"}
				{"hun_bazooker" "<c(FFFFFF)>AT infantry<c(FFFFFF)>"}
				{"hun_com" "<c(FFFFFF)>Squad com<c(FFFFFF)>"}
				{"hun_gren" "<c(FFFFFF)>Grenadier<c(FFFFFF)>"}
				{"hun_medic" "<c(FFFFFF)>Medic<c(FFFFFF)>"}
				{"hun_mgun" "<c(FFFFFF)>Machinegunner<c(FFFFFF)>"}
				{"hun_smg" "<c(FFFFFF)>Soldier<c(FFFFFF)>"}	
				{"hun_smg2" "<c(FFFFFF)>Soldier<c(FFFFFF)>"}	
				{"hun_sniper" "<c(FFFFFF)>Marksman<c(FFFFFF)>"}
				{"oficer" "<c(FFFFFF)>Officer<c(FFFFFF)>"}
				{"pilot" "<c(FFFFFF)>Pilot<c(FFFFFF)>"}		
				{"tankman" "<c(FFFFFF)>Tankman<c(FFFFFF)>"}
				{"tankman2" "<c(FFFFFF)>Tankman<c(FFFFFF)>"}
				{"tankman3" "<c(FFFFFF)>Tankman<c(FFFFFF)>"}
				{"vehicle_supporter" "<c(FFFFFF)>Operator<c(FFFFFF)>"}
				{"engineer" "<c(FFFFFF)>Engineer<c(FFFFFF)>"}
			}
			{"irq"
				{"irq_engineer" "<c(FFFFFF)>Engineer<c(FFFFFF)>"}
				{"irq_rpg" "<c(FFFFFF)>AT infantry<c(FFFFFF)>"}
				{"irq_com" "<c(FFFFFF)>Squad com<c(FFFFFF)>"}
				{"irq_radio" "<c(FFFFFF)>Radioman<c(FFFFFF)>"}
				{"irq_mgun" "<c(FFFFFF)>Machinegunner<c(FFFFFF)>"}
				{"irq_mgunhelp" "<c(FFFFFF)>Assistantpulemetchik<c(FFFFFF)>"}
				{"irq_smg" "<c(FFFFFF)>Soldier<c(FFFFFF)>"}	
				{"irq_smg2" "<c(FFFFFF)>Soldier<c(FFFFFF)>"}	
				{"irq_sniper" "<c(FFFFFF)>Sniper<c(FFFFFF)>"}

				{"irq_recruits__rpg" "<c(FFFFFF)>AT infantry-prizivnik<c(FFFFFF)>"}	
				{"irq_recruits__smg" "<c(FFFFFF)>Soldier-prizivnik<c(FFFFFF)>"}	
				{"irq_recruits__smg2" "<c(FFFFFF)>Soldier-prizivnik<c(FFFFFF)>"}	
				{"irq_recruits_com" "<c(FFFFFF)>Squad com-prizivnik<c(FFFFFF)>"}	
				{"irq_recruits_mgun" "<c(FFFFFF)>Machinegunner-prizivnik<c(FFFFFF)>"}	

				{"irq_elite" "<c(FFFFFF)>Guardsman<c(FFFFFF)>"}
				{"irq_elite2" "<c(FFFFFF)>Guardsman<c(FFFFFF)>"}
				{"irq_elite3" "<c(FFFFFF)>Guardsman<c(FFFFFF)>"}
				{"irq_elite4" "<c(FFFFFF)>Guardsman<c(FFFFFF)>"}
				{"irq_officer" "<c(FFFFFF)>Officer<c(FFFFFF)>"}
				{"irq_pzrk" "<c(FFFFFF)>MANPAD operator<c(FFFFFF)>"}
				{"pilot" "<c(FFFFFF)>Pilot<c(FFFFFF)>"}		
				{"irq_tankman" "<c(FFFFFF)>Tankman<c(FFFFFF)>"}
			}
			{"oksva"
				{"antipersonel_miner" "<c(FFFFFF)>AP miner<c(FFFFFF)>"}
				{"antitank_miner" "<c(FFFFFF)>AT miner<c(FFFFFF)>"}
				{"bazooker" "<c(FFFFFF)>AT infantry<c(FFFFFF)>"}
				{"defend" "<c(FFFFFF)>Specnaz<c(FFFFFF)>"}
				{"defend2" "<c(FFFFFF)>Specnaz<c(FFFFFF)>"}
				{"defend3" "<c(FFFFFF)>Specnaz<c(FFFFFF)>"}
				{"defend4" "<c(FFFFFF)>Specnaz<c(FFFFFF)>"}
				{"engineer" "<c(FFFFFF)>Engineer<c(FFFFFF)>"}
				{"flamer2" "<c(FFFFFF)>Flamer<c(FFFFFF)>"}
				{"mgun" "<c(FFFFFF)>Machinegunner<c(FFFFFF)>"}
				{"oficer" "<c(FFFFFF)>Officer<c(FFFFFF)>"}
				{"saper" "<c(FFFFFF)>Sapper<c(FFFFFF)>"}
				{"smg" "<c(FFFFFF)>Soldier<c(FFFFFF)>"}
				{"smg2" "<c(FFFFFF)>Soldier<c(FFFFFF)>"}
				{"smg3" "<c(FFFFFF)>Soldier<c(FFFFFF)>"}
				{"sniper" "<c(FFFFFF)>Sniper<c(FFFFFF)>"}
				{"tankman" "<c(FFFFFF)>Tankman<c(FFFFFF)>"}
				{"tankman2" "<c(FFFFFF)>Tankman<c(FFFFFF)>"}
				{"tankman3" "<c(FFFFFF)>Tankman<c(FFFFFF)>"}
				{"vdv_com" "<c(FFFFFF)>VDV<c(FFFFFF)>"}
				{"vdv_mgun" "<c(FFFFFF)>VDV<c(FFFFFF)>"}
				{"vdv_rpg" "<c(FFFFFF)>VDV<c(FFFFFF)>"}
				{"vdv_smg" "<c(FFFFFF)>VDV<c(FFFFFF)>"}
				{"vdv_sniper" "<c(FFFFFF)>VDV<c(FFFFFF)>"}
				{"vdv_zamcom" "<c(FFFFFF)>VDV<c(FFFFFF)>"}
				{"vehicle_supporter" "<c(FFFFFF)>Operator<c(FFFFFF)>"}
				{"vertpilot" "<c(FFFFFF)>Pilot<c(FFFFFF)>"}
			}
			{"est"
				{"est_at_rifle" "<c(FFFFFF)>Antisniper<c(FFFFFF)>"}
				{"est_at_rifle_spotter" "<c(FFFFFF)>Spotter<c(FFFFFF)>"}
				{"est_bazooker" "<c(FFFFFF)>AT infantry<c(FFFFFF)>"}
				{"est_bazooker_jav" "<c(FFFFFF)>Operator FGM-148 Javelin<c(FFFFFF)>"}
				{"est_bazooker_jav_support" "<c(FFFFFF)>Assistant operator's FGM-148 Javelin<c(FFFFFF)>"}
				{"est_com" "<c(FFFFFF)>Squad com<c(FFFFFF)>"}
				{"est_gren" "<c(FFFFFF)>Grenadier<c(FFFFFF)>"}
				{"est_medic" "<c(FFFFFF)>Medic<c(FFFFFF)>"}
				{"est_mgun" "<c(FFFFFF)>Machinegunner<c(FFFFFF)>"}
				{"est_mgunhelp" "<c(FFFFFF)>Assistantfor machinegunner<c(FFFFFF)>"}
				{"est_oficer" "<c(FFFFFF)>Officer<c(FFFFFF)>"}
				{"est_rpghelp" "<c(FFFFFF)>Assistantfor AT infantry<c(FFFFFF)>"}
				{"est_smg" "<c(FFFFFF)>Soldier<c(FFFFFF)>"}
				{"est_smg2" "<c(FFFFFF)>Soldier<c(FFFFFF)>"}
				{"est_sniper" "<c(FFFFFF)>snajper<c(FFFFFF)>"}
				{"est_tankman" "<c(FFFFFF)>Tankman<c(FFFFFF)>"}
				{"est_vehicle_supporter" "<c(FFFFFF)>Operator<c(FFFFFF)>"}
			}
			{"jap"
				{"jap_bazooker" "<c(FFFFFF)>AT infantry<c(FFFFFF)>"}
				{"jap_com" "<c(FFFFFF)>Squad com<c(FFFFFF)>"}
				{"jap_mgun" "<c(FFFFFF)>Machinegunner<c(FFFFFF)>"}
				{"jap_smg" "<c(FFFFFF)>Soldier<c(FFFFFF)>"}
				{"jap_smg2" "<c(FFFFFF)>Soldier<c(FFFFFF)>"}
				{"jap_sniper" "<c(FFFFFF)>snajper<c(FFFFFF)>"}
				{"vehicle_supporter" "<c(FFFFFF)>Operator<c(FFFFFF)>"}
				{"tankman" "<c(FFFFFF)>Tankman<c(FFFFFF)>"}
				{"jap_mgun_help" "<c(FFFFFF)>Assistantfor machinegunner<c(FFFFFF)>"}
				{"jap_marksman" "<c(FFFFFF)>Marksman<c(FFFFFF)>"}
				{"jap_army_spotter" "<c(FFFFFF)>Spotter<c(FFFFFF)>"}
				{"pzrk_new" "<c(FFFFFF)>MANPAD operator<c(FFFFFF)>"}
				{"pzrkhelp_new" "<c(FFFFFF)>MANPAD operator 2nd<c(FFFFFF)>"}
			}
			{"lat"
				{"lat_bazooker" "<c(FFFFFF)>AT infantry<c(FFFFFF)>"}
				{"lat_com" "<c(FFFFFF)>Squad com<c(FFFFFF)>"}
				{"lat_gren" "<c(FFFFFF)>Grenadier<c(FFFFFF)>"}
				{"lat_medic" "<c(FFFFFF)>Medic<c(FFFFFF)>"}
				{"lat_mgun" "<c(FFFFFF)>Machinegunner<c(FFFFFF)>"}
				{"lat_mgunhelp" "<c(FFFFFF)>Assistantfor machinegunner<c(FFFFFF)>"}
				{"lat_oficer" "<c(FFFFFF)>Officer<c(FFFFFF)>"}
				{"lat_pzrk_soldier" "<c(FFFFFF)>MANPAD operator<c(FFFFFF)>"}
				{"lat_pzrk_help_soldier" "<c(FFFFFF)>MANPAD operator 2nd<c(FFFFFF)>"}
				{"lat_rpghelp" "<c(FFFFFF)>Assistantfor AT infantry<c(FFFFFF)>"}
				{"lat_smg" "<c(FFFFFF)>Soldier<c(FFFFFF)>"}
				{"lat_smg2" "<c(FFFFFF)>Soldier<c(FFFFFF)>"}
				{"lat_sniper" "<c(FFFFFF)>snajper<c(FFFFFF)>"}
				{"lat_tankman" "<c(FFFFFF)>Tankman<c(FFFFFF)>"}
				{"lat_vehicle_supporter" "<c(FFFFFF)>Operator<c(FFFFFF)>"}
			}
			{"lit"
				{"lit_bazooker" "<c(FFFFFF)>AT infantry<c(FFFFFF)>"}
				{"lit_com" "<c(FFFFFF)>Squad com<c(FFFFFF)>"}
				{"lit_gren" "<c(FFFFFF)>Grenadier<c(FFFFFF)>"}
				{"lit_kasp" "<c(FFFFFF)>Soldier KASP<c(FFFFFF)>"}
				{"lit_kasp_bazooker" "<c(FFFFFF)>AT infantry KASP<c(FFFFFF)>"}
				{"lit_kasp_mgun" "<c(FFFFFF)>Machinegunner KASP<c(FFFFFF)>"}
				{"lit_kasp_sniper" "<c(FFFFFF)>snajper KASP<c(FFFFFF)>"}
				{"lit_medic" "<c(FFFFFF)>Medic<c(FFFFFF)>"}
				{"lit_mgun" "<c(FFFFFF)>Machinegunner<c(FFFFFF)>"}
				{"lit_mgunhelp" "<c(FFFFFF)>Assistantfor machinegunner<c(FFFFFF)>"}
				{"lit_oficer" "<c(FFFFFF)>Officer<c(FFFFFF)>"}
				{"lit_rpghelp" "<c(FFFFFF)>Assistantfor AT infantry<c(FFFFFF)>"}
				{"lit_smg" "<c(FFFFFF)>Soldier<c(FFFFFF)>"}
				{"lit_smg2" "<c(FFFFFF)>Soldier<c(FFFFFF)>"}
				{"lit_sniper" "<c(FFFFFF)>Sniper<c(FFFFFF)>"}
				{"lit_tankman" "<c(FFFFFF)>Tankman<c(FFFFFF)>"}
				{"lit_vehicle_supporter" "<c(FFFFFF)>Operator<c(FFFFFF)>"}
			}
			{"cu"
				{"rafael_leon_de_rubio" "<c(FFFFFF)>Rafael Leon de Rubio<c(FFFFFF)>"}
				{"avispas" "<c(FFFFFF)>Avis Pas<c(FFFFFF)>"}
				{"avispas_com" "<c(FFFFFF)>Avis Pas squad com<c(FFFFFF)>"}
				{"avispas_marksman" "<c(FFFFFF)>Avis Pas marksman<c(FFFFFF)>"}
				{"avispas_mgun" "<c(FFFFFF)>Avis Pas machinegunner<c(FFFFFF)>"}
				{"avispas_rpg" "<c(FFFFFF)>Avis Pas AT infantry<c(FFFFFF)>"}
				{"avispas_smg" "<c(FFFFFF)>Avis Pas<c(FFFFFF)>"}
				{"avispas_smg2" "<c(FFFFFF)>Avis Pas<c(FFFFFF)>"}
				{"avispas_smg3" "<c(FFFFFF)>Avis Pas<c(FFFFFF)>"}
				{"mgun" "<c(FFFFFF)>Machinegunner<c(FFFFFF)>"}
				{"mgunhelp" "<c(FFFFFF)>Assistant for machinegunner<c(FFFFFF)>"}
				{"radio" "<c(FFFFFF)><c(FFFFFF)>"}
				{"rpg" "<c(FFFFFF)>AT infantry<c(FFFFFF)>"}
				{"smg" "<c(FFFFFF)>Soldier<c(FFFFFF)>"}
				{"smg2" "<c(FFFFFF)>Soldier<c(FFFFFF)>"}
				{"sniper" "<c(FFFFFF)>Sniper<c(FFFFFF)>"}
				{"tankman" "<c(FFFFFF)>Tankman<c(FFFFFF)>"}
				{"vehicle_supporter" "<c(FFFFFF)>Operator<c(FFFFFF)>"}
			}
		}
		{"civilian"
			{"civilian1" "Civilian"}
			{"civilian2" "Civilian"}
			{"civilian3" "Civilian"}
			{"civilian4" "Civilian"}
			{"civilian5" "Civilian"}
			{"civilian6" "Civilian"}
			{"civilian7" "Civilian"}
			{"civilian8" "Civilian"}
			{"civilian9" "Civilian"}
			{"civilian10" "Civilian"}
			{"civilian11" "Civilian"}
			{"civilian1_cu" "Civilian"}
			{"civilian2_cu" "Civilian"}
			{"civilian3_cu" "Civilian"}
			{"civilian4_cu" "Civilian"}
			{"civilian5_cu" "Civilian"}
			{"civilian6_cu" "Civilian"}
			{"civilian7_cu" "Civilian"}
			{"civilian8_cu" "Civilian"}
			{"civilian9_cu" "Civilian"}
			{"civilian10_cu" "Civilian"}
			{"civilian11_cu" "Civilian"}
			{"civguarda1" "Guard"}
			{"civguarda2" "Guard"}
			{"civguarda3" "Guard"}
			{"civguarda4" "Guard"}
			{"civguardb1" "Guard"}
			{"civguardb2" "Guard"}
			{"civguardb3" "Guard"}
			{"civguardb4" "Guard"}
			{"cw_civilian_med" "Medic"}
			{"cw_civilian_med_rus" "Medic"}
			{"cw_civilian_worker" "Worker"}
			{"cw_civilian_worker1" "Worker"}
			{"priv_mil_smg" "Shooter ChVK"}
			{"priv_mil_smg1" "Shooter ChVK"}
			{"priv_mil_marksman" "Marksman ChVK"}
			{"priv_mil_rpg" "Spetsialist ChVK"}
		}