		{"capture" "<c(8470ff)>▼▼▼<c(BBBBBB)>"}
	
		{"body_broken" "<c(FF1F00)>Hull destroyed<c(FFFFFF)>"}
		{"body_injured" "<c(FFFF00)>Hull damaged<c(FFFFFF)>"}
		{"track_broken" "<c(FF1F00)>Track broken<c(FFFFFF)>"}
		{"track_injured" "<c(FFFF00)>Track damaged<c(FFFFFF)>"}
		{"engine_broken" "<c(FF1F00)>Engine broken<c(FFFFFF)>"}
		{"engine_injured" "<c(FFFF00)>Engine damaged<c(FFFFFF)>"}
		{"gun_broken" "<c(FF1F00)>Gun broken<c(FFFFFF)>"}
		{"gun_injured" "<c(FFFF00)>Gun damaged<c(FFFFFF)>"}
		{"turret_broken" "<c(FF1F00)>Turret broken<c(FFFFFF)>"}
		{"turret_injured" "<c(FFFF00)>Turret damaged<c(FFFFFF)>"}
		{"turret_pierced" "<c(FFFF00)>Turret pierce<c(FFFFFF)>"}
		{"armor_broken" "<c(FF1F00)>Armor broken<c(FFFFFF)>"}
		{"armor_injured" "<c(FFFF00)>Armor damaged<c(FFFFFF)>"}
		{"body_break" "<c(FFFF00)>Hull destroyed<c(FFFFFF)>"}
		{"body_pierced" "<c(FFFF00)>Hull pierced<c(FFFFFF)>"}
		{"turret_jammed" "<c(FFFF00)>Turret jammed<c(FFFFFF)>"}
		{"burn_engine" "<c(FFAF00)>Engine fire<c(FFFFFF)>"}
		{"burn_fire" "<c(FFAF00)>Fire<c(FFFFFF)>"}
		{"overheat" "<c(FFAF00)>Overheat<c(FFFFFF)>"}
		{"strong_overheat" "<c(FFAF00)>Strong overheat<c(FFFFFF)>"}
		{"antifire" "<c(00FF00)>Fire extinguished<c(FFFFFF)>"}
		{"inventory_broken" "<c(FF1F00)>Ammo detonation<c(FFFFFF)>"}
		{"crew_down" "<c(FFFF00)>Crew killed<c(FFFFFF)>"}
		{"leave_unit" "<c(CCCCCC)>Vehicle abandoned<c(FFFFFF)>"}
		{"empty" ""}
		{"shock" "<c(BBBBBB)>Contusion<c(BBBBBB)>"}
		{"charger_die" "<c(CCCCCC)>Charger dead<c(FFFFFF)>"}
		{"commander_die" "<c(CCCCCC)>Comander dead<c(FFFFFF)>"}
		{"driver_die" "<c(CCCCCC)>Driver dead<c(FFFFFF)>"}
		{"gunner_die" "<c(CCCCCC)>Gunner dead<c(FFFFFF)>"}
		{"gunner2_die" "<c(CCCCCC)>Gunner dead<c(FFFFFF)>"}
;============CW==========
		{"autoloader_malfunction" "<c(FFFF00)>Autoloader damaged<c(FFFFFF)>"}
		{"era_pierced" "<c(BBBBBB)>ERA pierced<c(BBBBBB)>"}
		{"guided_weap_disabled" "<c(1F1FCC)>Guided weapon disabled<c(BBBBBB)>"}
		{"guided_weap_enabled" "<c(1F1FCC)>Guided weapon enabled<c(BBBBBB)>"}
		{"heavy_weap_disabled" "<c(1F1FCC)>Heavy weapon disabled<c(BBBBBB)>"}
		{"heavy_weap_enabled" "<c(1F1FCC)>Heavy weapon enabled<c(BBBBBB)>"}
		{"zpu_disabled" "<c(1F1FCC)>Top mgun Always-off<c(BBBBBB)>"}
		{"zpu_enabled" "<c(1F1FCC)>Top mgun Intellectual<c(BBBBBB)>"}
		{"zpu_careful" "<c(1F1FCC)>Top mgun Always-on<c(BBBBBB)>"}
		{"radar_disabled" "<c(1F1FCC)>Radar disabled<c(BBBBBB)>"}
		{"radar_enabled" "<c(1F1FCC)>Radar enabled<c(BBBBBB)>"}
		{"radar_careful" "<c(1F1FCC)>Radar temporary disabled<c(BBBBBB)>"}
		{"salvo_launch" "<c(1F1FCC)>Salvo launch<c(BBBBBB)>"}
		{"single_launch" "<c(1F1FCC)>Single launch<c(BBBBBB)>"}
		{"cargobay_opened" "<c(1F1FCC)>Cargobay opened<c(BBBBBB)>"}
		{"cargobay_closed" "<c(1F1FCC)>Cargobay closed<c(BBBBBB)>"}
		{"misfire" "<c(1F1FCC)>Misfire<c(BBBBBB)>"}
		{"return_to_base" "<c(1F1FCC)>Return to base<c(BBBBBB)>"}
		{"return_to_base_cancel" "<c(1F1FCC)>Cancel raturn to base<c(BBBBBB)>"}
		{"hydro_steering_off" "<c(1F1FCC)>Variable steering off<c(BBBBBB)>"}
		{"hydro_steering_on" "<c(1F1FCC)>Variable steering on<c(BBBBBB)>"}
		{"smoke_reloading" "<c(1F1FCC)>Smoke discharger reloading<c(BBBBBB)>"}
		{"smoke_reloaded" "<c(1F1FCC)>Smoke discharger ready<c(BBBBBB)>"}
		{"dont_see_anything" "<c(1F1FCC)>I see nothing<c(BBBBBB)>"}
		{"airborne_M"
			{"ammo_storage_autocannon_damaged" "Gun ammo storage damaged"}
			{"ammo_storage_mgun_damaged" "MGun ammo storage damaged"}
			{"OLS_damaged" "<c(FFFF00)>OLS damaged<c(FFFFFF)>"}
			{"wing_damaged" "<c(FFFF00)>Wing damaged<c(FFFFFF)>"}
			{"aileron_damaged" "<c(FFFF00)>Aileron damaged<c(FFFFFF)>"}
			{"elevator_damaged" "<c(FFFF00)>Elevator damaged<c(FFFFFF)>"}
			{"rudder_damaged" "<c(FFFF00)>Rudder damaged<c(FFFFFF)>"}
			{"stabilizer_damaged" "<c(FFFF00)>Stabilizer damaged<c(FFFFFF)>"}
			{"tail_damaged" "<c(FFFF00)>Tail damaged<c(FFFFFF)>"}
			{"flap_damaged" "<c(FFFF00)>Flap damaged<c(FFFFFF)>"}
			{"wheels_damaged" "<c(FFFF00)>Wheels damaged<c(FFFFFF)>"}
			{"engine_damaged" "<c(FF1F00)>Engine damaged<c(FFFFFF)>"}
			{"engine1_damaged" "<c(FFFF00)>Left engine damaged<c(FFFFFF)>"}
			{"engine2_damaged" "<c(FFFF00)>Right engine damaged<c(FFFFFF)>"}
			{"enginea_damaged" "<c(FFFF00)>First engine damaged<c(FFFFFF)>"}
			{"engineb_damaged" "<c(FFFF00)>Second engine damaged<c(FFFFFF)>"}
			{"enginec_damaged" "<c(FFFF00)>Third engine damaged<c(FFFFFF)>"}
			{"engined_damaged" "<c(FFFF00)>Fourth engine damaged<c(FFFFFF)>"}
			{"main_reductor_damaged" "<c(FF1F00)>Main reductor damaged<c(FFFFFF)>"}
			{"main_reductor_malfunction" "<c(FF1F00)>Main reductor malfunction<c(FFFFFF)>"}
			{"propeller_damaged" "<c(FF1F00)>Propeller damaged<c(FFFFFF)>"}
			{"tail_shaft_damaged" "<c(FF1F00)>Tail shaft damaged<c(FFFFFF)>"}
			{"tail_rotor_damaged" "<c(FF1F00)>Tail rotor damaged<c(FFFFFF)>"}
			{"driver_panel_damaged" "<c(FF1F00)>Driver panel damaged<c(FFFFFF)>"}
			{"steering_damaged" "<c(FF1F00)>Steering damaged<c(FFFFFF)>"}
			{"hydrosystem_damaged" "<c(FFFF00)>Hydrosystem damaged<c(FFFFFF)>"}
			{"antifire_damaged" "<c(FFFF00)>Antifire damaged<c(FFFFFF)>"}
			{"hydrosystem_tank_damaged" "<c(FF1F00)>Hydrosystem tank damaged<c(FFFFFF)>"}
			{"PPU_damaged" "<c(FFFF00)>PPU damaged<c(FFFFFF)>"}
			{"APU_damaged" "<c(FFFF00)>APU damaged<c(FFFFFF)>"}
			{"ir_active_def_damaged" "<c(FFFF00)>APS damaged<c(FFFFFF)>"}
			{"ECM_damaged" "<c(FFFF00)>ECM damaged<c(FFFFFF)>"}
			{"targeting_pod_damaged" "<c(FFFF00)>Targeting pod damaged<c(FFFFFF)>"}
			{"electronics_damaged" "<c(FFFF00)>Electronics damaged<c(FFFFFF)>"}
			{"PrPNK_damaged" "<c(FFFF00)>Targeting system damaged<c(FFFFFF)>"}
			{"radar_damaged" "<c(FFFF00)>Radar damaged<c(FFFFFF)>"}
			{"Laser_TD_damaged" "<c(FFFF00)>Target detection laser damaged<c(FFFFFF)>"}
			{"Radar_TD_damaged" "<c(FFFF00)>Target detection radar damaged<c(FFFFFF)>"}
			{"fuel_tank_damaged" "<c(FFAF00)>Fuel tank damaged<c(FFFFFF)>"}
			{"gun_damaged" "<c(FFFF00)>Gun damaged<c(FFFFFF)>"}
			{"mgun_damaged" "<c(FFFF00)>MGun damaged<c(FFFFFF)>"}
			{"ptur_damaged" "<c(FFFF00)>ATM damaged<c(FFFFFF)>"}
			{"nar_damaged" "<c(FFFF00)>NAR block damaged<c(FFFFFF)>"}
			{"flares_damaged" "<c(FFFF00)>Flares block damaged<c(FFFFFF)>"}
			{"chaff_damaged" "<c(FFFF00)>Chaff block damaged<c(FFFFFF)>"}

			{"wing_repaired" "<c(00FF00)>Wing repaired<c(FFFFFF)>"}
			{"aileron_repaired" "<c(00FF00)>Aileron repaired<c(FFFFFF)>"}
			{"elevator_repaired" "<c(00FF00)>Elevator repaired<c(FFFFFF)>"}
			{"rudder_repaired" "<c(00FF00)>Rudder repaired<c(FFFFFF)>"}
			{"stabilizer_repaired" "<c(00FF00)>Stabilizer repaired<c(FFFFFF)>"}
			{"tail_repaired" "<c(00FF00)>Tail repaired<c(FFFFFF)>"}
			{"flap_repaired" "<c(00FF00)>Flap repaired<c(FFFFFF)>"}
			{"wheels_repaired" "<c(00FF00)>Wheels repaired<c(FFFFFF)>"}
			{"engine_repaired" "<c(FF1F00)>Engine repaired<c(FFFFFF)>"}
			{"engine1_repaired" "<c(00FF00)>Left engine repaired<c(FFFFFF)>"}
			{"engine2_repaired" "<c(00FF00)>Right engine repaired<c(FFFFFF)>"}
			{"enginea_repaired" "<c(00FF00)>First engine repaired<c(FFFFFF)>"}
			{"engineb_repaired" "<c(00FF00)>Second engine repaired<c(FFFFFF)>"}
			{"enginec_repaired" "<c(00FF00)>Third engine repaired<c(FFFFFF)>"}
			{"engined_repaired" "<c(00FF00)>Fourth engine repaired<c(FFFFFF)>"}
			{"main_reductor_repaired" "<c(FF1F00)>Main reductor repaired<c(FFFFFF)>"}
			{"propeller_repaired" "<c(00FF00)>Propeller repaired<c(FFFFFF)>"}
			{"main_reductor_repaired" "<c(00FF00)>Main reductor repaired<c(FFFFFF)>"}
			{"tail_shaft_repaired" "<c(FF1F00)>Tail shaft repaired<c(FFFFFF)>"}
			{"tail_rotor_repaired" "<c(FF1F00)>Tail rotor repaired<c(FFFFFF)>"}
			{"driver_panel_repaired" "<c(FF1F00)>Driver panel repaired<c(FFFFFF)>"}
			{"steering_repaired" "<c(FF1F00)>Steering repaired<c(FFFFFF)>"}
			{"hydrosystem_repaired" "<c(00FF00)>Hydrosystem repaired<c(FFFFFF)>"}
			{"hydrosystem_tank_repaired" "<c(00FF00)>Hydrosystem tank repaired<c(FFFFFF)>"}
			{"antifire_repaired" "<c(00FF00)>Antifire repaired<c(FFFFFF)>"}
			{"PPU_repaired" "<c(00FF00)>PPU repaired<c(FFFFFF)>"}
			{"APU_repaired" "<c(00FF00)>APU repaired<c(FFFFFF)>"}
			{"ir_active_def_repaired" "<c(00FF00)>APS repaired<c(FFFFFF)>"}
			{"ECM_repaired" "<c(00FF00)>ECM repaired<c(FFFFFF)>"}
			{"targeting_pod_repaired" "<c(00FF00)>Targeting pod repaired<c(FFFFFF)>"}
			{"electronics_repaired" "<c(00FF00)>Electronics repaired<c(FFFFFF)>"}
			{"PrPNK_repaired" "<c(00FF00)>Targeting system repaired<c(FFFFFF)>"}
			{"radar_repaired" "<c(00FF00)>Radar repaired<c(FFFFFF)>"}
			{"Laser_TD_repaired" "<c(00FF00)>Target detection laser repaired<c(FFFFFF)>"}
			{"Radar_TD_repaired" "<c(00FF00)>Target detection radar repaired<c(FFFFFF)>"}
			{"gun_repaired" "<c(00FF00)>Gun repaired<c(FFFFFF)>"}
			{"mgun_repaired" "<c(00FF00)>MGun repaired<c(FFFFFF)>"}
			{"ptur_repaired" "<c(00FF00)>ATM repaired<c(FFFFFF)>"}
			{"nar_repaired" "<c(00FF00)>NAR block repaired<c(FFFFFF)>"}
			{"flares_repaired" "<c(00FF00)>Flares block repaired<c(FFFFFF)>"}
			{"chaff_repaired" "<c(00FF00)>Chaff block repaired<c(FFFFFF)>"}

			{"reload_zur" "<c(1F1FCC)>Reload SAM<c(BBBBBB)>"}
			{"reload_missile" "<c(1F1FCC)>Reload missile<c(BBBBBB)>"}
		}
		{"armored"
			{"driver_triplex_damaged" "<c(FFFF00)>Driver triplex damaged<c(FFFFFF)>"}
			{"commander_triplex_damaged" "<c(FFFF00)>Commander sight damaged<c(FFFFFF)>"}
			{"additional_triplex_damaged" "<c(FFFF00)>Sight damaged<c(FFFFFF)>"}
			{"additional_triplex1_damaged" "<c(FFFF00)>Sight damaged<c(FFFFFF)>"}
			{"ammo_storage_damaged" "<c(FFAF00)>Ammo storage damaged<c(FFFFFF)>"}
			{"body_pierced" "Hull pierced"}
			{"turret_pierced" "Turret pierced"}
			{"fuel_tank_damaged" "<c(FFAF00)>Fuel tank damaged<c(FFFFFF)>"}
			{"kaz_radar_damaged" "<c(FFFF00)>KAZ radar damaged<c(FFFFFF)>"}
			{"kaz_mortar_damaged" "<c(FFFF00)>KAZ mortar damaged<c(FFFFFF)>"}
			{"Shtora_damaged" "<c(FFFF00)>\"Shtora\" damaged<c(FFFFFF)>"}
			{"gun_damaged" "<c(FFFF00)>Gun damaged<c(FFFFFF)>"}
			{"transmission_damaged" "<c(FF1F00)>Transmission damaged<c(FFFFFF)>"}
			{"panel_engine_connectors_damaged" "<c(FF1F00)>Engine connectors damaged<c(FFFFFF)>"}
			{"front_wheels_damaged" "<c(FF1F00)>Front wheels damaged<c(FFFFFF)>"}
			{"driver_panel_damaged" "<c(FF1F00)>Driver panel damaged<c(FFFFFF)>"}
			{"mgun_damaged" "<c(FFFF00)>MGun damaged<c(FFFFFF)>"}
			{"gun1_damaged" "<c(FFFF00)>Secondary gun damaged<c(FFFFFF)>"}
			{"ptur_damaged" "<c(FFFF00)>ATM damaged<c(FFFFFF)>"}
			{"autoloader_damaged" "<c(FFFF00)>Autoloader damaged<c(FFFFFF)>"}
			{"turret_move_engine_damaged" "<c(FFFF00)>Turret move engine damaged<c(FFFFFF)>"}
			{"stabilizer_damaged" "<c(FFFF00)>Stabilizer damaged<c(FFFFFF)>"}
			{"gunner_panel_damaged" "<c(FFFF00)>Gunner panel damaged<c(FFFFFF)>"}
			{"PPU_damaged" "<c(FFFF00)>PPU damaged<c(FFFFFF)>"}
			{"APU_damaged" "<c(FFFF00)>APU damaged<c(FFFFFF)>"}
			{"hull_integrity_damaged" "<c(FFFF00)>Hull integrity damaged<c(FFFFFF)>"}
			{"driver_dead" "<c(FF1F00)>Crew member killed<c(FFFFFF)>"}
			{"gunner_dead" "<c(FF1F00)>Crew member killed<c(FFFFFF)>"}
			{"shooter_dead" "<c(FF1F00)>Crew member killed<c(FFFFFF)>"}
			{"charger_dead" "<c(FF1F00)>Crew member killed<c(FFFFFF)>"}
			{"commander_dead" "<c(FF1F00)>Crew member killed<c(FFFFFF)>"}
			
			{"driver_triplex_repaired" "<c(00FF00)>Driver tiplex водителя repaired<c(FFFFFF)>"}
			{"commander_triplex_repaired" "<c(00FF00)>Gunner sight repaired<c(FFFFFF)>"}
			{"additional_triplex_repaired" "<c(00FF00)>Sight repaired<c(FFFFFF)>"}
			{"additional_triplex1_repaired" "<c(00FF00)>Sight repaired<c(FFFFFF)>"}
			{"driver_panel_repaired" "<c(00FF00)>Driver panel repaired<c(FFFFFF)>"}
			{"transmission_repaired" "<c(00FF00)>Transmission repaired<c(FFFFFF)>"}
			{"panel_engine_connectors_repaired" "<c(00FF00)>Engine connectors repaired<c(FFFFFF)>"}
			{"front_wheels_repaired" "<c(00FF00)>Front wheels repaired<c(FFFFFF)>"}
			{"autoloader_repaired" "<c(00FF00)>Autoloader repaired<c(FFFFFF)>"}
			{"mgun_repaired" "<c(00FF00)>MGun repaired<c(FFFFFF)>"}
			{"gun_repaired" "<c(00FF00)>Gun repaired<c(FFFFFF)>"}
			{"gun1_repaired" "<c(00FF00)>Secondary gun repaired<c(FFFFFF)>"}
			{"ptur_repaired" "<c(00FF00)>ATM repaired<c(FFFFFF)>"}
			{"kaz_mortar_repaired" "<c(00FF00)>KAZ mortar repaired<c(FFFFFF)>"}
			{"turret_move_engine_repaired" "<c(00FF00)>Turret move engine repaired<c(FFFFFF)>"}
			{"stabilizer_repaired" "<c(00FF00)>Stabilizer repaired<c(FFFFFF)>"}
			{"gunner_panel_repaired" "<c(00FF00)>Gunner panel repaired<c(FFFFFF)>"}
			{"PPU_repaired" "<c(00FF00)>PPU repaired<c(FFFFFF)>"}
			{"APU_repaired" "<c(00FF00)>APU repaired<c(FFFFFF)>"}
			{"hull_integrity_repaired" "<c(00FF00)>Hull integrity repaired<c(FFFFFF)>"}
			{"kaz_radar_repaired" "<c(00FF00)>KAZ radar repaired<c(FFFFFF)>"}
			{"Shtora_repaired" "<c(00FF00)>\"Shtora\" repaired<c(FFFFFF)>"}


		}
		{"other"
			{"ptur_damaged" "<c(FFFF00)>ATM damaged<c(FFFFFF)>"}
			{"ptur_repaired" "<c(00FF00)>ATM repaired<c(FFFFFF)>"}
			{"radar_damaged" "<c(FF1F00)>Radar damaged<c(FFFFFF)>"}
			{"radar_array_damaged" "<c(FFFF00)>Radar array damaged<c(FFFFFF)>"}

		}
		{"selfdestruct"
			{"delay_0" "<c(FF1F00)>180<c(FFFFFF)>"}
			{"delay_10" "<c(FF1F00)>170<c(FFFFFF)>"}
			{"delay_20" "<c(FF1F00)>160<c(FFFFFF)>"}
			{"delay_30" "<c(FF1F00)>150<c(FFFFFF)>"}
			{"delay_40" "<c(FF1F00)>140<c(FFFFFF)>"}
			{"delay_50" "<c(FF1F00)>130<c(FFFFFF)>"}
			{"delay_60" "<c(FF1F00)>120<c(FFFFFF)>"}
			{"delay_70" "<c(FF1F00)>110<c(FFFFFF)>"}
			{"delay_80" "<c(FF1F00)>100<c(FFFFFF)>"}
			{"delay_90" "<c(FF1F00)>90<c(FFFFFF)>"}
			{"delay_100" "<c(FF1F00)>80<c(FFFFFF)>"}
			{"delay_110" "<c(FF1F00)>70<c(FFFFFF)>"}
			{"delay_120" "<c(FF1F00)>60<c(FFFFFF)>"}
			{"delay_130" "<c(FF1F00)>50<c(FFFFFF)>"}
			{"delay_140" "<c(FF1F00)>40<c(FFFFFF)>"}
			{"delay_150" "<c(FF1F00)>30<c(FFFFFF)>"}
			{"delay_160" "<c(FF1F00)>20<c(FFFFFF)>"}
			{"delay_170" "<c(FF1F00)>10<c(FFFFFF)>"}
			{"delay_171" "<c(FF1F00)>9<c(FFFFFF)>"}
			{"delay_172" "<c(FF1F00)>8<c(FFFFFF)>"}
			{"delay_173" "<c(FF1F00)>7<c(FFFFFF)>"}
			{"delay_174" "<c(FF1F00)>6<c(FFFFFF)>"}
			{"delay_175" "<c(FF1F00)>5<c(FFFFFF)>"}
			{"delay_176" "<c(FF1F00)>4<c(FFFFFF)>"}
			{"delay_177" "<c(FF1F00)>3<c(FFFFFF)>"}
			{"delay_178" "<c(FF1F00)>2<c(FFFFFF)>"}
			{"delay_179" "<c(FF1F00)>1<c(FFFFFF)>"}
		}