{"attack" "Attack"}
		{"attack"
			{"action" "Attack enemy units."}
			{"usage" "Click on an enemy unit to attack it. Click on a destination to order your squad to fight their way towards it."}
		}
		{"attack_ground" "Attack ground"}
		{"attack_ground"
			{"action" "Attack ground"}
			{"usage" "Choose a spot to cover."}
		}
		{"cancel" "Cancel"}
		{"cancel"
			{"action" "Cancel all orders issued to the selected units."}
		}
		{"drop" "Drop"}
		{"drop"
			{"action" "Drop the currently held item."}
			{"usage" "After clicking the button, click the unit, item, or place where you wish to drop the item."}
		}
		{"examine" "Examine"}
		{"examine"
			{"action" "Examine inventory"}
			{"usage" "Click item or unit whose inventory you want to examine."}
		}
		{"collect" "Take"}
		{"collect"
			{"action" "Pick up"}
			{"usage" "After clicking the button, specify an object to pick up from the ground."}
		}
		{"rotate" "Turn"}
		{"rotate"
			{"action" "Turn around or aim at the selected destination."}
			{"usage" "Click this button, then click on the area that the selected unit should face."}
		}
		{"use" "Use item"}
		{"spread" "Spread out"}
		{"suppression_fire" "Suppressive fire"}
		{"suppression_fire"
			{"action" "Suppressive fire"}
			{"usage" "Click this button, then click enemy unit or terrain at which to direct suppressive fire."}
		}
		{"aimed_shot" "Aimed shot"}
		{"aimed_shot"
			{"action" "Fire a shot from a sniper rifle."}
			{"usage" "Click this button and then click an enemy unit you want to shoot using the sniper rifle."}
		}
		{"bazooka_shot" "Rocket launcher shot"}
		{"bazooka_shot"
			{"action" "Fire a rocket launcher."}
			{"usage" "Click the button, then click on the selected target to fire a rocket."}
		}
		{"throw_at_grenade" "Anti-tank grenade"}
		{"throw_at_grenade"
			{"action" "Throw an AT grenade."}
			{"usage" "Click on the button, then click an enemy unit or a location at which to throw the grenade."}
		}
		{"throw_ap_grenade" "Anti-personnel grenade"}
		{"throw_ap_grenade"
			{"action" "Throw an AP grenade."}
			{"usage" "Click on the button, then click an enemy unit or a location at which to throw the grenade."}
		}
		{"weapon_prepare"
			{"on" "Draw/holster weapon."}
			{"on"
				{"action" "Draw weapon"}
			}
			{"off" "Draw/holster weapon."}
			{"off"
				{"action" "Holster weapon"}
			}
		}
		{"weapon_unprepare" ""}
		{"weapon_reload" ""}
		{"weapon_reload"
			{"action" ""}
			{"on" "Load or reload weapon"}
			{"on"
				{"action" "Reload weapon"}
			}
			{"off" "Load or reload weapon"}
			{"off"
				{"action" "Unload weapon"}
			}
		}
		{"leave_unit" "Exit vehicle"}
		{"advance" "Advance"}
		{"repair" "Repair"}
		{"repair"
			{"action" "Repair vehicle"}
			{"usage" "Click on the button, then click on a damaged vehicle that you want to repair."}
		}
		{"free_fire" "Fire at will"}
		{"back_fire" "Return fire"}
		{"hold_fire" "Hold fire"}
		{"hold_position" "Hold position"}
		{"move_at_will" ""}
		{"move_fast" ""}
		{"move_slow" ""}
		{"human"
			{"stand" ""}
			{"squat" ""}
			{"lie" ""}
			{"lie"
				{"action" ""}
				{"usage" ""}
			}
			{"heal" "Heal"}
			{"heal"
				{"action" "Heal the selected soldier."}
			}
			{"attack_melee" "Melee attack"}
			{"attack_melee"
				{"action" "Perform a melee attack."}
				{"usage" "Click the button, then click an enemy soldier to attack in hand-to-hand combat."}
			}
			{"fortification" "Fortify area"}
			{"fortification"
				{"action" "Use to erect a fortification around a target structure."}
				{"usage" "Click the button and choose a structure that supports fortification(s)."}
			}
			{"pose"
				{"normal" "Change stance"}
				{"normal"
					{"action" "Stand"}
					{"usage" "Click the button to change soldier's stance: standing, squatting, or prone."}
				}
				{"squat" "Change stance"}
				{"squat"
					{"action" "Squat"}
					{"usage" "Click the button to change soldier's stance: standing, squatting, or prone."}
				}
				{"crawl" "Change stance"}
				{"crawl"
					{"action" "Prone"}
					{"usage" "Click the button to change soldier's stance: standing, squatting, or prone."}
				}
			}
		}
		{"vehicle"
			{"emit" "Unload crew"}
			{"emit"
				{"action" "Unload crew from the selected vehicle."}
				{"usage" "After clicking the button, click the location where you want to unload your crew."}
			}
			{"smoke_decoy" "Smoke Decoy"}
			{"smoke_decoy"
				{"action" "Create a wall of smoke in front of your vehicle."}
				{"usage" "Use this to escape from tricky situations."}
			}
			{"mount" "Firing position"}
			{"unmount" "Towed position"}
			{"board" "Enter vehicle"}
		}
		{"squad"
			{"call_ally" "Call for ally"}
			{"set_commander" "Set squad commander"}
			{"dismiss" "Dismiss squad"}
			{"control" "Dismiss squad"}
			{"control"
				{"action" "The selected squad will be dismissed."}
			}
		}
		{"mine" "Mine"}
		{"mine"
			{"usage" "After clicking the button, click the location where you wish to plant the mine."}
		}
		{"trench_medium" "Dig in a two-man fighting position"}
		{"trench_medium"
			{"usage" "After clicking the button, right click drag will set cover rotation and position."}
		}
		{"trench_small" "Dig in a foxhole"}
		{"trench_small"
			{"usage" "After clicking the button, right click drag will set cover rotation and position."}
		}
		{"place_netting" "Camo Net"}
		{"place_netting"
			{"usage" "Expand camouflage net around vehicle"}
		}
		{"flashmine" "Signal flashmine"}
		{"flashmine"
			{"usage" "After clicking the button, click the location where you wish to plant the mine."}
		}
		{"frogmine" "Bouncing mine"}
		{"frogmine"
			{"usage" "After clicking the button, click the location where you wish to plant the mine."}
		}
		{"set_grenademine_f1" "F1 trapmine"}
		{"set_grenademine_f1"
			{"usage" "After clicking the button, click the location where you wish to plant the trapmine."}
		}
		{"set_grenademine_rgd" "RGD trapmine"}
		{"set_grenademine_rgd"
			{"usage" "After clicking the button, click the location where you wish to plant the trapmine."}
		}
		{"set_grenademine_rgn" "RGN trapmine"}
		{"set_grenademine_rgn"
			{"usage" "After clicking the button, click the location where you wish to plant the trapmine."}
		}
		{"set_grenademine_rgo" "RGO trapmine"}
		{"set_grenademine_rgo"
			{"usage" "After clicking the button, click the location where you wish to plant the trapmine."}
		}
		{"set_grenademine_m61" "M61 trapmine"}
		{"set_grenademine_m61"
			{"usage" "After clicking the button, click the location where you wish to plant the trapmine."}
		}
		{"set_grenademine_m67" "M67 trapmine"}
		{"set_grenademine_m67"
			{"usage" "After clicking the button, click the location where you wish to plant the trapmine."}
		}
		{"set_grenademine_dm51gr" "DM51 trapmine"}
		{"set_grenademine_dm51gr"
			{"usage" "After clicking the button, click the location where you wish to plant the trapmine."}
		}
		{"set_grenademine_of37" "OF-37 trapmine"}
		{"set_grenademine_of37"
			{"usage" "After clicking the button, click the location where you wish to plant the trapmine."}
		}
		{"set_grenademine_shgr56" "Shgr56 trapmine"}
		{"set_grenademine_shgr56"
			{"usage" "After clicking the button, click the location where you wish to plant the trapmine."}
		}
		{"mine_directional" "Directional mine"}
		{"mine_directional"
			{"usage" "After clicking on the button, click and drag on the location where you wish to plant the mine in order to define the direction of the mine."}
		}
		{"mine_efp_side" "Off-route anti-tank mine"}
		{"mine_efp_side"
			{"usage" "After clicking on the button, click and drag on the location where you wish to plant the mine in order to define the direction of the mine."}
		}
		{"scud_dummy" "SCUD dummy"}
		{"scud_dummy"
			{"usage" "After clicking the button, click the location where you wish to put the dummy"}
		}
		{"mine_detection" "Clear mines"}
		{"mine_detection"
			{"usage" "After clicking the button, click the location you want cleared of mines."}
		}
		{"specability" "Specail ability"}
		{"specability"
			{"usage" "Use special ability: turn off heavy weapons, perform paradrops from cargo plane or disembark from hovercraft, deploy ropes from transport helicopter."}
		}
		{"switch_hatch" "Top mgun mode"}
		{"switch_hatch"
			{"usage" "Press the button to switch top mgun mode: Always-off, Intellectual, Always-on. For helicopters - disembark passengers. For SAMs - radar mode:15 seconds off, Always-off, Always-on."}
		}
		{"diagnostics" "Diagnostics"}
		{"diagnostics"
			{"usage" "Press to check vehicle state report"}
		}
		{"put_dynamite" "Put dynamite"}
		{"put_dynamite"
			{"usage" "After clicking the button, click the place where you want to plant dynamite."}
		}
		{"plant" "Camouflage"}
		{"plant"
			{"usage" "After clicking the button, specify where you want to place a camouflage bush."}
		}
		{"hedgehog" "Deploy a hedgehog"}
		{"hedgehog"
			{"usage" "After clicking the button, click the location to place an anti-tank hedgehog."}
		}
		{"injection" "Inject morphine"}
		{"injection"
			{"usage" "Click the button, then click on the injured soldier to inject morphine."}
		}
		{"burn" "Set alight"}
		{"burn"
			{"usage" "Click on the button, then choose an object you want to set alight."}
		}
		{"attach" ""}
		{"attach"
			{"action" ""}
			{"on" "Attach cargo"}
			{"off" "Detach cargo"}
		}
		{"detach" ""}
		{"supply" ""}
		{"supply"
			{"on" "Enable auto resupply"}
			{"on"
				{"action" "Enable auto resupply of your unit."}
			}
			{"off" "Disable auto resupply"}
			{"off"
				{"action" "Disable auto resupply of your unit."}
			}
		}
		{"altitude" ""}
		{"altitude"
			{"travel" "Ascend"}
			{"travel"
				{"action" "Ascend to optimal travel altitude."}
			}
			{"surface" "Descend"}
			{"surface"
				{"action" "Descend to ground level."}
			}
			{"surface_warning" "Descend"}
			{"surface_warning"
				{"action" "Descend to ground level."}
				{"usage" "<c(e74236)>Beware possibly unsafe landing ground!</c>"}
			}
		}
		{"manual_control" "Direct Control mode"}
		{"manual_control"
			{"action" "Enable / Disable direct control over the selected unit."}
			{"usage" "While in direct control mode, use the cursor to aim and the directional keys to move."}
		}
		{"inventory" "Inventory"}
		{"inventory"
			{"action" "Show/hide the selected unit's inventory."}
		}
		{"objectives" "Objectives"}
		{"objectives"
			{"action" "Show/hide mission objectives."}
		}
		{"message_history" "Message history"}
		{"message_history"
			{"action" "Show/hide message history."}
		}
		{"map" "Mini-map"}
		{"map"
			{"action" "Show/hide mini-map."}
		}
		{"map_control" "Map setup"}
		{"map_control"
			{"docking" "Position"}
			{"docking#"
				{"topleft" "Top Left"}
				{"topright" "Top Right"}
			}
			{"docking_editor" "Position"}
			{"docking_editor#"
				{"topleft" "Top Left"}
				{"topright" "Top Right"}
			}
			{"size" "Size"}
			{"opacity" "Transparency"}
			{"clickable" "Management"}
;			{"action" "Show/hide map controls."}
			{"show_tracers" "Tracers"}
			{"show_compass_icons" "Compass icons"}
			{"show_squad_icons" "Show squad icons"}
			{"enable_squad_icons" "Enable/disable squad icons"}
			{"show_hit_cursor" "Show hit information"}
			{"show_damage_messages" "Show info messages"}
			{"show_waypoints" "Show waypoints"}
			{"show_kill_stream" "Enable event log stream"}
		}
		{"minimap_zoom_in" "Zoom in"}
		{"minimap_zoom_in"
			{"usage" "Click to zoom in the mini-map."}
		}
		{"minimap_zoom_out" "Zoom out"}
		{"minimap_zoom_out"
			{"usage" "Click to zoom out the mini-map."}
		}
		{"minimap_fade_in" "Decrease transparency"}
		{"minimap_fade_out" "Increase transparency"}
		{"game_menu" "Game menu"}
		{"game_menu"
			{"action" "Switch to the main game menu"}
		}
		{"count_fx" "<f(arial_hq)s(8)c(FFFFFF)p(0)x.e(shadow)>%1%"}
		{"count_fx_red" "<f(arial_hq)s(8)c(c8c8c8)p(0)x.e(shadow)>%1%"}
		{"count_black" "<f(arial_hq)s(8)c(0 0 0)p(0)x.>%1%"}
		{"count_white" "<f(arial_hq)s(8)c(200 200 200)p(0)x.>%1%"}
		{"highlight"
			{"stuff" "Highlight Items"}
			{"stuff"
				{"action" "Enable/disable highlighting of items on the ground."}
			}
			{"corpses" "Highlight Corpses"}
			{"corpses"
				{"action" "Enable/disable highlighting of corpses."}
			}
			{"silhouettes" "Highlight Silhouettes"}
			{"silhouettes"
				{"action" "Enable/disable highlighting of soldiers' silhouettes."}
			}
		}
		{"dummy" "Button slot"}
		{"dummy"
			{"usage" "Right-click, then drag and drop frequently used buttons from the right panel into this slot."}
		}
		{"fire" ""}
		{"fire"
			{"action" ""}
			{"usage" ""}
			{"free" "Firing mode"}
			{"free"
				{"action" "Fire at will"}
				{"usage" "Click this button to switch between firing modes: Hold fire, Return fire, and Fire at will."}
			}
			{"hold" "Firing mode"}
			{"hold"
				{"action" "Hold fire"}
				{"usage" "Click this button to switch between firing modes: Hold fire, Return fire, and Fire at will."}
			}
			{"back" "Firing mode"}
			{"back"
				{"action" "Return fire"}
				{"usage" "Click this button to switch between firing modes: Hold fire, Return fire, and Fire at will."}
			}
		}
		{"move" ""}
		{"move"
			{"action" ""}
			{"usage" ""}
			{"at_will" "Movement mode"}
			{"at_will"
				{"action" "Move at will"}
				{"usage" "Click this button to switch between the different movement modes: Hold position or Move at will."}
			}
			{"hold" "Movement mode"}
			{"hold"
				{"action" "Hold position"}
				{"usage" "Click this button to switch between the different movement modes: Hold position or Move at will."}
			}
		}
		{"cannon" ""}
		{"cannon"
			{"action" ""}
			{"usage" ""}
			{"fire" "Change artillery position"}
			{"fire"
				{"action" "Firing position"}
				{"usage" "Click this button to toggle between an artillery piece's Firing and Towing modes."}
			}
			{"move" "Change artillery position"}
			{"move"
				{"action" "Towed position"}
				{"usage" "Click this button to toggle between an artillery piece's Firing and Towing modes."}
			}
		}
		{"browse_useitem" "Use item"}
		{"browse_useitem"
			{"usage" "After clicking the button, choose the desired action for the inventory item."}
		}
		{"browse_special" "Submenu"}
		{"browse_special"
			{"usage" "Opens up another menu."}
		}

		{"browse_attack" "Attack options"}
		{"browse_attack"
			{"usage" "Click the button, then select desired attack mode."}
		}
		{"browse_back" "Back"}
		{"browse_back"
			{"action" "Return to the previous menu."}
		}
		{"key_hint" "%1% (<c(ffff60)>%2%</c>)"}
		{"throw_sk_grenade" "Smoke grenade"}
		{"throw_sk_grenade"
			{"action" "Throw a smoke grenade"}
			{"usage" "After clicking this button, click the location where you want to place a smoke grenade."}
		}
		{"barricade" "Set breastwork"}
		{"barricade"
			{"usage" "After clicking this button, select a place on the map for building a breastwork."}
		}
		{"barbwire" "Set barbed wire"}
		{"barbwire"
			{"usage" "After clicking this button, select a place on the map for rolling out some barbed wire."}
		}
		{"round_sandbag" "Fortify position"}
		{"round_sandbag"
			{"action" "Build a ring of breastwork to protect the gun."}
		}
		{"chat" "Chat"}
		{"chat"
			{"action" "Show/hide chat window."}
		}
		{"score_table" "Score table"}
		{"score_table"
			{"action" "Show/hide score table."}
		}
		{"videocapture" "Capture video"}
		{"videocapture"
			{"action" "Toggle video capture on/off."}
		}
		{"event_history" "Event history"}
		{"event_history"
			{"action" "Show/hide event history."}
		}
		{"transfer" "Unit transfer"}
		{"transfer"
			{"action" "Selected units will be transferred to chosen player in your team."}
		}
		{"frontline_retreat" "Retreat"}
		{"frontline_retreat"
			{"action" "Retreat to the next line of defenses and receive new resources."}
		}
		{"cp_current" "Current CP value"}
		{"cp_current"
			{"action" "Value raises with every purchased unit. Cannot exceed the limit."}
		}
		{"mp_available_points" "MP Points"}
		{"mp_available_points"
			{"action" "Shows how much you can spend on troops."}
		}
		{"mp_per_second" "MP / Second"}
		{"mp_per_second"
			{"action" "Shows how many MP you gain every second."}
		}
		{"mp_payback" "MP Payback"}
		{"mp_payback"
			{"action" "Regain some MP for troops that you've lost."}
		}
		{"vehicle_fuel" "Remaining Fuel"}
		{"vehicle_fuel"
			{"action" "This vehicle needs fuel to run. It can be re-filled."}
		}
		{"vehicle_supplies" "Remaining Supplies"}
		{"vehicle_supplies"
			{"action" "This vehicle supplies your troops with equipment. It refills itself automatically."}
		}
		{"vehicle_speed" "Remaining Speed"}
		{"vehicle_speed"
			{"action" "Remaining Speed."}
		}
		{"vehicle_armor" "Remaining Armor"}
		{"vehicle_armor"
			{"action" "Remaining Armor."}
		}